(() => {
'use strict';
const $ = id => document.getElementById(id);
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
class AdminApp {
  constructor(){
    this.token=sessionStorage.getItem('bingoOnlineAdminToken:owner')||'';
    this.state=null;this.events=null;this.reconnectTimer=null;this.mode=75;
    this.markingMode='normal';this.maxCardsPerPlayer=4;this.linePrizeCount=1;
    this.rules={line:true,corners:true,doubleLine:false,tripleLine:false,ambocabeza:false,bingo:true};
    this.transmission={showChat:true,showCards:true,showNames:true,showProgress:true,rotationSeconds:30};
    this.drawerTab='numbers';this.sound=true;this.lastBall=null;this.claimShown='';this.claimTimer=null;this.currentClaimOpen=true;this.seenAdminChatIds=new Set();this.autoResumeClockTimer=null;
  }
  async init(){
    this.fillCounts();this.bind();this.applyTheme();this.autoResumeClockTimer=setInterval(()=>this.updateAutoResumeCountdown(),250);
    if(!this.token) return this.show('authView');
    try{
      const action=new URLSearchParams(location.search).get('accion');
      if(action==='nuevo'){
        await this.req('/api/admin/new-room',{method:'POST',body:'{}'});
        history.replaceState({},'',location.pathname);
      }
      await this.refresh();this.connect();
    }catch{this.token='';sessionStorage.removeItem('bingoOnlineAdminToken:owner');this.show('authView')}
  }
  bind(){
    $('adminLoginBtn').onclick=()=>this.login();$('adminPassword').onkeydown=e=>e.key==='Enter'&&this.login();
    document.querySelectorAll('#markingModeChoices [data-value]').forEach(b=>b.onclick=()=>{this.markingMode=b.dataset.value;this.activateGroup('markingModeChoices',b);this.updateConfig()});
    document.querySelectorAll('#modeChoices [data-value]').forEach(b=>b.onclick=()=>{this.mode=Number(b.dataset.value);this.activateGroup('modeChoices',b);this.renderRules();this.updateConfig()});
    document.querySelectorAll('#lineCountChoices [data-value]').forEach(b=>b.onclick=()=>{this.linePrizeCount=Number(b.dataset.value)===2?2:1;document.querySelectorAll('#lineCountChoices [data-value]').forEach(x=>x.classList.toggle('active',x===b));this.updateConfig()});const ambo90=document.getElementById('ambo90Choice');if(ambo90)ambo90.onclick=()=>{this.rules.ambocabeza=!this.rules.ambocabeza;ambo90.classList.toggle('active',this.rules.ambocabeza);this.updateConfig()};
    ['intervalSelect','cardCount'].forEach(id=>{const el=$(id);if(el)el.onchange=()=>this.updateConfig()});
    $('testVoiceBtn').onclick=()=>this.testVoice();$('liveTransmissionBtn').onclick=()=>this.openTransmissionSettings();$('waitingTransmissionBtn').onclick=()=>this.openTransmission();$('closeTransmission').onclick=()=>this.closeModal('transmissionModal');$('saveTransmission').onclick=()=>this.saveTransmission();$('openTransmission').onclick=()=>this.openTransmission();$('copyTransmission').onclick=()=>this.copy(this.state?.broadcastUrl||'');$('castTransmission').onclick=()=>this.castTransmission();
    $('createRoomBtn').onclick=()=>this.createRoom();$('createSimulationBtn').onclick=()=>this.createSimulation();$('mobilePreviewBtn').onclick=()=>this.openMobilePreview(false);$('closeMobilePreview').onclick=()=>this.closeModal('mobilePreviewModal');$('loadMobilePreview').onclick=()=>this.loadMobilePreview();$('rotateMobilePreview').onclick=()=>this.rotateMobilePreview();$('mobilePreviewSize').onchange=()=>this.applyMobilePreviewSize();$('mobilePreviewPlayer').onchange=()=>this.loadMobilePreview();$('startBtn').onclick=()=>this.start();$('closeRoomBtn').onclick=()=>this.closeRoom();$('confirmLargeStartBtn').onclick=()=>this.confirmLargeRoomStart();$('cancelLargeStartBtn').onclick=()=>this.closeModal('startCriterionModal');
    $('invitePlayerBtn').onclick=()=>this.invitePlayer();$('inviteName').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();this.invitePlayer()}};$('inviteBulkBtn').onclick=()=>this.inviteBulk();
    $('pauseBtn').onclick=()=>this.pauseResume();$('keepPausedBtn').onclick=()=>this.keepPaused();$('drawNowBtn').onclick=()=>this.draw();$('finishBtn').onclick=()=>this.finish();$('liveInterval').onchange=()=>this.updateInterval();
    $('onlineTab').onclick=()=>this.setSide('online');$('chatTab').onclick=()=>this.setSide('chat');$('adminChatSend').onclick=()=>this.sendChat();$('adminChatInput').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();this.sendChat()}};$('chatLockBtn').onclick=()=>this.chatAction(this.state?.chat?.locked?'unlock':'lock');$('chatClearBtn').onclick=()=>confirm('¿Borrar todos los mensajes visibles?')&&this.chatAction('clear');
    $('drawerToggle').onclick=()=>this.toggleDrawer();$('drawerClose').onclick=()=>this.toggleDrawer(false);document.querySelectorAll('[data-drawer]').forEach(b=>b.onclick=()=>{this.drawerTab=b.dataset.drawer;this.renderDrawer()});
    $('closeClaimBtn').onclick=()=>{this.currentClaimOpen=false;$('claimOverlay').classList.remove('show');this.claimShown='';};$('themeBtn').onclick=()=>this.toggleTheme();$('soundBtn').onclick=()=>{this.sound=!this.sound;$('soundBtn').textContent=this.sound?'🔊':'🔇'};$('fullBtn').onclick=()=>this.fullscreen();$('homeBtn').onclick=()=>location.href='/admin';
    $('viewPdfBtn').onclick=()=>this.showPdf();$('closePdf').onclick=()=>this.closeModal('pdfModal');$('newRoomBtn').onclick=()=>this.newRoom();
    $('adminChatList').addEventListener('click',event=>window.BingoEmojiStickers?.replay(event.target));
  }

  show(id){['authView','configView','waitingView','liveView','finishedView'].forEach(x=>$(x).classList.toggle('hidden',x!==id))}
  activateGroup(id,active){$(id).querySelectorAll('[data-value]').forEach(b=>b.classList.toggle('active',b===active))}
  fillCounts(){for(let n=50;n<=250;n+=50)$('cardCount').insertAdjacentHTML('beforeend',`<option value="${n}" ${n===250?'selected':''}>${n}</option>`);this.renderRules();this.updateConfig()}
  renderRules(){
    const host=$('optionalRules');
    if(this.mode===75)host.innerHTML='<label><input data-rule="corners" type="checkbox"> 4 esquinas</label><label><input data-rule="doubleLine" type="checkbox"> Doble línea</label><label><input data-rule="tripleLine" type="checkbox"> Triple línea</label>';
    else host.innerHTML='<span class="muted">En 90 bolas: AmboCabeza opcional + 1 o 2 líneas + Bingo. Con 2 líneas, los reclamos válidos conservan su orden global.</span>';
    host.querySelectorAll('[data-rule]').forEach(input=>{this.rules[input.dataset.rule]=input.checked;input.onchange=()=>{this.rules[input.dataset.rule]=input.checked;this.updateConfig()}});
    if(this.mode===90){this.rules.corners=false;this.rules.doubleLine=false;this.rules.tripleLine=false;this.rules.line=true;this.rules.bingo=true;const ambo=document.getElementById('ambo90Choice');if(ambo)ambo.classList.toggle('active',!!this.rules.ambocabeza);}
  }
  updateConfig(){
    this.maxCardsPerPlayer=this.markingMode==='manual_only'?2:4;
    $('lineCount90')?.classList.toggle('hidden',this.mode!==90);
    if($('markingModeHelp'))$('markingModeHelp').innerHTML=this.markingMode==='manual_only'?'<b>SOLO MANUAL · MÁXIMO 2</b><span>Cada invitación nueva autoriza hasta 2 cartones y Automarcado no aparece.</span>':'<b>4 CARTONES POR DEFECTO</b><span>Cada invitación nueva autoriza hasta 4 cartones. El administrador puede bajar la cantidad individualmente.</span>';
    if($('inviteCards')){const max=this.maxCardsPerPlayer;[...$('inviteCards').options].forEach(o=>o.disabled=Number(o.value)>max);if(Number($('inviteCards').value)>max)$('inviteCards').value=String(max);}
    if($('bulkCards')){const max=this.maxCardsPerPlayer;[...$('bulkCards').options].forEach(o=>o.disabled=Number(o.value)>max);if(Number($('bulkCards').value)>max)$('bulkCards').value=String(max);}
    $('configSummary').innerHTML=`<b>${this.markingMode==='manual_only'?'SOLO MANUAL':'NORMAL'} · ${this.mode} BOLAS</b><span>${$('cardCount').value} cartones únicos generados${this.mode===90?` · ${this.rules.ambocabeza?'AmboCabeza + ':''}${this.linePrizeCount} línea${this.linePrizeCount===1?'':'s'} + Bingo`:''}</span><span>Invitaciones privadas: ${this.maxCardsPerPlayer} cartones por defecto</span><span>Chat y minijuegos activos en la sala de espera · Transmisión creada automáticamente</span><span>Intervalo: ${$('intervalSelect').value} s</span>`;
  }

  async saveTransmission(){this.transmission={showChat:$('txChat').checked,showCards:$('txCards').checked,showNames:$('txNames').checked,showProgress:$('txProgress').checked,rotationSeconds:Number($('txRotation').value)||30};this.updateConfig();try{if(this.state?.active){const alias=$('txAlias').value.trim();const data=await this.req('/api/admin/settings',{method:'POST',body:JSON.stringify({transmission:this.transmission,broadcastAlias:alias})});this.apply(data);this.toast('Transmisión actualizada')}}catch(e){this.toast(e.message);return}this.closeModal('transmissionModal')}
  openTransmissionSettings(){const tx=this.state?.roomSettings?.transmission||this.transmission;this.transmission={...this.transmission,...tx};$('txChat').checked=this.transmission.showChat!==false;$('txCards').checked=this.transmission.showCards!==false;$('txNames').checked=this.transmission.showNames!==false;$('txProgress').checked=this.transmission.showProgress!==false;$('txRotation').value=String(this.transmission.rotationSeconds||30);if(!$('txRotation').value)$('txRotation').value='30';$('txAlias').value=this.state?.roomSettings?.broadcastAlias||'';$('txLinkPreview').textContent=this.state?.broadcastUrl?`Link: ${this.state.broadcastUrl}`:'Se genera al crear la sala.';$('castTransmission').disabled=!this.state?.active;this.openModal('transmissionModal')}
  async castTransmission(){if(!this.state?.broadcastUrl)return this.toast('Primero creá la sala.');try{await window.LaGordaCast.castUrl(this.state.broadcastUrl,this.state.castAppId);this.toast('Elegí tu Chromecast o TV compatible.')}catch(e){this.toast(e.message)}}
  async req(url,opt={}){const r=await fetch(url,{...opt,headers:{'Content-Type':'application/json',...(this.token?{'X-Admin-Token':this.token}:{}),...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'No se pudo completar la acción.');return d}
  async login(){try{const d=await this.req('/api/admin/login',{method:'POST',body:JSON.stringify({password:$('adminPassword').value})});this.token=d.token;sessionStorage.setItem('bingoOnlineAdminToken:owner',this.token);await this.refresh();this.connect()}catch(e){$('authError').innerHTML=`<div class="errorBox">${esc(e.message)}</div>`}}
  async refresh(){this.apply(await this.req('/api/admin/state'))}
  connect(){this.events?.close();clearTimeout(this.reconnectTimer);this.events=new EventSource(`/api/events?role=admin&adminToken=${encodeURIComponent(this.token)}`);this.events.addEventListener('state',e=>{clearTimeout(this.reconnectTimer);this.apply(JSON.parse(e.data))});this.events.addEventListener('chat',e=>{const m=JSON.parse(e.data);this.state?.chat?.messages&&!this.state.chat.messages.some(x=>x.id===m.id)&&this.state.chat.messages.push(m);if(this.state?.chat){this.state.chat.messages=this.state.chat.messages.slice(-100);this.renderChat()}});this.events.addEventListener('chat-control',e=>{if(!this.state)return;this.state.chat={...(this.state.chat||{}),...JSON.parse(e.data)};this.renderChat()});this.events.addEventListener('logout',()=>{sessionStorage.removeItem('bingoOnlineAdminToken:owner');location.reload()});this.events.onerror=()=>{clearTimeout(this.reconnectTimer);this.reconnectTimer=setTimeout(async()=>{if(!this.token)return;try{await this.refresh();if(this.events?.readyState===EventSource.CLOSED)this.connect()}catch{}},1200)}}
  renderSimulationPlayerControl(){
    const roomActive=Boolean(this.state?.active);
    $('mobilePreviewBtn')?.classList.toggle('hidden',!roomActive);
    $('mobilePreviewBtn').textContent='👁';
    $('mobilePreviewBtn').title='Ver jugador';
  }
  async createRoom(){
    try{
      $('createRoomBtn').disabled=true;$('configError').innerHTML='';this.updateConfig();
      const payload={roomType:'alpha',mode:this.mode,cardCount:Number($('cardCount').value),autoSeconds:Number($('intervalSelect').value),rules:this.rules,linePrizeCount:this.mode===90?this.linePrizeCount:1,markingMode:this.markingMode,maxCardsPerPlayer:this.maxCardsPerPlayer};
      const data=await this.req('/api/admin/create-simple-room',{method:'POST',body:JSON.stringify(payload)});this.apply(data);this.toast('Partida creada. Agregá jugadores y mandales su link privado.');
    }catch(e){$('configError').innerHTML=`<div class="errorBox">${esc(e.message)}</div>`}finally{$('createRoomBtn').disabled=false}
  }

  async createSimulation(){const count=Math.max(2,Math.min(60,Number($('simulationPlayers').value)||20)),aiChatEnabled=$('simulationChat')?.checked!==false;if(!confirm(`Crear una simulación interna con ${count} jugadores IA y entre 1 y 4 cartones aleatorios por jugador${aiChatEnabled?', con chat simulado':''}?`))return;try{$('createSimulationBtn').disabled=true;$('simulationError').innerHTML='';const data=await this.req('/api/admin/create-ai-simulation',{method:'POST',body:JSON.stringify({playerCount:count,mode:this.mode,autoSeconds:Number($('intervalSelect').value),rules:this.rules,linePrizeCount:this.mode===90?this.linePrizeCount:1,aiChatEnabled})});this.apply(data);this.toast(`Simulación creada: ${data.players.length} IA · ${data.preflight?.activeCards||0} cartones${aiChatEnabled?' · chat IA activo':''}.`)}catch(e){$('simulationError').innerHTML=`<div class="errorBox">${esc(e.message)}</div>`}finally{$('createSimulationBtn').disabled=false}}
  apply(data){const previous=this.state,previousLast=this.lastBallOf(previous),nextLast=this.lastBallOf(data);this.state=data;this.renderSimulationPlayerControl();if(data?.roomSettings?.transmission)this.transmission={...this.transmission,...data.roomSettings.transmission};if(!data.active){$('drawerToggle').classList.add('hidden');this.show('configView');this.updateConfig();return}$('drawerToggle').classList.remove('hidden');const ballChanged=previousLast!==nextLast;if(data.status==='waiting'||data.status==='starting'){this.show('waitingView');this.renderWaiting()}else if(data.status==='finished'){this.show('finishedView');this.renderFinished()}else{this.show('liveView');this.renderLive(ballChanged)}this.renderClaim();this.renderDrawer();if(previous?.game?.drawn?.length!==data.game?.drawn?.length&&this.sound&&nextLast!=null)this.beep()}
  renderWaiting(){
    const d=this.state,isSimulation=Boolean(d.roomSettings?.adminSimulation),manual=d.roomSettings?.markingMode==='manual_only';
    $('roomCode').textContent=isSimulation?'SIMULACIÓN':`PARTIDA ${d.roomCode}`;
    $('roomMode').textContent=`${d.game.mode} bolas · ${d.game.cards.length} cartones${Number(d.game.mode)===90?` · ${d.game.rules?.ambocabeza?'AmboCabeza · ':''}${Number(d.roomSettings?.linePrizeCount||1)} línea${Number(d.roomSettings?.linePrizeCount||1)===1?'':'s'}`:''} · ${manual?'SOLO MANUAL':'NORMAL'}`;
    $('joinInfo').innerHTML=isSimulation?`<b>SIMULACIÓN INTERNA</b><span>${d.players.length} jugadores IA.</span>`:`<b>INGRESO POR LINK PRIVADO</b><span>Agregá cada jugador, autorizá cuántos cartones puede elegir y mandale su enlace por WhatsApp.</span><span>No hay clave ni segundo login. El primer dispositivo que usa el link queda asociado a esa sesión.</span><span>La sala de espera tiene chat, emojis, stickers de La Gorda y minijuegos.</span>`;
    $('inviteTools')?.classList.toggle('hidden',isSimulation);
    const plan=d.startPlan||{};const canStart=isSimulation||Boolean(plan.canStartFromAdmin);$('startBtn').textContent=isSimulation?'INICIAR SIMULACIÓN':'INICIAR SORTEO';$('startBtn').disabled=!canStart;
    $('playerCount').textContent=isSimulation?`${d.players.length} IA`:`${d.players.length}`;$('waitingPlayers').innerHTML=this.playerRows(true);this.bindPlayerActions();
    const autoCount=Number(plan.autoAssignPlayers||0),connected=Number(plan.connectedEligiblePlayers||0),eligible=Number(plan.eligiblePlayers||0);
    $('waitingLeaderboard').innerHTML=isSimulation?`<h3>PRUEBA DE CARGA</h3><div class="summaryBox"><span>Probá sorteo, reclamos, chat, transmisión y visor.</span></div>`:`<h3>ESTADO DE LA SALA</h3><div class="summaryBox"><span><b>${connected} conectados · ${eligible} habilitados</b></span><span>${autoCount?`${autoCount} jugador${autoCount===1?'':'es'} sin selección recibirá${autoCount===1?'':'n'} automáticamente su cantidad autorizada al iniciar.`:'Quienes ya confirmaron una selección conservarán exactamente esos cartones.'}</span><span>${canStart?'Podés iniciar el sorteo.':'Se necesitan al menos 2 jugadores conectados y habilitados.'}</span></div>`;
  }
  playerRows(waiting=false){
    const d=this.state,max=Number(d.roomSettings?.maxCardsPerPlayer||4);
    return (d.players||[]).map(p=>{
      const ai=Boolean(p.virtual),selected=Boolean(p.selectionConfirmed),cardCount=selected?p.cardIds.length:Number(p.allowedCardCount||1),linkReady=Boolean(p.invitationUrl&&!p.invitationClaimed);
      const status=ai?'IA':p.connected?'EN LÍNEA':p.invitationClaimed?'INVITACIÓN USADA · DESCONECTADO':'LINK SIN USAR';
      const adjust=waiting&&!ai&&!selected?`<div class="playerAccessActions" style="margin-top:7px"><span class="muted">Hasta</span><button class="tiny" data-auth-dec="${p.id}">−</button><b>${Number(p.allowedCardCount||1)}</b><button class="tiny" data-auth-inc="${p.id}">+</button><span class="muted">cartones</span></div>`:'';
      return `<article class="playerRow"><div><b>${esc(p.name)}</b><small>${selected?`${cardCount} cartón${cardCount===1?'':'es'} elegidos`:`hasta ${cardCount} cartón${cardCount===1?'':'es'}`} · ${status} · ${p.markingModeChosen?(p.autoMark?'AUTO':'MANUAL'):'modo pendiente'}</small>${adjust}</div><div class="playerAccessActions"><button class="tiny" data-preview="${p.id}" title="Ver como celular">👁</button>${!ai&&linkReady?`<button class="tiny" data-copy-invite="${p.id}">COPIAR LINK</button><button class="tiny" data-wa-invite="${p.id}">WHATSAPP</button>`:''}${!ai&&!linkReady?`<button class="tiny" data-copy-direct="${p.id}">RECUPERAR ACCESO</button>`:''}${waiting&&!ai?`<button class="tiny" data-remove="${p.id}">QUITAR</button>`:''}${!waiting&&!ai?`<button class="tiny" data-mute="${p.id}">${d.chat?.mutedPlayerIds?.includes(p.id)?'HABILITAR CHAT':'BLOQUEAR CHAT'}</button>`:''}</div></article>`;
    }).join('')||'<div class="muted">Todavía no agregaste jugadores.</div>';
  }
  bindPlayerActions(){
    document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>confirm('¿Quitar a este jugador?')&&this.req('/api/admin/remove-player',{method:'POST',body:JSON.stringify({playerId:b.dataset.remove})}).then(d=>this.apply(d)).catch(e=>this.toast(e.message)));
    document.querySelectorAll('[data-mute]').forEach(b=>b.onclick=()=>this.chatAction(this.state.chat?.mutedPlayerIds?.includes(b.dataset.mute)?'unmute':'mute',{playerId:b.dataset.mute}));
    document.querySelectorAll('[data-copy-direct]').forEach(b=>b.onclick=()=>{const p=this.state.players.find(x=>x.id===b.dataset.copyDirect);if(p)this.copyDirectInvite(p)});
    document.querySelectorAll('[data-copy-invite]').forEach(b=>b.onclick=()=>{const p=this.state.players.find(x=>x.id===b.dataset.copyInvite);if(p)this.copyPlayerInviteLink(p)});
    document.querySelectorAll('[data-wa-invite]').forEach(b=>b.onclick=()=>{const p=this.state.players.find(x=>x.id===b.dataset.waInvite);if(p)this.copyPlayerWhatsapp(p)});
    document.querySelectorAll('[data-preview]').forEach(b=>b.onclick=()=>this.openMobilePreview(false,b.dataset.preview));
    document.querySelectorAll('[data-auth-dec]').forEach(b=>b.onclick=()=>this.adjustPlayerAuthorization(b.dataset.authDec,-1));
    document.querySelectorAll('[data-auth-inc]').forEach(b=>b.onclick=()=>this.adjustPlayerAuthorization(b.dataset.authInc,1));
  }
  async adjustPlayerAuthorization(playerId,delta=0){
    const p=this.state?.players?.find(x=>x.id===playerId);if(!p||p.selectionConfirmed)return;
    const max=Number(this.state?.roomSettings?.maxCardsPerPlayer||4),next=Math.max(1,Math.min(max,Number(p.allowedCardCount||1)+Number(delta||0)));
    try{this.apply(await this.req('/api/admin/player-approval',{method:'POST',body:JSON.stringify({playerId,allowedCardCount:next})}));}catch(e){this.toast(e.message)}
  }
  async invitePlayer(){
    const name=$('inviteName').value.trim(),allowed=Number($('inviteCards').value)||this.maxCardsPerPlayer;if(!name)return this.toast('Escribí el nombre del jugador.');
    try{$('invitePlayerBtn').disabled=true;$('inviteError').innerHTML='';const data=await this.req('/api/admin/invite-player',{method:'POST',body:JSON.stringify({name,allowedCardCount:allowed})});this.apply(data.state);$('inviteName').value='';this.toast(`${data.player.name}: link privado generado`);await this.copyText(data.player.inviteUrl,'Link privado copiado');}catch(e){$('inviteError').innerHTML=`<div class="errorBox">${esc(e.message)}</div>`}finally{$('invitePlayerBtn').disabled=false}
  }
  async inviteBulk(){
    const names=$('bulkNames').value.trim(),allowed=Number($('bulkCards').value)||this.maxCardsPerPlayer;if(!names)return this.toast('Pegá los nombres, uno por línea.');
    try{$('inviteBulkBtn').disabled=true;$('inviteError').innerHTML='';const data=await this.req('/api/admin/invite-players',{method:'POST',body:JSON.stringify({names,allowedCardCount:allowed})});this.apply(data.state);$('bulkNames').value='';this.toast(`${data.players.length} invitaciones generadas.`);}catch(e){$('inviteError').innerHTML=`<div class="errorBox">${esc(e.message)}</div>`}finally{$('inviteBulkBtn').disabled=false}
  }

  renderLive(ballChanged=false){const d=this.state,last=this.lastBallOf(d);this.renderCurrentBall(last,d.game.mode,ballChanged);$('drawCount').textContent=`${d.game.drawn.length} de ${d.game.mode} bolillas`;const recentHost=$('recentBalls');recentHost.className=`recent ${Number(d.game.mode)===75?'bingo75':''}`;recentHost.innerHTML=d.game.drawn.slice(-5).reverse().map(n=>this.recentBallTag(n,d.game.mode)).join('');$('liveState').textContent=d.status==='playing'?'JUGANDO':d.status==='paused'?'PAUSADO':d.status==='verifying'?'VERIFICANDO RECLAMO':d.status==='finalizing'?'CIERRE FINAL':'PREPARANDO';const autoResume=Boolean(d.status==='paused'&&d.claimAutoResume?.active);$('pauseBtn').textContent=d.status==='paused'?(autoResume?'REANUDAR AHORA':'REANUDAR'):'PAUSAR';$('pauseBtn').disabled=!['playing','paused'].includes(d.status);$('keepPausedBtn').classList.toggle('hidden',!autoResume);$('autoResumeNotice').classList.toggle('show',autoResume);this.updateAutoResumeCountdown();$('drawNowBtn').disabled=d.status!=='playing';const simulationFinish=Boolean(d.roomSettings?.adminSimulation||d.demo);$('finishBtn').disabled=d.status==='finalizing'||(!simulationFinish&&d.game.drawn.length<d.game.mode)||!['playing','paused','verifying','finalizing'].includes(d.status);$('finishBtn').textContent=d.status==='finalizing'?'CERRANDO…':simulationFinish?'FINALIZAR DEMO':'FINALIZAR';$('liveInterval').value=String(d.game.autoSeconds||6);$('connectedPill').textContent=`${d.players.filter(p=>p.connected).length} en línea`;$('cardsPill').textContent=`${d.preflight?.activeCards||0} cartones`;$('chatPill').textContent=`Chat ${d.chat?.locked?'pausado':'abierto'}`;$('liveTransmissionBtn').textContent='TRANSMISIÓN / TV';const finalInfo=d.status==='finalizing'?`<span><b>CIERRE OFICIAL:</b> extrayendo bolillas faltantes · ${d.game.drawn.length} de ${d.game.mode}</span><span>El acta se habilita automáticamente al completar la extracción.</span>`:'';$('liveSummary').innerHTML=`<span>Sala ${d.roomCode} · ${d.game.mode} bolas</span><span>Bolillero ${d.game.drawMode==='automatic'?'automático':'manual'} · intervalo ${d.game.autoSeconds}s</span><span>Premios confirmados: ${Object.values(d.prizeStatus||{}).filter(x=>x&&x.closed).length}</span>${finalInfo}`;$('onlinePlayers').innerHTML=this.playerRows(false);this.bindPlayerActions();this.renderChat()}
  renderChat(){
    const d=this.state,stickers=window.BingoEmojiStickers,messages=d.chat?.messages||[];$('chatLockBtn').textContent=d.chat?.locked?'REABRIR CHAT':'PAUSAR CHAT';const fresh=new Set(messages.filter(m=>!this.seenAdminChatIds.has(m.id)).map(m=>m.id));
    $('adminChatList').innerHTML=messages.map(m=>{const isSticker=Boolean(stickers?.isStickerMessage(m));const body=stickers?stickers.renderMessage(m,{animate:fresh.has(m.id)}):esc(m.text||'');return `<article class="chatMsg ${m.role==='admin'?'admin':''} ${isSticker?'stickerMessage':''}"><header><b>${esc(m.name)}</b><button class="tiny" data-delete="${m.id}">ELIMINAR</button></header><p>${body}</p>${m.playerId?`<div class="chatActions"><button class="tiny" data-chat-mute="${m.playerId}" data-message-id="${m.id}">BLOQUEAR Y OCULTAR</button></div>`:''}</article>`}).join('')||'<div class="muted">Todavía no hay mensajes.</div>';
    messages.forEach(m=>this.seenAdminChatIds.add(m.id));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>this.chatAction('delete',{messageId:b.dataset.delete}));document.querySelectorAll('[data-chat-mute]').forEach(b=>b.onclick=()=>this.chatAction('mute',{playerId:b.dataset.chatMute,messageId:b.dataset.messageId}))
  }
  renderClaim(){
    clearTimeout(this.claimTimer);const pending=(this.state?.claims||[]).filter(c=>c.status==='pending');
    if(!pending.length){$('claimOverlay').classList.remove('show');this.claimShown='';$('claimWindowText').textContent='';$('claimList').innerHTML='';return}
    if(this.currentClaimOpen!==false)$('claimOverlay').classList.add('show');const key=pending.map(c=>c.id).join(',');if(key!==this.claimShown){this.claimShown=key;this.currentClaimOpen=true;$('claimOverlay').classList.add('show')}
    const first=pending.slice().sort((a,b)=>(a.receivedSequence||0)-(b.receivedSequence||0))[0],autoMs=Number(this.state?.claimAutoVerifyMs||10000),receivedAt=new Date(first.receivedAt||first.createdAt||Date.now()).getTime(),left=Math.max(0,receivedAt+autoMs-Date.now());
    const auditLeft=Math.max(0,Number(this.state.claimWindow?.expiresAtMs||0)-Date.now());
    $('claimWindowText').innerHTML=`${auditLeft>0?`Esperando otras alertas · ${(auditLeft/1000).toFixed(1)} s · `:''}<b>verificación automática en ${Math.ceil(left/1000)} s</b>`;
    $('claimList').innerHTML=pending.sort((a,b)=>(a.receivedSequence||0)-(b.receivedSequence||0)).map((c,i)=>`<article class="claimItem ${c.officialValid?'valid':'invalid'}"><b>${i+1}. ${esc(c.prizeLabel||c.type)} · ${esc(c.playerName)} · Cartón ${esc(c.cardNumber)}</b><div>#${esc(c.receivedSequence||'—')} ${i?`· +${Math.max(0,Number(c.deltaFromFirstMs)||0)} ms`:''}</div><div>${c.officialValid?'<strong>VALIDACIÓN CORRECTA</strong>':'<strong>INVÁLIDO</strong>: no cumple el premio'}</div><div class="actions" style="margin-top:7px"><button class="btn primary" data-confirm="${c.id}" ${!c.officialValid||auditLeft>0?'disabled':''}>VERIFICAR AHORA</button><button class="btn secondary" data-reject="${c.id}" ${auditLeft>0?'disabled':''}>RECHAZAR</button></div></article>`).join('');
    document.querySelectorAll('[data-confirm]').forEach(b=>b.onclick=()=>this.resolve(b.dataset.confirm,'confirmed'));document.querySelectorAll('[data-reject]').forEach(b=>b.onclick=()=>this.resolve(b.dataset.reject,'rejected'));this.claimTimer=setTimeout(()=>this.renderClaim(),250)
  }
  renderDrawer(){if(!this.state?.active)return;document.querySelectorAll('[data-drawer]').forEach(b=>b.classList.toggle('active',b.dataset.drawer===this.drawerTab));const d=this.state;if(this.drawerTab==='numbers'){const nums=[...d.game.drawn].sort((a,b)=>a-b);$('drawerContent').innerHTML=`<h3>NÚMEROS SALIDOS · ${nums.length}</h3><div class="numberGrid">${nums.map(n=>`<span>${n}</span>`).join('')}</div>`}else if(this.drawerTab==='winners'){const wins=(d.claims||[]).filter(c=>c.status==='confirmed');$('drawerContent').innerHTML=`<h3>GANADORES</h3>${wins.map(c=>`<div class="summaryBox"><b>${esc(c.prizeLabel||c.type)}</b><span>${esc(c.playerName)} · Cartón ${esc(c.cardNumber)}</span><span>${esc(c.receivedAtDisplay||c.resolvedAt||'')}</span></div>`).join('')||'<span class="muted">Todavía no hay premios confirmados.</span>'}`}else{$('drawerContent').innerHTML=`<h3>EVENTOS</h3>${(d.eventLog||[]).slice(-80).reverse().map(e=>`<div class="summaryBox"><b>${esc(e.type)}</b><span>${new Date(e.at).toLocaleTimeString('es-AR')}</span></div>`).join('')}`}}
  renderFinished(){const d=this.state;$('finishedSummary').innerHTML=`<span>Sala ${d.roomCode}</span><span>${d.players.length} jugadores · ${d.preflight?.activeCards||0} cartones</span><span>${d.game.drawn.length} bolillas extraídas</span>`;$('downloadPdfBtn').href=`/api/results.pdf?sala=${encodeURIComponent(d.roomCode)}`;$('downloadCsvBtn').href='/api/admin/acta.csv'}
  async toggleJoin(){try{this.apply(await this.req('/api/admin/join-open',{method:'POST',body:JSON.stringify({open:!this.state.roomSettings.joinOpen})}))}catch(e){this.toast(e.message)}}
  async start(){
    const plan=this.state?.startPlan||{};
    const requested=this.state.players.reduce((sum,p)=>sum+(p.cardIds?.length||0),0);
    if(this.state.roomSettings?.adminSimulation){if(!confirm(`Iniciar ahora la simulación con ${this.state.players.length} IA y ${requested} cartones?`))return;return this.startConfirmed(true)}
    if(Number(plan.connectedEligiblePlayers||0)<2)return this.toast('Se necesitan al menos 2 jugadores conectados y habilitados.');
    const eligible=Number(plan.eligiblePlayers||0),auto=Number(plan.autoAssignPlayers||0),pendingPay=Number(plan.pendingPaymentPlayers||0),selected=Number(plan.selectedPlayers||0);
    const meta=`<b>${eligible} JUGADORES HABILITADOS</b><span>${selected} ya eligieron cartones · ${auto} recibirán cartones al azar al iniciar.</span>${pendingPay?`<span>${pendingPay} con pago pendiente quedarán fuera de esta ronda.</span>`:''}<span>Quien no haya elegido Manual/Auto comenzará en MANUAL y podrá cambiar después.</span>`;
    if(eligible>20){$('largeRoomStartMeta').innerHTML=meta;this.openModal('startCriterionModal');return}
    if(!confirm(`Iniciar sorteo con ${eligible} jugadores habilitados?\n${auto} recibirán cartones automáticamente.${pendingPay?`\n${pendingPay} con pago pendiente quedarán fuera.`:''}`))return;await this.startConfirmed()
  }
  async confirmLargeRoomStart(){this.closeModal('startCriterionModal');await this.startConfirmed()}
  async startConfirmed(force=false){try{this.apply(await this.req('/api/admin/start',{method:'POST',body:JSON.stringify({force:Boolean(force)})}))}catch(e){this.toast(e.message)}}
  async pauseResume(){try{const autoResume=Boolean(this.state.status==='paused'&&this.state.claimAutoResume?.active);this.apply(await this.req(this.state.status==='paused'?'/api/admin/resume':'/api/admin/pause',{method:'POST',body:this.state.status==='paused'?JSON.stringify({mode:this.state.game.drawMode,immediate:autoResume}):'{}'}))}catch(e){this.toast(e.message)}}
  async keepPaused(){try{this.apply(await this.req('/api/admin/cancel-claim-auto-resume',{method:'POST',body:'{}'}));this.toast('La partida queda pausada hasta que decidas reanudar.')}catch(e){this.toast(e.message)}}
  updateAutoResumeCountdown(){const box=$('autoResumeNotice'),text=$('autoResumeText');if(!box||!text)return;const info=this.state?.claimAutoResume,active=Boolean(this.state?.status==='paused'&&info?.active);box.classList.toggle('show',active);$('keepPausedBtn')?.classList.toggle('hidden',!active);if(!active)return;const remaining=Math.max(0,new Date(info.resumesAt||0).getTime()-Date.now()),seconds=Math.max(0,Math.ceil(remaining/1000));text.innerHTML=`Premio confirmado · <b>reanudando automáticamente en ${seconds}</b>`}
  async draw(){try{this.apply(await this.req('/api/admin/draw',{method:'POST',body:JSON.stringify({source:'manual'})}))}catch(e){this.toast(e.message)}}
  async updateInterval(){try{this.apply(await this.req('/api/admin/draw-settings',{method:'POST',body:JSON.stringify({autoSeconds:Number($('liveInterval').value)})}))}catch(e){this.toast(e.message)}}
  async resolve(claimId,resolution){try{await this.req('/api/admin/resolve',{method:'POST',body:JSON.stringify({claimId,resolution})});await this.refresh()}catch(e){this.toast(e.message)}}
  async finish(){const simulation=Boolean(this.state?.roomSettings?.adminSimulation||this.state?.demo);const question=simulation?'¿Finalizar esta demostración ahora? Se detendrá el bolillero, la IA y los reclamos pendientes.':'¿Finalizar la partida y generar el acta?';if(!confirm(question))return;try{this.apply(await this.req('/api/admin/finish',{method:'POST',body:JSON.stringify({forceSimulation:simulation})}))}catch(e){this.toast(e.message)}}
  async closeRoom(){if(!confirm('¿Cerrar esta sala?'))return;await this.req('/api/admin/close',{method:'POST',body:'{}'});await this.refresh()}
  async newRoom(){await this.req('/api/admin/new-room',{method:'POST',body:'{}'});await this.refresh()}
  async sendChat(){const text=$('adminChatInput').value.trim();if(!text)return;try{this.apply(await this.req('/api/admin/chat',{method:'POST',body:JSON.stringify({text})}));$('adminChatInput').value=''}catch(e){this.toast(e.message)}}
  async chatAction(action,extra={}){try{this.apply(await this.req('/api/admin/chat/moderate',{method:'POST',body:JSON.stringify({action,...extra})}))}catch(e){this.toast(e.message)}}
  setSide(tab){$('onlineTab').classList.toggle('active',tab==='online');$('chatTab').classList.toggle('active',tab==='chat');$('onlinePanel').classList.toggle('hidden',tab!=='online');$('chatPanel').classList.toggle('hidden',tab!=='chat')}
  toggleDrawer(force){const open=force??!$('drawer').classList.contains('show');$('drawer').classList.toggle('show',open);$('drawerToggle').classList.toggle('hidden',!this.state?.active);$('drawerToggle').textContent=open?'‹':'›'}
  async showPdf(){const room=encodeURIComponent(this.state.roomCode);const preview=`/api/results.pdf?sala=${room}&preview=1`;const download=`/api/results.pdf?sala=${room}`;$('pdfOpenTab').href=preview;$('pdfDownloadModal').href=download;$('actaPreview').innerHTML='<div class="actaBox">Preparando vista previa…</div>';this.openModal('pdfModal');try{this.renderActaPreview(await this.req('/api/admin/acta'))}catch(e){$('actaPreview').innerHTML=`<div class="errorBox">${esc(e.message)}</div>`}}
  actaTime(value){if(!value)return'—';try{return new Date(value).toLocaleString('es-AR',{dateStyle:'short',timeStyle:'medium'})}catch{return String(value)}}
  renderActaPreview(acta){const winners=acta.winners||[],alerts=acta.claimAlerts||[],participants=acta.participants||[],balls=acta.balls||[];const categories=Object.values(acta.categories||{});$('actaPreview').innerHTML=`<section class="actaHead"><h2>${acta.demo?'DEMOSTRACIÓN · SIN VALIDEZ OFICIAL':'LA GORDA - BINGO ONLINE'}</h2><div>Sala ${esc(acta.roomCode)} · Juego ${esc(acta.gameNumber)} · Bingo ${esc(acta.mode)}</div></section><div class="actaMeta"><span><b>INICIO</b>${esc(this.actaTime(acta.startedAt))}</span><span><b>FINALIZACIÓN</b>${esc(this.actaTime(acta.endedAt))}</span><span><b>JUGADORES</b>${Number(acta.totalPlayers)||0}</span><span><b>CARTONES ACTIVOS</b>${Number(acta.activeCards)||0}</span><span><b>SORTEO</b>${acta.integrity?.verified?'✓ VERIFICADO':'—'}</span></div>${acta.integrity?.commitment?`<div class="actaBox"><b>Sello SHA-256:</b> ${esc(acta.integrity.commitment)}${acta.integrity.verified?'<br><b>El orden final coincide con el sello generado antes de comenzar.</b>':''}</div>`:''}<h3>RESULTADOS</h3><div class="actaWinners">${categories.map(cat=>`<div class="actaWinner"><b>${esc(cat.label)}</b><div>${cat.enabled===false?'No sorteada':cat.winners?.length?cat.winners.map(w=>`${esc(w.playerName)} · Cartón ${esc(w.cardNumber)}`).join('<br>'):'Sin ganador confirmado'}</div></div>`).join('')}</div><h3>BOLILLAS EXTRAÍDAS · ${balls.length}</h3><div class="actaBalls">${balls.map(ball=>`<div class="actaBall">${esc(ball.number)}<small>#${esc(ball.order)} · ${esc(new Date(ball.at).toLocaleTimeString('es-AR',{hour:'2-digit',minute:'2-digit',second:'2-digit'}))}</small></div>`).join('')}</div><h3>GANADORES CONFIRMADOS · ${winners.length}</h3><div class="actaRows">${winners.length?winners.map(w=>`<div class="actaRow"><b>${esc(w.prizeLabel)}</b><span>${esc(w.playerName)} · Cartón ${esc(w.cardNumber)}</span><span>${esc(this.actaTime(w.claimedAt))}</span><span>Bolilla ${esc(w.ballNumber??'—')}</span></div>`).join(''):'<div class="actaBox">Sin ganadores confirmados.</div>'}</div><h3>AUDITORÍA DE RECLAMOS · ${alerts.length}</h3><div class="actaRows">${alerts.length?alerts.map(a=>`<div class="actaRow"><b>#${esc(a.sequence||'—')}</b><span>${esc(a.prizeLabel||a.type)} · ${esc(a.playerName)} · Cartón ${esc(a.cardNumber)}</span><span>${a.officialValid?'VÁLIDO':'INVÁLIDO'} · ${esc(this.claimAuditLabel(a))}</span><span>${Number(a.deltaMs)||0} ms</span></div>`).join(''):'<div class="actaBox">Sin alertas registradas.</div>'}</div><h3>PARTICIPANTES · ${participants.length}</h3><div class="actaParticipants">${participants.map(p=>`<span class="actaParticipant"><b>${esc(p.name)}</b> · ${esc((p.cardNumbers||[]).join(' · ')||'sin cartón')}</span>`).join('')}</div>`}
  roomJoinUrl(){return ''}
  copyRoomLink(){this.toast('El acceso se genera jugador por jugador.')}
  copyRoomInvite(){this.toast('Usá el botón WHATSAPP de cada jugador.')}
  async copyPlayerInviteLink(player){if(!player?.invitationUrl)return this.toast('Ese jugador ya usó su invitación.');return this.copyText(player.invitationUrl,`Link privado de ${player.name} copiado`)}
  async copyPlayerWhatsapp(player){if(!player?.invitationUrl)return this.toast('Ese jugador ya usó su invitación.');const d=this.state,lines=Number(d?.game?.mode)===90?` · ${Number(d?.roomSettings?.linePrizeCount||1)} línea${Number(d?.roomSettings?.linePrizeCount||1)===1?'':'s'}`:'';const text=`🎉 ¡Hola ${player.name}! Tu acceso a Bingo de la Gorda ya está listo.\n🎱 Bingo de ${d.game.mode} bolas${lines}\n🎟 Podés elegir hasta ${Number(player.allowedCardCount||1)} cartón${Number(player.allowedCardCount||1)===1?'':'es'}.\n\n👉 Entrá directamente desde tu link privado:\n${player.invitationUrl}\n\nEste enlace es personal. No lo compartas.`;try{window.open(`https://wa.me/?text=${encodeURIComponent(text)}`,'_blank','noopener');this.toast('Abriendo WhatsApp…');}catch{}try{await navigator.clipboard.writeText(text)}catch{}return text}
  async copyDirectInvite(player){if(!player?.id)return;try{const data=await this.req('/api/admin/player-recovery-link',{method:'POST',body:JSON.stringify({playerId:player.id})});const text=`🔐 Recuperación privada para ${data.playerName}. Funciona una sola vez y vence en 15 minutos:\n${data.url}`;await this.copyText(text,'Link de recuperación copiado')}catch(e){this.toast(e.message)}}

async copyText(text,label='Copiado'){try{await navigator.clipboard.writeText(String(text||''));this.toast(label)}catch{prompt('Copiá este texto:',text)}}
openMobilePreview(aiOnly=false,playerId=''){if(!this.state?.active)return this.toast('Primero creá una sala.');const select=$('mobilePreviewPlayer');const previous=playerId||select.value;let players=(this.state.players||[]);if(aiOnly)players=players.filter(p=>p.virtual);select.innerHTML=players.map(p=>`<option value="${esc(p.id)}">${esc(p.name||p.slotLabel)}${p.virtual?' · IA':' · jugador'}</option>`).join('');if([...select.options].some(o=>o.value===previous))select.value=previous;else if(select.options.length)select.selectedIndex=0;$('mobilePreviewIframe').src='about:blank';$('mobilePreviewNote').textContent=players.length?'Vista en vivo de solo lectura. No marca, no reclama y no modifica la partida.':'Todavía no hay un jugador disponible para mostrar.';this.applyMobilePreviewSize();this.openModal('mobilePreviewModal');if(players.length)queueMicrotask(()=>this.loadMobilePreview())}
async loadMobilePreview(){const id=$('mobilePreviewPlayer').value;if(!id)return this.toast('No hay jugadores para previsualizar.');try{const data=await this.req('/api/admin/player-view-session',{method:'POST',body:JSON.stringify({playerId:id})});$('mobilePreviewIframe').src=data.url;$('mobilePreviewNote').textContent=`Vista de ${data.playerName}${data.virtual?' · IA':''} · simulación en vivo de solo lectura. No modifica la partida.`}catch(e){this.toast(e.message)}}
applyMobilePreviewSize(){const frame=$('mobilePreviewFrame'),size=$('mobilePreviewSize').value;frame.classList.remove('small','tablet');if(size==='small')frame.classList.add('small');if(size==='tablet')frame.classList.add('tablet')}
rotateMobilePreview(){$('mobilePreviewFrame').classList.toggle('landscape')}
showJoinQr(){const url=this.roomJoinUrl();if(!url)return this.toast('Primero creá la sala.');$('joinQrImage').src=`https://api.qrserver.com/v1/create-qr-code/?size=320x320&margin=10&data=${encodeURIComponent(url)}`;$('joinQrText').textContent=url;this.openModal('qrModal')}
  openTransmission(){if(this.state?.broadcastUrl)window.open(this.state.broadcastUrl,'_blank','noopener');else this.toast('Primero creá la sala.')}
  openModal(id){$(id).classList.add('show')}closeModal(id){$(id).classList.remove('show')}
  lastBallOf(data){const drawn=data?.game?.drawn;return Array.isArray(drawn)&&drawn.length?drawn[drawn.length-1]:(data?.game?.lastBall??null)}
  ballLabel(n,mode){if(Number(mode)!==75)return String(n);return `${'BINGO'[Math.min(4,Math.floor((n-1)/15))]} · ${n}`}
  claimAuditLabel(a){if(a?.resolutionReason==='automatic_verified')return 'GANADOR · VERIFICACIÓN AUTOMÁTICA';if(a?.resolutionReason==='automatic_rejected')return 'RECHAZADO · VERIFICACIÓN AUTOMÁTICA';if(a?.status==='confirmed')return 'GANADOR';if(a?.resolutionReason==='valid_but_received_later')return 'VÁLIDA POSTERIOR';if(a?.resolutionReason==='rejected_by_admin')return a?.officialValid?'VÁLIDO · RECHAZADO POR ADMIN':'RECHAZADO POR ADMIN';if(a?.resolutionReason==='invalid_card')return 'INVÁLIDO';return a?.resolutionReason||a?.status||'—'}
  ballInfo75(number){const letter=number<=15?'B':number<=30?'I':number<=45?'N':number<=60?'G':'O';return {letter,className:`bingo-col-${letter.toLowerCase()}`}}
  currentBallMarkup(number,mode){if(number==null)return '—';if(Number(mode)!==75)return `<span class="ballNumber">${number}</span>`;const info=this.ballInfo75(number);return `<span class="ballInner"><span class="ballLetter">${info.letter}</span><span class="ballNumber">${number}</span></span>`}
  recentBallTag(number,mode){if(Number(mode)!==75)return `<span>${number}</span>`;const info=this.ballInfo75(number);return `<span class="${info.className}"><span class="tagLetter">${info.letter}</span>${number}</span>`}
  renderCurrentBall(number,mode,animate=false){const el=$('currentBall');el.className='ball';if(number==null){el.textContent='—';return}if(Number(mode)===75)el.classList.add(this.ballInfo75(number).className);el.innerHTML=this.currentBallMarkup(number,mode);if(animate&&window.matchMedia&&!window.matchMedia('(prefers-reduced-motion: reduce)').matches){el.classList.remove('ball-animate');void el.offsetWidth;el.classList.add('ball-animate');setTimeout(()=>el.classList.remove('ball-animate'),750)}}
  testVoice(){const text='Hola, soy Vero. Bolilla número cuarenta y dos. Mucha suerte para todos.';if(!speechSynthesis)return this.toast('Este navegador no permite probar voces.');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);const voices=speechSynthesis.getVoices();const spanish=voices.filter(v=>/^es([-_]|$)/i.test(v.lang)||/spanish|español|espanol/i.test(v.name));u.voice=spanish.find(v=>/female|femen|mujer|sofia|paulina|paloma|ximena|laura|lucia|mar[ií]a|camila|valentina|monica|m[oó]nica|sabina/i.test(v.name))||spanish[0]||voices[0]||null;u.lang=u.voice?.lang||'es-AR';u.rate=1.02;u.pitch=1.16;speechSynthesis.speak(u)}
  toggleTheme(){const day=document.documentElement.dataset.theme==='day';document.documentElement.dataset.theme=day?'night':'day';localStorage.setItem('bingoAdminTheme',day?'night':'day');$('themeBtn').textContent=day?'☾':'☀'}applyTheme(){const theme=localStorage.getItem('bingoAdminTheme')==='day'?'day':'night';document.documentElement.dataset.theme=theme;$('themeBtn').textContent=theme==='day'?'☀':'☾'}
  async fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{}}
  async copy(text){return this.copyText(text,'Enlace copiado')}
  toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>$('toast').classList.remove('show'),4500)}
  beep(){try{const A=window.AudioContext||window.webkitAudioContext;if(!A)return;const c=new A(),o=c.createOscillator(),g=c.createGain();o.frequency.value=620;g.gain.value=.04;o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+.12)}catch{}}
}
window.addEventListener('DOMContentLoaded',()=>new AdminApp().init());
})();
