'use strict';
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const storage={visitor:'laGordaCommunityVisitor',name:'laGordaCommunityName',game:'laGordaCommunityGame',best:'laGordaCommunityBest'};
const safeStorage={
  get(key){try{return localStorage.getItem(key)||''}catch{return ''}},
  set(key,value){try{localStorage.setItem(key,String(value))}catch{} }
};
function randomVisitor(){const id=(globalThis.crypto?.randomUUID?.()||`guest-${Date.now()}-${Math.random().toString(16).slice(2)}`);return String(id).replace(/[^a-zA-Z0-9_-]/g,'').slice(0,80)}
const visitorId=safeStorage.get(storage.visitor)||randomVisitor(); safeStorage.set(storage.visitor,visitorId);
let name=safeStorage.get(storage.name).trim().slice(0,20);
let state={messages:[],leaderboards:{red_black:[],higher_lower:[]},whatsapp:{},activeGame:null,chatEnabled:true,onlineCount:0,maxLength:180};
let nameResolve=null,pollTimer=null,toastTimer=null;
const pickerMode={desktop:'',drawer:''};
const seenMessageIds=new Set();
const stickerSendTimes=[];
const bestByType=(()=>{try{return JSON.parse(safeStorage.get(storage.best)||'{}')}catch{return {}}})();
const savedGame=safeStorage.get(storage.game);
const mini={type:['red_black','higher_lower'].includes(savedGame)?savedGame:'red_black',score:0,best:0,current:null,ended:false,busy:false,message:''};

async function api(url,opt={}){const r=await fetch(url,{...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'No se pudo completar la acción.');return d}
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2300)}
function validName(value){const n=String(value||'').trim().replace(/\s+/g,' ').slice(0,20);return n.length>=2&&!/^(la\s*gorda|administraci[oó]n|admin|administrador(?:a)?|sistema|moderador(?:a)?|staff|oficial)$/i.test(n)}
function focusNameInput(){const input=$('nameInput');if(!input)return;input.disabled=false;input.readOnly=false;try{input.focus({preventScroll:true})}catch{input.focus()}try{const end=input.value.length;input.setSelectionRange(end,end)}catch{}}
function askName(){
  if(validName(name)) return Promise.resolve(true);
  if(nameResolve) return Promise.resolve(false);
  return new Promise(resolve=>{
    nameResolve=resolve;
    const input=$('nameInput');
    input.disabled=false;input.readOnly=false;input.value=name;$('nameError').textContent='';
    $('nameOverlay').classList.remove('hidden');
    // El primer focus es síncrono para que iOS/Android permitan abrir el teclado desde el toque del usuario.
    focusNameInput();
    requestAnimationFrame(()=>focusNameInput());
  });
}
function closeName(result=false){$('nameOverlay').classList.add('hidden');const resolve=nameResolve;nameResolve=null;if(resolve)resolve(result)}
function saveName(){if(validName(name)){closeName(true);return true}const input=$('nameInput');const n=String(input.value||'').trim().replace(/\s+/g,' ').slice(0,20);if(!validName(n)){$('nameError').textContent='Usá entre 2 y 20 caracteres y evitá nombres oficiales como LA GORDA o ADMIN.';focusNameInput();return false}name=n;safeStorage.set(storage.name,name);renderIdentity();closeName(true);toast(`Hola, ${name}`);return true}
async function ensureName(){if(validName(name))return true;return await askName()}
function renderIdentity(){const locked=validName(name),button=$('identityBtn');button.textContent=locked?`👤 ${name}`:'ELEGIR NOMBRE';button.disabled=locked;button.classList.toggle('locked',locked);button.classList.toggle('needsName',!locked);button.title=locked?'Nombre guardado en este dispositivo':'Elegí tu nombre para participar';$('previewIdentity').textContent=locked?`Estás como ${name} · nombre guardado`:'Entrá con tu nombre';$('drawerIdentity').textContent=locked?`Estás como ${name} · nombre guardado en este dispositivo`:'Elegí un nombre para participar';$('miniName').textContent=locked?`Jugás como ${name}`:''}
function timeLabel(iso){try{return new Date(iso).toLocaleTimeString('es-AR',{hour:'2-digit',minute:'2-digit'})}catch{return ''}}
function stickers(){return window.BingoEmojiStickers||null}
function isStickerMessage(m){return Boolean(stickers()?.isStickerMessage(m))}
function messageBody(m,animate=false){const api=stickers();return api?api.renderMessage(m,{animate}):esc(m?.text||'')}
function previewBody(m){if(isStickerMessage(m)){const info=stickers()?.get(m.stickerId);return `✦ ${info?.label||'Sticker'}`}return String(m?.text||'')}
function messageHtml(m){const own=m.visitorId===visitorId,official=m.role==='official',sticker=isStickerMessage(m),fresh=sticker&&!seenMessageIds.has(m.id),canReport=!own&&!official;return `<article class="msg ${own?'me':''} ${official?'official':''} ${sticker?'stickerMessage':''}" data-message-id="${esc(m.id)}"><div class="msgHead"><b>${official?'✓ ':''}${esc(m.name||'Invitado')}</b><span class="msgMeta"><time>${esc(timeLabel(m.createdAt))}</time>${canReport?`<button type="button" class="reportFlag ${m.reportedByMe?'reported':''}" data-report-message="${esc(m.id)}" title="${m.reportedByMe?'Mensaje reportado':'Reportar mensaje'}" aria-label="${m.reportedByMe?'Mensaje reportado':'Reportar mensaje'}" ${m.reportedByMe?'disabled':''}>⚑</button>`:''}</span></div><p>${messageBody(m,fresh)}</p></article>`}
function renderMessages(){
  const messages=state.messages||[];
  const html=messages.map(messageHtml).join('')||'<div class="empty">Todavía no hay mensajes. Podés ser el primero.</div>';
  for(const id of ['messages','drawerMessages']){const host=$(id),nearBottom=host.scrollHeight-host.scrollTop-host.clientHeight<90;host.innerHTML=html;if(nearBottom||!host.dataset.rendered)host.scrollTop=host.scrollHeight;host.dataset.rendered='1';host.onclick=e=>{const flag=e.target.closest?.('[data-report-message]');if(flag){e.preventDefault();e.stopPropagation();reportMessage(flag.dataset.reportMessage);return}stickers()?.replay(e.target)}}
  messages.forEach(m=>seenMessageIds.add(m.id));
  const last=messages.slice(-2);$('previewMessages').innerHTML=last.length?last.map(m=>`<div class="previewLine"><b>${esc(m.name)}:</b> ${esc(previewBody(m))}</div>`).join(''):'<div class="previewLine">Todavía no hay mensajes.</div>';
}
function statusLabel(status){return ({waiting:'ESPERANDO JUGADORES',starting:'COMENZANDO',playing:'PARTIDA EN VIVO',verifying:'VERIFICANDO PREMIO',paused:'PARTIDA PAUSADA',resuming:'REANUDANDO',finalizing:'ÚLTIMAS BOLILLAS'})[status]||'PARTIDA ACTIVA'}
function renderLive(){const game=state.activeGame;if(!game){$('liveContent').innerHTML=`<div class="eyebrow"><span class="liveDot" style="background:#7d7288;box-shadow:none"></span> AHORA MISMO</div><h1>La comunidad sigue abierta</h1><p>No hay una partida activa. Podés jugar a los minijuegos o quedarte charlando.</p><div class="actions"><button class="btn primary" data-jump-games>JUGAR MINIJUEGOS</button></div>`;$('[data-jump-games]')?.addEventListener('click',()=>openGame(mini.type));return}const actions=[];if(game.canJoin&&game.joinUrl)actions.push(`<a class="btn primary" href="${esc(game.joinUrl)}">JUGAR AHORA</a>`);else if(state.whatsapp?.contactUrl)actions.push(`<a class="btn primary" target="_blank" rel="noopener" href="${esc(state.whatsapp.contactUrl)}">PEDIR ACCESO</a>`);if(game.transmissionEnabled&&game.transmissionUrl)actions.push(`<a class="btn secondary" href="${esc(game.transmissionUrl)}">VER TRANSMISIÓN</a>`);$('liveContent').innerHTML=`<div class="eyebrow"><span class="liveDot"></span> ${esc(statusLabel(game.status))}</div><h1>Sala ${esc(game.roomCode)}</h1><p>${game.mode} bolillas · ${game.playerCount} participante${game.playerCount===1?'':'s'}</p><div class="liveMeta"><span class="pill">${game.mode} BOLAS</span><span class="pill">${game.roomType==='test'?'SALA DE PRUEBA':'SALA OFICIAL'}</span></div><div class="actions">${actions.join('')||'<button class="btn ghost" disabled>ACCESO PRIVADO</button>'}</div>`}
function renderWhatsapp(){const group=state.whatsapp?.groupUrl||'',contact=state.whatsapp?.contactUrl||'';$('groupBtn').href=group||'#';$('contactBtn').href=contact||'#';$('groupBtn').setAttribute('aria-disabled',group?'false':'true');$('contactBtn').setAttribute('aria-disabled',contact?'false':'true');$('groupBtn').style.opacity=group?'1':'.45';$('contactBtn').style.opacity=contact?'1':'.45';$('groupBtn').onclick=e=>{if(!group){e.preventDefault();toast('El enlace del grupo todavía no está configurado.')}};$('contactBtn').onclick=e=>{if(!contact){e.preventDefault();toast('El WhatsApp de contacto todavía no está configurado.')}};$('whatsappHint').textContent=state.whatsapp?.number?`Contacto: ${state.whatsapp.number}`:'Grupo, novedades y contacto directo.'}
function renderState(){renderIdentity();renderMessages();renderLive();renderWhatsapp();$('onlineText').textContent=`${Math.max(1,Number(state.onlineCount)||1)} en la comunidad`;for(const id of ['chatInput','drawerInput','sendBtn','drawerSendBtn','emojiBtn','stickerBtn','drawerEmojiBtn','drawerStickerBtn'])$(id).disabled=state.chatEnabled===false;$('chatInput').placeholder=state.chatEnabled===false?'Chat pausado por La Gorda':'Escribí un mensaje…';$('drawerInput').placeholder=$('chatInput').placeholder;if(state.chatEnabled===false){closePicker('desktop');closePicker('drawer')}renderLeaderboard()}
async function refresh(silent=true){try{state=await api(`/api/community/state?visitorId=${encodeURIComponent(visitorId)}`);renderState()}catch(e){if(!silent)toast(e.message)}}
async function reportMessage(messageId){if(!messageId)return;if(!confirm('¿Seguro que querés reportar este mensaje?'))return;try{const d=await api('/api/community/report',{method:'POST',body:JSON.stringify({visitorId,messageId})});if(d.state)state=d.state;renderState();toast(d.alreadyReported?'Este mensaje ya estaba reportado.':'Reporte enviado para revisión.')}catch(e){toast(e.message)}}
async function sendFrom(input){const text=input.value.trim();if(!text)return;if(!(await ensureName()))return;try{input.disabled=true;const d=await api('/api/community/chat',{method:'POST',body:JSON.stringify({visitorId,name,text})});input.value='';if(d.state)state=d.state;closePicker(input.id==='drawerInput'?'drawer':'desktop');renderState()}catch(e){toast(e.message)}finally{input.disabled=state.chatEnabled===false;try{input.focus({preventScroll:true})}catch{input.focus()}}}
function pickerIds(scope){return scope==='drawer'?{host:'drawerPicker',emoji:'drawerEmojiBtn',sticker:'drawerStickerBtn',input:'drawerInput'}:{host:'desktopPicker',emoji:'emojiBtn',sticker:'stickerBtn',input:'chatInput'}}
function closePicker(scope){const ids=pickerIds(scope),host=$(ids.host);pickerMode[scope]='';host.className='chatPicker';host.innerHTML='';$(ids.emoji).classList.remove('active');$(ids.sticker).classList.remove('active')}
function insertEmoji(scope,emoji){const ids=pickerIds(scope),input=$(ids.input),allowed=stickers()?.commonEmojis||[];if(!allowed.includes(emoji)||input.disabled)return;const selected=[...input.value].filter(char=>allowed.includes(char)).length;if(selected>=4){toast('Podés agregar hasta 4 emojis del menú por mensaje.');return}const start=input.selectionStart??input.value.length,end=input.selectionEnd??start;input.value=`${input.value.slice(0,start)}${emoji}${input.value.slice(end)}`.slice(0,Number(state.maxLength)||180);const next=Math.min(input.value.length,start+emoji.length);closePicker(scope);try{input.focus({preventScroll:true});input.setSelectionRange(next,next)}catch{input.focus()}}
function renderPicker(scope,type){const ids=pickerIds(scope),host=$(ids.host),api=stickers();if(!api)return;if(pickerMode[scope]===type){closePicker(scope);return}pickerMode[scope]=type;$(ids.emoji).classList.toggle('active',type==='emoji');$(ids.sticker).classList.toggle('active',type==='sticker');if(type==='emoji'){host.className='chatPicker emojis show';host.innerHTML=api.commonEmojis.map(emoji=>`<button type="button" data-community-emoji="${emoji}" aria-label="Emoji ${emoji}">${emoji}</button>`).join('');host.querySelectorAll('[data-community-emoji]').forEach(btn=>btn.onclick=()=>insertEmoji(scope,btn.dataset.communityEmoji));return}host.className='chatPicker stickers show';host.innerHTML=`<div class="chatPickerHint">Los stickers se envían solos con un toque, igual que en el chat del bingo.</div>${api.stickers.map(item=>`<button class="premiumStickerButton" type="button" data-community-sticker="${esc(item.id)}" aria-label="Enviar sticker ${esc(item.label)}">${api.sticker(item.id,{className:'premiumStickerMenuIcon',replay:false})}</button>`).join('')}`;host.querySelectorAll('[data-community-sticker]').forEach(btn=>btn.onclick=()=>{const preview=btn.querySelector('.premiumSticker');if(preview){preview.classList.remove('preview');void preview.offsetWidth;preview.classList.add('preview')}sendSticker(scope,btn.dataset.communitySticker)})}
async function sendSticker(scope,stickerId){if(state.chatEnabled===false)return;if(!stickers()?.get(stickerId))return;if(!(await ensureName()))return;const now=Date.now();while(stickerSendTimes.length&&now-stickerSendTimes[0]>=10000)stickerSendTimes.shift();const last=stickerSendTimes.at(-1)||0;if(now-last<1200||stickerSendTimes.length>=4){toast('Esperá un momento antes de enviar otro sticker.');return}stickerSendTimes.push(now);try{const d=await api('/api/community/chat',{method:'POST',body:JSON.stringify({visitorId,name,stickerId})});if(d.state)state=d.state;closePicker(scope);renderState()}catch(e){stickerSendTimes.pop();toast(e.message)}}
function openChat(){ensureName().then(ok=>{if(!ok)return;$('chatDrawer').classList.remove('hidden');renderMessages();setTimeout(()=>{try{$('drawerInput').focus({preventScroll:true})}catch{$('drawerInput').focus()}},40)})}
function closeChat(){closePicker('drawer');$('chatDrawer').classList.add('hidden')}
function randomCard(){const suits=[{symbol:'♥',color:'red',face:'corazon'},{symbol:'♦',color:'red',face:'diamante'},{symbol:'♠',color:'black',face:'pica'},{symbol:'♣',color:'black',face:'trebol'}],suit=suits[Math.floor(Math.random()*suits.length)],value=1+Math.floor(Math.random()*13);return {...suit,value,rank:value===1?'A':value===11?'J':value===12?'Q':value===13?'K':String(value)}}
function showCard(card,hidden=false){const host=$('playingCard');if(hidden||!card){host.className='playingCard back';host.style.backgroundImage='';host.innerHTML='';return}host.className='playingCard';host.style.backgroundImage=`url('/assets/cards/${card.face}.webp')`;host.innerHTML=`<div class="cardIndex top ${card.color}">${esc(card.rank)}<small>${card.symbol}</small></div><div class="cardIndex bottom ${card.color}">${esc(card.rank)}<small>${card.symbol}</small></div>`}
function gameTitle(type){return type==='red_black'?'ROJO O NEGRO':'MAYOR O MENOR'}
function resetMini(keepType=true){mini.score=0;mini.current=null;mini.ended=false;mini.busy=false;mini.message='';mini.best=Number(bestByType[mini.type])||0;if(!keepType)mini.type='red_black'}
function setGame(type){if(!['red_black','higher_lower'].includes(type))type='red_black';mini.type=type;safeStorage.set(storage.game,type);resetMini();if(type==='higher_lower')mini.current=randomCard();renderGame()}
function renderGame(){const type=mini.type;document.querySelectorAll('[data-game-tab]').forEach(b=>b.classList.toggle('active',b.dataset.gameTab===type));$('gameTitle').textContent=gameTitle(type);$('gameHint').textContent=type==='red_black'?'Elegí el color de la próxima carta. Cada acierto suma uno a tu racha.':'Mirá la carta actual y elegí si la próxima será mayor o menor. Los empates mantienen la racha.';$('gameScore').textContent=mini.score;$('gameBest').textContent=Math.max(Number(bestByType[type])||0,mini.best||0);if(type==='higher_lower'&&!mini.current&&!mini.ended)mini.current=randomCard();showCard(mini.current,type==='red_black'&&!mini.current);$('gameResult').textContent=mini.message||(type==='red_black'?'Elegí rojo o negro.':`Carta actual: ${mini.current.rank}${mini.current.symbol}. ¿La próxima será mayor o menor?`);$('gameChoices').innerHTML=type==='red_black'?'<button class="redChoice" data-choice="red">ROJO</button><button class="blackChoice" data-choice="black">NEGRO</button>':'<button class="higherChoice" data-choice="higher">MAYOR</button><button class="lowerChoice" data-choice="lower">MENOR</button>';$('gameChoices').classList.toggle('hidden',mini.ended);$('gameRestart').classList.toggle('hidden',!mini.ended);$('gameChoices').querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>playMini(b.dataset.choice));renderLeaderboard()}
function renderLeaderboard(){if(!$('leaderboard'))return;const board=state.leaderboards?.[mini.type]||[];$('leaderboard').innerHTML=`<b>Mejores rachas de la comunidad:</b><br>${board.length?board.slice(0,5).map((x,i)=>`${i+1}. ${esc(x.name)} · ${Number(x.bestScore)||0}`).join(' &nbsp;·&nbsp; '):'Todavía no hay puntajes.'}`}
async function submitScore(score){if(!validName(name)||score<=0)return;try{state=await api('/api/community/score',{method:'POST',body:JSON.stringify({visitorId,name,gameType:mini.type,score})});renderLeaderboard()}catch{}}
async function playMini(choice){if(mini.ended||mini.busy)return;mini.busy=true;const next=randomCard();let correct=false,tie=false;if(mini.type==='red_black')correct=choice===next.color;else{const current=mini.current||randomCard();mini.current=current;tie=next.value===current.value;correct=tie||(choice==='higher'?next.value>current.value:next.value<current.value)}showCard(next);if(tie){mini.current=next;mini.message=`Empate: salió ${next.rank}${next.symbol}. La racha sigue igual.`;mini.busy=false;renderGame();return}if(correct){mini.score++;mini.best=Math.max(mini.best,mini.score);bestByType[mini.type]=Math.max(Number(bestByType[mini.type])||0,mini.best);safeStorage.set(storage.best,JSON.stringify(bestByType));mini.current=next;mini.message=mini.type==='red_black'?`¡Correcto! Salió ${next.rank}${next.symbol}. Elegí otra vez.`:`¡Correcto! Salió ${next.rank}${next.symbol}. ¿Mayor o menor?`;mini.busy=false;renderGame();submitScore(mini.best);return}mini.ended=true;mini.current=next;mini.message=`Te equivocaste: salió ${next.rank}${next.symbol}. Racha final: ${mini.score}.`;mini.busy=false;bestByType[mini.type]=Math.max(Number(bestByType[mini.type])||0,mini.score);safeStorage.set(storage.best,JSON.stringify(bestByType));renderGame();submitScore(mini.score)}
async function openGame(type){$('gameOverlay').classList.remove('hidden');setGame(type||mini.type)}
function closeGame(){$('gameOverlay').classList.add('hidden')}
function bind(){
  $('nameForm').addEventListener('submit',e=>{e.preventDefault();saveName()});
  $('cancelNameBtn').onclick=()=>closeName(false);
  $('nameInput').addEventListener('pointerdown',()=>setTimeout(focusNameInput,0));
  $('nameInput').addEventListener('touchend',()=>setTimeout(focusNameInput,0),{passive:true});
  $('identityBtn').onclick=()=>{if(!validName(name))askName()};
  $('sendBtn').onclick=()=>sendFrom($('chatInput'));$('chatInput').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();sendFrom($('chatInput'))}};
  $('drawerSendBtn').onclick=()=>sendFrom($('drawerInput'));$('drawerInput').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();sendFrom($('drawerInput'))}};
  $('emojiBtn').onclick=()=>renderPicker('desktop','emoji');$('stickerBtn').onclick=()=>renderPicker('desktop','sticker');$('drawerEmojiBtn').onclick=()=>renderPicker('drawer','emoji');$('drawerStickerBtn').onclick=()=>renderPicker('drawer','sticker');
  $('openChatBtn').onclick=openChat;$('closeChatBtn').onclick=closeChat;
  document.querySelectorAll('[data-open-game]').forEach(el=>el.onclick=()=>openGame(el.dataset.openGame));$('closeGameBtn').onclick=closeGame;document.querySelectorAll('[data-game-tab]').forEach(el=>el.onclick=()=>setGame(el.dataset.gameTab));$('gameRestart').onclick=()=>{resetMini();if(mini.type==='higher_lower')mini.current=randomCard();renderGame()};
  document.querySelectorAll('[data-nav]').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('[data-nav]').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const n=btn.dataset.nav;if(n==='home')scrollTo({top:0,behavior:'smooth'});if(n==='games')$('gamesSection').scrollIntoView({behavior:'smooth',block:'center'});if(n==='chat')openChat();if(n==='whatsapp')$('groupBtn').scrollIntoView({behavior:'smooth',block:'center'})});
  document.addEventListener('pointerdown',e=>{for(const scope of ['desktop','drawer']){const ids=pickerIds(scope),host=$(ids.host);if(!pickerMode[scope])continue;if(host.contains(e.target)||$(ids.emoji).contains(e.target)||$(ids.sticker).contains(e.target))continue;closePicker(scope)}});
  document.addEventListener('keydown',e=>{if(e.key==='Escape'){closePicker('desktop');closePicker('drawer');closeChat();closeGame();if(!$('nameOverlay').classList.contains('hidden'))closeName(false)}});
}
async function init(){bind();renderIdentity();await refresh(false);pollTimer=setInterval(()=>refresh(true),4000);window.addEventListener('focus',()=>refresh(true));}
window.addEventListener('DOMContentLoaded',init);
