'use strict';
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const storage={
  visitor:'laGordaCommunityVisitor', name:'laGordaCommunityName', game:'laGordaCommunityGame', best:'laGordaCommunityBest'
};
function randomVisitor(){return (crypto.randomUUID?.()||`guest-${Date.now()}-${Math.random().toString(16).slice(2)}`).replace(/[^a-zA-Z0-9_-]/g,'').slice(0,80)}
const visitorId=localStorage.getItem(storage.visitor)||randomVisitor(); localStorage.setItem(storage.visitor,visitorId);
let name=(localStorage.getItem(storage.name)||'').trim().slice(0,20);
let state={messages:[],leaderboards:{red_black:[],higher_lower:[]},whatsapp:{},activeGame:null,chatEnabled:true,onlineCount:0,maxLength:180};
let namePurpose='chat', nameResolve=null, pollTimer=null, toastTimer=null;
const bestByType=(()=>{try{return JSON.parse(localStorage.getItem(storage.best)||'{}')}catch{return {}}})();
const mini={type:['red_black','higher_lower'].includes(localStorage.getItem(storage.game))?localStorage.getItem(storage.game):'red_black',score:0,best:0,current:null,ended:false,busy:false,message:''};

async function api(url,opt={}){const r=await fetch(url,{...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'No se pudo completar la acción.');return d}
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2300)}
function validName(value){const n=String(value||'').trim().replace(/\s+/g,' ').slice(0,20);return n.length>=2&&!/^(la\s*gorda|administraci[oó]n|admin|administrador(?:a)?|sistema|moderador(?:a)?|staff|oficial)$/i.test(n)}
function askName(purpose='chat'){namePurpose=purpose;return new Promise(resolve=>{nameResolve=resolve;$('nameInput').value=name;$('nameError').textContent='';$('nameOverlay').classList.remove('hidden');setTimeout(()=>$('nameInput').focus(),30)})}
function closeName(result=false){$('nameOverlay').classList.add('hidden');const resolve=nameResolve;nameResolve=null;if(resolve)resolve(result)}
function saveName(){const n=$('nameInput').value.trim().replace(/\s+/g,' ').slice(0,20);if(!validName(n)){ $('nameError').textContent='Usá entre 2 y 20 caracteres y evitá nombres oficiales como LA GORDA o ADMIN.';return}name=n;localStorage.setItem(storage.name,name);renderIdentity();closeName(true);toast(`Hola, ${name}`)}
async function ensureName(purpose='chat'){if(validName(name))return true;return await askName(purpose)}
function renderIdentity(){const label=validName(name)?name:'ELEGIR NOMBRE';$('identityBtn').textContent=validName(name)?`${name} · CAMBIAR`:'ELEGIR NOMBRE';$('previewIdentity').textContent=validName(name)?`Estás como ${name}`:'Entrá con tu nombre';$('drawerIdentity').textContent=validName(name)?`Estás como ${name}`:'Elegí un nombre para participar';$('miniName').textContent=validName(name)?`Jugás como ${name}`:''}
function timeLabel(iso){try{return new Date(iso).toLocaleTimeString('es-AR',{hour:'2-digit',minute:'2-digit'})}catch{return ''}}
function messageHtml(m){const own=m.visitorId===visitorId;const official=m.role==='official';return `<article class="msg ${own?'me':''} ${official?'official':''}"><div class="msgHead"><b>${official?'✓ ':''}${esc(m.name||'Invitado')}</b><time>${esc(timeLabel(m.createdAt))}</time></div><p>${esc(m.text||'')}</p></article>`}
function renderMessages(){const html=(state.messages||[]).map(messageHtml).join('')||'<div class="empty">Todavía no hay mensajes. Podés ser el primero.</div>';for(const id of ['messages','drawerMessages']){$(id).innerHTML=html;$(id).scrollTop=$(id).scrollHeight}const last=(state.messages||[]).slice(-2);$('previewMessages').innerHTML=last.length?last.map(m=>`<div class="previewLine"><b>${esc(m.name)}:</b> ${esc(m.text)}</div>`).join(''):'<div class="previewLine">Todavía no hay mensajes.</div>'}
function statusLabel(status){return ({waiting:'ESPERANDO JUGADORES',starting:'COMENZANDO',playing:'PARTIDA EN VIVO',verifying:'VERIFICANDO PREMIO',paused:'PARTIDA PAUSADA',resuming:'REANUDANDO',finalizing:'ÚLTIMAS BOLILLAS'})[status]||'PARTIDA ACTIVA'}
function renderLive(){const game=state.activeGame;if(!game){$('liveContent').innerHTML=`<div class="eyebrow"><span class="liveDot" style="background:#7d7288;box-shadow:none"></span> AHORA MISMO</div><h1>La comunidad sigue abierta</h1><p>No hay una partida activa. Podés jugar a los minijuegos o quedarte charlando.</p><div class="actions"><button class="btn primary" data-jump-games>JUGAR MINIJUEGOS</button></div>`;$('[data-jump-games]')?.addEventListener('click',()=>openGame(mini.type));return}const actions=[];if(game.canJoin&&game.joinUrl)actions.push(`<a class="btn primary" href="${esc(game.joinUrl)}">JUGAR AHORA</a>`);else if(state.whatsapp?.contactUrl)actions.push(`<a class="btn primary" target="_blank" rel="noopener" href="${esc(state.whatsapp.contactUrl)}">PEDIR ACCESO</a>`);if(game.transmissionEnabled&&game.transmissionUrl)actions.push(`<a class="btn secondary" href="${esc(game.transmissionUrl)}">VER TRANSMISIÓN</a>`);$('liveContent').innerHTML=`<div class="eyebrow"><span class="liveDot"></span> ${esc(statusLabel(game.status))}</div><h1>Sala ${esc(game.roomCode)}</h1><p>${game.mode} bolillas · ${game.playerCount} participante${game.playerCount===1?'':'s'}</p><div class="liveMeta"><span class="pill">${game.mode} BOLAS</span><span class="pill">${game.roomType==='test'?'SALA DE PRUEBA':'SALA OFICIAL'}</span></div><div class="actions">${actions.join('')||'<button class="btn ghost" disabled>ACCESO PRIVADO</button>'}</div>`}
function renderWhatsapp(){const group=state.whatsapp?.groupUrl||'',contact=state.whatsapp?.contactUrl||'';$('groupBtn').href=group||'#';$('contactBtn').href=contact||'#';$('groupBtn').setAttribute('aria-disabled',group?'false':'true');$('contactBtn').setAttribute('aria-disabled',contact?'false':'true');$('groupBtn').style.opacity=group?'1':'.45';$('contactBtn').style.opacity=contact?'1':'.45';$('groupBtn').onclick=e=>{if(!group){e.preventDefault();toast('El enlace del grupo todavía no está configurado.')}};$('contactBtn').onclick=e=>{if(!contact){e.preventDefault();toast('El WhatsApp de contacto todavía no está configurado.')}};$('whatsappHint').textContent=state.whatsapp?.number?`Contacto: ${state.whatsapp.number}`:'Grupo, novedades y contacto directo.'}
function renderState(){renderIdentity();renderMessages();renderLive();renderWhatsapp();$('onlineText').textContent=`${Math.max(1,Number(state.onlineCount)||1)} en la comunidad`;for(const id of ['chatInput','drawerInput','sendBtn','drawerSendBtn'])$(id).disabled=state.chatEnabled===false;$('chatInput').placeholder=state.chatEnabled===false?'Chat pausado por La Gorda':'Escribí un mensaje…';$('drawerInput').placeholder=$('chatInput').placeholder;renderLeaderboard()}
async function refresh(silent=true){try{state=await api(`/api/community/state?visitorId=${encodeURIComponent(visitorId)}`);renderState()}catch(e){if(!silent)toast(e.message)}}
async function sendFrom(input){const text=input.value.trim();if(!text)return;if(!(await ensureName('chat')))return;try{input.disabled=true;const d=await api('/api/community/chat',{method:'POST',body:JSON.stringify({visitorId,name,text})});input.value='';if(d.state)state=d.state;renderState()}catch(e){toast(e.message)}finally{input.disabled=false;input.focus()}}
function openChat(){ensureName('chat').then(ok=>{if(!ok)return;$('chatDrawer').classList.remove('hidden');$('drawerInput').focus();renderMessages()})}
function closeChat(){$('chatDrawer').classList.add('hidden')}
function randomCard(){const suits=[{symbol:'♥',color:'red',face:'corazon'},{symbol:'♦',color:'red',face:'diamante'},{symbol:'♠',color:'black',face:'pica'},{symbol:'♣',color:'black',face:'trebol'}],suit=suits[Math.floor(Math.random()*suits.length)],value=1+Math.floor(Math.random()*13);return {...suit,value,rank:value===1?'A':value===11?'J':value===12?'Q':value===13?'K':String(value)}}
function showCard(card,hidden=false){const host=$('playingCard');if(hidden||!card){host.className='playingCard back';host.style.backgroundImage='';host.innerHTML='';return}host.className='playingCard';host.style.backgroundImage=`url('/assets/cards/${card.face}.webp')`;host.innerHTML=`<div class="cardIndex top ${card.color}">${esc(card.rank)}<small>${card.symbol}</small></div><div class="cardIndex bottom ${card.color}">${esc(card.rank)}<small>${card.symbol}</small></div>`}
function gameTitle(type){return type==='red_black'?'ROJO O NEGRO':'MAYOR O MENOR'}
function resetMini(keepType=true){mini.score=0;mini.current=null;mini.ended=false;mini.busy=false;mini.message='';mini.best=Number(bestByType[mini.type])||0;if(!keepType)mini.type='red_black'}
function setGame(type){if(!['red_black','higher_lower'].includes(type))type='red_black';mini.type=type;localStorage.setItem(storage.game,type);resetMini();if(type==='higher_lower')mini.current=randomCard();renderGame()}
function renderGame(){const type=mini.type;document.querySelectorAll('[data-game-tab]').forEach(b=>b.classList.toggle('active',b.dataset.gameTab===type));$('gameTitle').textContent=gameTitle(type);$('gameHint').textContent=type==='red_black'?'Elegí el color de la próxima carta. Cada acierto suma uno a tu racha.':'Mirá la carta actual y elegí si la próxima será mayor o menor. Los empates mantienen la racha.';$('gameScore').textContent=mini.score;$('gameBest').textContent=Math.max(Number(bestByType[type])||0,mini.best||0);if(type==='higher_lower'&&!mini.current&&!mini.ended)mini.current=randomCard();showCard(mini.current,type==='red_black'&&!mini.current);$('gameResult').textContent=mini.message||(type==='red_black'?'Elegí rojo o negro.':`Carta actual: ${mini.current.rank}${mini.current.symbol}. ¿La próxima será mayor o menor?`);$('gameChoices').innerHTML=type==='red_black'?'<button class="redChoice" data-choice="red">ROJO</button><button class="blackChoice" data-choice="black">NEGRO</button>':'<button class="higherChoice" data-choice="higher">MAYOR</button><button class="lowerChoice" data-choice="lower">MENOR</button>';$('gameChoices').classList.toggle('hidden',mini.ended);$('gameRestart').classList.toggle('hidden',!mini.ended);$('gameChoices').querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>playMini(b.dataset.choice));renderLeaderboard()}
function renderLeaderboard(){if(!$('leaderboard'))return;const board=state.leaderboards?.[mini.type]||[];$('leaderboard').innerHTML=`<b>Mejores rachas de la comunidad:</b><br>${board.length?board.slice(0,5).map((x,i)=>`${i+1}. ${esc(x.name)} · ${Number(x.bestScore)||0}`).join(' &nbsp;·&nbsp; '):'Todavía no hay puntajes.'}`}
async function submitScore(score){if(!validName(name)||score<=0)return;try{state=await api('/api/community/score',{method:'POST',body:JSON.stringify({visitorId,name,gameType:mini.type,score})});renderLeaderboard()}catch{}}
async function playMini(choice){if(mini.ended||mini.busy)return;mini.busy=true;const next=randomCard();let correct=false,tie=false;if(mini.type==='red_black')correct=choice===next.color;else{const current=mini.current||randomCard();mini.current=current;tie=next.value===current.value;correct=tie||(choice==='higher'?next.value>current.value:next.value<current.value)}showCard(next);if(tie){mini.current=next;mini.message=`Empate: salió ${next.rank}${next.symbol}. La racha sigue igual.`;mini.busy=false;renderGame();return}if(correct){mini.score++;mini.best=Math.max(mini.best,mini.score);bestByType[mini.type]=Math.max(Number(bestByType[mini.type])||0,mini.best);localStorage.setItem(storage.best,JSON.stringify(bestByType));mini.current=next;mini.message=mini.type==='red_black'?`¡Correcto! Salió ${next.rank}${next.symbol}. Elegí otra vez.`:`¡Correcto! Salió ${next.rank}${next.symbol}. ¿Mayor o menor?`;mini.busy=false;renderGame();submitScore(mini.best);return}mini.ended=true;mini.current=next;mini.message=`Te equivocaste: salió ${next.rank}${next.symbol}. Racha final: ${mini.score}.`;mini.busy=false;bestByType[mini.type]=Math.max(Number(bestByType[mini.type])||0,mini.score);localStorage.setItem(storage.best,JSON.stringify(bestByType));renderGame();submitScore(mini.score)}
async function openGame(type){$('gameOverlay').classList.remove('hidden');setGame(type||mini.type)}
function closeGame(){$('gameOverlay').classList.add('hidden')}
function bind(){
  $('saveNameBtn').onclick=saveName;$('cancelNameBtn').onclick=()=>closeName(false);$('nameInput').onkeydown=e=>e.key==='Enter'&&saveName();$('identityBtn').onclick=()=>askName('chat');
  $('sendBtn').onclick=()=>sendFrom($('chatInput'));$('chatInput').onkeydown=e=>{if(e.key==='Enter')sendFrom($('chatInput'))};$('drawerSendBtn').onclick=()=>sendFrom($('drawerInput'));$('drawerInput').onkeydown=e=>{if(e.key==='Enter')sendFrom($('drawerInput'))};
  $('openChatBtn').onclick=openChat;$('closeChatBtn').onclick=closeChat;document.querySelectorAll('[data-open-game]').forEach(el=>el.onclick=()=>openGame(el.dataset.openGame));$('closeGameBtn').onclick=closeGame;document.querySelectorAll('[data-game-tab]').forEach(el=>el.onclick=()=>setGame(el.dataset.gameTab));$('gameRestart').onclick=()=>{resetMini();if(mini.type==='higher_lower')mini.current=randomCard();renderGame()};
  document.querySelectorAll('[data-nav]').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('[data-nav]').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const n=btn.dataset.nav;if(n==='home')scrollTo({top:0,behavior:'smooth'});if(n==='games')$('gamesSection').scrollIntoView({behavior:'smooth',block:'center'});if(n==='chat')openChat();if(n==='whatsapp')$('groupBtn').scrollIntoView({behavior:'smooth',block:'center'})});
  document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeChat();closeGame();if(!$('nameOverlay').classList.contains('hidden'))closeName(false)}});
}
async function init(){bind();renderIdentity();await refresh(false);pollTimer=setInterval(()=>refresh(true),4000);window.addEventListener('focus',()=>refresh(true));}
window.addEventListener('DOMContentLoaded',init);
