(()=>{'use strict';
const $=id=>document.getElementById(id);const DEVICE_KEY='bingoEventoAccessCode:v1';let accessPayload=null,live=null,currentIndex=0,accessCode='',heartbeatTimer=null,es=null,pollTimer=null,working=false,selectedClaimType='';
const labels={ambo:'AMBO CABEZA',line:'LÍNEA',doubleLine:'DOBLE LÍNEA',tripleLine:'TRIPLE LÍNEA',corners:'4 ESQUINAS',bingo:'BINGO'};
const cleanCode=value=>{const raw=String(value||'').toUpperCase().replace(/[^23456789ABCDEFGHJKLMNPQRSTUVWXYZ]/g,'').slice(0,8);return raw.length>4?raw.slice(0,4)+'-'+raw.slice(4):raw};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const statusLabel=s=>({waiting:'ESPERANDO COMIENZO',starting:'COMENZANDO',playing:'JUGANDO',paused:'PAUSA',verifying:'VERIFICANDO JUGADA',resuming:'CONTINUANDO',finalizing:'CERRANDO PARTIDA',finished:'EVENTO FINALIZADO'})[s]||String(s||'ESPERANDO').toUpperCase();
const ballParts=(n,mode)=>{if(n===null||n===undefined)return{letter:'',number:'—'};const num=Number(n);return Number(mode)===75?{letter:'BINGO'[Math.min(4,Math.floor((num-1)/15))],number:String(num)}:{letter:'',number:String(num)}};
const ballLabel=(n,mode)=>n===null||n===undefined?'—':Number(mode)===75?`${'BINGO'[Math.min(4,Math.floor((Number(n)-1)/15))]} ${n}`:String(n);
function toast(message){const host=$('toast');host.textContent=String(message||'');host.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>host.classList.remove('show'),2800)}
function applyBrand(event){$('eventLogo').src=event?.logoUrl||'/assets/logo.webp';$('eventName').textContent=event?.name||'El Bingo de la Gorda';$('eventDetails').textContent=[event?.tagline,event?.date,event?.location,event?.sponsor?`Presentado por ${event.sponsor}`:''].filter(Boolean).join(' · ')}
function baseCards(){return live?.cards?.length?live.cards:(accessPayload?.cards||[])}
function selectedCard(){const cards=baseCards();if(!cards.length)return null;if(currentIndex>=cards.length)currentIndex=0;return cards[currentIndex]}
function setShellMode(){const shell=$('eventShell');shell.classList.toggle('gameMobile',(window.innerWidth||0)<=720);shell.classList.toggle('gameDesktop',(window.innerWidth||0)>720)}
function ticketGrid(card,interactive=false){const mode=Number(card?.mode)===75?75:90,drawn=new Set((live?.room?.game?.drawn||[]).map(Number)),marks=new Set((card?.marks||[]).map(Number)),manual=interactive&&live?.live&&!live?.player?.autoMark,cols=mode===75?5:9;const cells=(card?.grid||[]).flat().map((value,index)=>{if(value===null||value===undefined||value==='')return '<span class="cell blank">·</span>';if(String(value).toUpperCase()==='LIBRE')return `<span class="cell free ${mode===75?'bingo-n':''}">★</span>`;const n=Number(value),classes=['cell'];if(mode===75)classes.push(`bingo-${'bingo'[index%5]}`);if(drawn.has(n))classes.push('drawn');if(marks.has(n))classes.push('marked');const disabled=!manual||live?.room?.status!=='playing'||!drawn.has(n);return interactive?`<button type="button" class="${classes.join(' ')}" data-mark-number="${n}" ${disabled?'disabled':''}>${esc(value)}</button>`:`<span class="${classes.join(' ')}">${esc(value)}</span>`}).join('');const head=mode===75?'<div class="ticketColumns"><span class="bingo-b">B</span><span class="bingo-i">I</span><span class="bingo-n">N</span><span class="bingo-g">G</span><span class="bingo-o">O</span></div>':'';return `${head}<div class="ticket m${mode}">${cells}</div>`}
function raceText(card){const race=card?.race;if(!race)return'';const missing=Math.max(0,Number(race.missing)||0);return missing===0?`Listo para ${race.label||'la jugada'}`:missing===1?`Falta 1 para ${race.label||'la jugada'}`:`Faltan ${missing} para ${race.label||'la jugada'}`}
function markedCount(card){return Number(card?.markedCount)||((card?.marks||[]).length)}
function bestCardIndex(cards){const active=Boolean(live?.live&&(live?.room?.game?.drawn||[]).length&&['starting','playing','paused','verifying','resuming'].includes(String(live?.room?.status||'')));if(!active)return-1;const scores=cards.map(card=>card.race?Number(card.race.missing)*10+Number(card.race.importance||9):Infinity),best=Math.min(...scores);return Number.isFinite(best)?scores.findIndex(v=>v===best):-1}
function cardSwitcher(cards){const best=bestCardIndex(cards);return `<div class="eventCardSwitcher" aria-label="Elegir cartón">${cards.map((card,index)=>`<button type="button" class="eventCardBtn ${index===currentIndex?'active':''} ${index===best?'closest':''}" data-card-tab="${index}"><b>CARTÓN ${String(card.cardNumber).padStart(4,'0')}</b><small>${index===currentIndex?'ACTIVO':`${index+1} de ${cards.length}`}</small>${index===best?`<span class="hot">🔥 MÁS CERCA${card.race?` · ${esc(raceText(card))}`:''}</span>`:''}</button>`).join('')}</div>`}
function claimOptions(card){const mode=Number(card?.mode),rules=live?.room?.game?.rules||{},r=card?.readiness||{},items=[];if(mode===90&&rules.ambocabeza)items.push({type:'ambo',label:'AMBO CABEZA',short:'AMBO',ready:Boolean(r.amboEligible)});if(rules.line!==false)items.push({type:'line',label:'LÍNEA',short:'LÍNEA',ready:Boolean(r.lineEligible)});if(mode===75&&rules.doubleLine)items.push({type:'doubleLine',label:'DOBLE LÍNEA',short:'DOBLE',ready:Boolean(r.doubleLineEligible)});if(mode===75&&rules.tripleLine)items.push({type:'tripleLine',label:'TRIPLE LÍNEA',short:'TRIPLE',ready:Boolean(r.tripleLineEligible)});if(mode===75&&rules.corners)items.push({type:'corners',label:'CUATRO ESQUINAS',short:'4 ESQ.',ready:Boolean(r.cornersEligible)});if(rules.bingo!==false)items.push({type:'bingo',label:'BINGO',short:'BINGO',ready:Boolean(r.bingoEligible)});return items}
function claimControls(card){const auto=live?.room?.claimMode==='automatic_ties',items=claimOptions(card);if(auto){selectedClaimType='';return `<div class="claimCenter"><div class="autoClaimNotice notice"><b>RECLAMO AUTOMÁTICO · EMPATES</b><span>No necesitás tocar RECLAMAR. El servidor valida todos los cartones.</span></div><div class="prizeTrack">${items.map(item=>`<button type="button" class="prizeSquare ${item.ready?'ready':'open'}" disabled><span>${item.ready?'!':'•'}</span><b>${esc(item.short)}</b></button>`).join('')}</div></div>`}const ready=items.filter(item=>item.ready&&['playing','verifying'].includes(String(live?.room?.status||'')));let selected=ready.find(item=>item.type===selectedClaimType);if(!selected&&ready.length){selected=ready[0];selectedClaimType=selected.type}if(!ready.length)selectedClaimType='';const only=items.length===1?items[0]:null,main=selected||only,can=Boolean(selected)&&!working;return `<div class="claimCenter"><button id="primaryClaim" type="button" class="primaryClaim ${can?'ready':''}" ${can?`data-claim="${selected.type}" data-label="${esc(selected.label)}"`:'disabled'}>${main?`RECLAMAR ${esc(main.short)}`:'RECLAMAR'}</button><div class="prizeTrack">${items.map(item=>`<button type="button" class="prizeSquare ${item.ready?'ready':'open'} ${selected?.type===item.type?'selected':''}" data-prize-select="${item.type}" data-ready="${item.ready?'1':'0'}" ${item.ready?'':'disabled'}><span>${item.ready?'!':'•'}</span><b>${esc(item.short)}</b></button>`).join('')}</div></div>`}
function winnersMarkup(){const confirmed=(live?.ownClaims||[]).filter(c=>c.status==='confirmed');const latest=live?.room?.latestConfirmed;const publicOne=latest?`<div><b>${esc(latest.prizeLabel||labels[latest.type]||latest.type)}</b><br>${esc(latest.playerName||'')} · Cartón ${esc(String(latest.cardNumber||''))}</div>`:'';return confirmed.length?confirmed.slice(-6).reverse().map(c=>`<div><b>${esc(c.prizeLabel||labels[c.type]||c.type)}</b><br>Tu Cartón ${esc(String(c.cardNumber||''))}</div>`).join(''):publicOne||'<div>Todavía no hay ganadores confirmados.</div>'}
function bindCardTabs(){document.querySelectorAll('[data-card-tab]').forEach(btn=>btn.onclick=()=>{currentIndex=Number(btn.dataset.cardTab)||0;selectedClaimType='';renderLive()})}
function bindGameActions(card){bindCardTabs();document.querySelectorAll('[data-mark-number]').forEach(btn=>btn.onclick=()=>toggleMark(card,Number(btn.dataset.markNumber),!new Set(card.marks||[]).has(Number(btn.dataset.markNumber))));document.querySelectorAll('[data-prize-select]').forEach(btn=>btn.onclick=()=>{if(btn.dataset.ready!=='1')return;selectedClaimType=btn.dataset.prizeSelect;renderLive()});document.querySelectorAll('[data-claim]').forEach(btn=>btn.onclick=()=>claim(card,btn.dataset.claim,btn.dataset.label));if($('manualGame'))$('manualGame').onclick=()=>setAuto(false);if($('autoGame'))$('autoGame').onclick=()=>setAuto(true)}
function renderWaiting(){const cards=baseCards(),card=selectedCard(),event=live?.event||accessPayload?.event,prepared=Boolean(live?.live);$('root').innerHTML=`<section class="eventWaiting"><div class="waitingPulse"><i></i> SALA DE ESPERA PREMIUM</div><h1>${esc(live?.player?.name||accessPayload?.player?.name||'Tus cartones están listos')}</h1><p>${prepared?'La sala ya está preparada. Cuando el conductor inicie, esta pantalla cambia automáticamente a la partida.':'Tus cartones están cargados. Esperando que el conductor prepare la sala del Evento.'} Podés salir y volver desde este mismo dispositivo sin ingresar el código otra vez.</p><div class="eventIdentity"><span><strong>${cards.length}</strong> cartón${cards.length===1?'':'es'}</span><span>Bingo <strong>${esc(event?.mode||'')}</strong></span>${event?.sponsor?`<span>Presentado por <strong>${esc(event.sponsor)}</strong></span>`:''}</div>${cardSwitcher(cards)}${card?`<div class="panel eventTicketPanel eventMiniPreview"><div class="ticketHead"><b>Cartón ${String(card.cardNumber).padStart(4,'0')}</b><small>LISTO PARA JUGAR</small></div>${ticketGrid(card,false)}</div>`:''}</section>`;bindCardTabs()}
function renderGame(){const cards=baseCards(),card=selectedCard(),room=live?.room||{},drawn=room?.game?.drawn||[],mode=Number(room?.game?.mode)||Number(card?.mode)||90,last=room?.game?.lastBall,parts=ballParts(last,mode),recent=drawn.slice(-6).reverse().map(n=>`<span>${esc(ballLabel(n,mode))}</span>`).join(''),history=[...drawn].sort((a,b)=>a-b).map(n=>`<span>${esc(ballLabel(n,mode))}</span>`).join('');const notice=room.pendingClaim?`<div class="eventNotice"><b>VERIFICANDO ${esc(String(room.pendingClaim.type||'JUGADA').toUpperCase())}</b> · ${esc(room.pendingClaim.playerName||'')} · Cartón ${esc(String(room.pendingClaim.cardNumber||''))}</div>`:room.latestConfirmed?`<div class="eventNotice"><b>${esc(room.latestConfirmed.prizeLabel||labels[room.latestConfirmed.type]||'PREMIO')} CONFIRMADO</b> · ${esc(room.latestConfirmed.playerName||'')} · Cartón ${esc(String(room.latestConfirmed.cardNumber||''))}</div>`:'';$('root').innerHTML=`<div class="eventGame gameLayout"><section class="gameMain"><div class="ballPanel eventBall"><div class="ballStage"><div class="ball ${last==null?'empty':''}">${parts.letter?`<span class="ballLetter">${esc(parts.letter)}</span>`:''}<span class="ballNumber">${esc(parts.number)}</span></div></div><div class="gameStatus">${esc(statusLabel(room.status))}</div><div class="ballProgress"><strong>Bolilla ${drawn.length} / ${mode}</strong></div><div class="recent">${recent}</div></div>${notice}<div class="ticketPanel eventTicketPanel"><div class="eventIdentity"><span>${esc(live?.player?.name||'Jugador')}</span><span>${live?.player?.autoMark?'AUTOMARCADO':'MARCADO MANUAL'}</span></div>${cardSwitcher(cards)}<div class="ticketHead"><b>Cartón ${String(card.cardNumber).padStart(4,'0')}</b><small>${live?.player?.autoMark?'AUTOMARCADO':'MARCADO MANUAL'}</small></div>${ticketGrid(card,true)}${room.markingMode==='manual_only'?'<div class="notice" style="margin-top:8px"><b>SOLO MANUAL</b> · Tocá únicamente números que ya salieron.</div>':`<div class="modeRow"><button id="manualGame" class="modeBtn ${!live?.player?.autoMark?'active':''}">MANUAL</button><button id="autoGame" class="modeBtn ${live?.player?.autoMark?'active':''}">AUTOMARCADO</button></div>`}${claimControls(card)}${card.race?`<div class="notice" style="margin-top:8px"><b>🔥 ESTE CARTÓN:</b> ${esc(raceText(card))}</div>`:''}</div></section><aside class="sideInfo"><div class="panel" style="margin:0"><h3>NÚMEROS SALIDOS · ${drawn.length}/${mode}</h3><div class="numbersGrid">${history||'<span>—</span>'}</div></div><div class="panel" style="margin:0"><h3>GANADORES</h3><div class="claimHistory">${winnersMarkup()}</div></div></aside></div>`;bindGameActions(card)}
function renderFinished(){const cards=baseCards(),own=(live?.ownClaims||[]).filter(c=>c.status==='confirmed'),event=live?.event||accessPayload?.event,acta=live?.result?.available&&accessCode?`<a class="btn primary" href="/api/event/result.pdf?codigo=${encodeURIComponent(accessCode)}" target="_blank" rel="noopener">📄 DESCARGAR ACTA PREMIUM PDF</a>`:'';$('root').innerHTML=`<section class="eventFinal"><img src="${esc(event?.logoUrl||'/assets/logo.webp')}" alt=""><span class="eventKicker">EVENTO FINALIZADO</span><h1>Gracias por jugar, ${esc(live?.player?.name||accessPayload?.player?.name||'')}</h1><p>${own.length?`Tenés ${own.length} jugada${own.length===1?'':'s'} confirmada${own.length===1?'':'s'}.`:'La partida terminó.'}</p>${acta}<div class="eventIdentity" style="justify-content:center"><span>${cards.length} cartón${cards.length===1?'':'es'}</span><span>${esc(event?.name||'Evento Premium')}</span></div></section>`}
function renderLive(){applyBrand(live?.event||accessPayload?.event);setShellMode();const room=live?.room||null;if(room?.status==='finished'||live?.result?.available){renderFinished();return}if(!live?.live||!room||room.status==='waiting'){renderWaiting();return}renderGame()}
async function json(url,opt={}){const r=await fetch(url,{...opt,headers:{...(opt.body?{'Content-Type':'application/json'}:{}),...(opt.headers||{})},cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'No se pudo completar la acción.');return d}
async function refreshLive(){if(!accessCode)return;try{live=await json('/api/event/player-state?codigo='+encodeURIComponent(accessCode));renderLive()}catch(e){toast(e.message)}}
function connectEvents(){try{es?.close();es=new EventSource(`/api/events?role=event&codigo=${encodeURIComponent(accessCode)}`);es.addEventListener('state',ev=>{try{live=JSON.parse(ev.data);renderLive()}catch{}});es.addEventListener('logout',()=>{es?.close();refreshLive()});es.onerror=()=>{es?.close();clearTimeout(pollTimer);pollTimer=setTimeout(()=>{refreshLive();connectEvents()},1800)}}catch{clearTimeout(pollTimer);pollTimer=setTimeout(refreshLive,1800)}}
async function toggleMark(card,number,marked){if(working)return;working=true;try{live=await json('/api/event/mark',{method:'POST',body:JSON.stringify({codigo:accessCode,lotCode:card.lotCode,cardNumber:card.cardNumber,number,marked})});renderLive()}catch(e){toast(e.message)}finally{working=false}}
async function setAuto(enabled){if(working)return;working=true;try{live=await json('/api/event/automark',{method:'POST',body:JSON.stringify({codigo:accessCode,enabled:Boolean(enabled)})});renderLive();toast(enabled?'Automarcado activado.':'Marcado manual activado.')}catch(e){toast(e.message)}finally{working=false}}
async function claim(card,type,label){if(working)return;working=true;renderLive();try{const d=await json('/api/event/claim',{method:'POST',body:JSON.stringify({codigo:accessCode,lotCode:card.lotCode,cardNumber:card.cardNumber,type})});live=d.state;toast(`${label||labels[type]||type}: reclamo recibido.`);renderLive()}catch(e){toast(e.message);await refreshLive()}finally{working=false}}
async function access(){const code=cleanCode($('code').value);$('code').value=code;if(code.length!==9){$('msg').className='eventMsg err';$('msg').textContent='El código debe tener 8 caracteres.';return}$('go').disabled=true;$('msg').className='eventMsg';$('msg').textContent='Buscando tus cartones…';try{accessPayload=await json('/api/event/access-info?codigo='+encodeURIComponent(code));accessCode=code;localStorage.setItem(DEVICE_KEY,code);try{history.replaceState(null,'',location.pathname)}catch{}$('accessScreen').classList.add('hidden');$('app').classList.remove('hidden');applyBrand(accessPayload.event);await refreshLive();const cards=baseCards(),idx=cards.findIndex(card=>card.lotCode===accessPayload.accessedCard?.lotCode&&Number(card.cardNumber)===Number(accessPayload.accessedCard?.cardNumber));currentIndex=Math.max(0,idx);startHeartbeat();connectEvents()}catch(e){localStorage.removeItem(DEVICE_KEY);$('msg').className='eventMsg err';$('msg').textContent=e.message}finally{$('go').disabled=false}}
async function heartbeat(){if(!accessCode)return;try{await fetch('/api/event/heartbeat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({codigo:accessCode})})}catch{}}
function startHeartbeat(){clearInterval(heartbeatTimer);heartbeat();heartbeatTimer=setInterval(heartbeat,30000)}
function reset(){clearInterval(heartbeatTimer);es?.close();accessPayload=null;live=null;accessCode='';selectedClaimType='';localStorage.removeItem(DEVICE_KEY);$('app').classList.add('hidden');$('accessScreen').classList.remove('hidden');$('msg').className='eventMsg';$('msg').textContent='Ingresá el código privado de cualquiera de tus cartones.';$('code').value='';$('code').focus()}
const q=new URLSearchParams(location.search);const generalEventCode=String(q.get('evento')||'').trim().toUpperCase();if(generalEventCode){json('/api/event/public-info?evento='+encodeURIComponent(generalEventCode)).then(d=>{if(!accessPayload&&!live&&d.event)applyBrand(d.event)}).catch(()=>{})}const saved=q.get('codigo')||localStorage.getItem(DEVICE_KEY)||'';$('code').value=cleanCode(saved);$('code').oninput=()=>{$('code').value=cleanCode($('code').value)};$('code').onkeydown=e=>{if(e.key==='Enter')access()};$('go').onclick=access;$('changeCode').onclick=reset;window.addEventListener('resize',()=>{setShellMode();if(live||accessPayload)renderLive()});setShellMode();if($('code').value.length===9)access();
})();
