(() => {
'use strict';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
let token=sessionStorage.getItem('bingoOnlineAdminToken:owner')||'';
let community=null,event=null,adminState=null,lot=null,cards=[],selectedCard=null;
let assignments={};
let sponsorPending={};
let test={mode:'manual',order:[],drawn:[],paused:false,timer:null};
let pollTimer=null,sponsorTimer=null,sponsorIndex=0;
let seenWins=new Set();
const toast=text=>{const h=$('toast');if(!h)return;h.textContent=text;h.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>h.classList.remove('show'),2600)};
const req=async(url,opt={})=>{const headers={...(opt.body?{'Content-Type':'application/json'}:{}),...(token?{'X-Admin-Token':token}:{}),...(opt.headers||{})};const r=await fetch(url,{...opt,headers});const type=r.headers.get('content-type')||'';const d=type.includes('application/json')?await r.json():null;if(!r.ok)throw new Error(d?.error||`Error ${r.status}`);return d};
const pad=n=>String(Number(n)||0).padStart(3,'0');
const flattenLot=x=>(x?.series||[]).flatMap(s=>(s.cards||[]).map(c=>({...c,seriesNumber:Number(c.seriesNumber)||Number(s.number)||1,globalNumber:Number(c.globalNumber)||0,mode:Number(c.mode)||Number(x.mode)||90}))).sort((a,b)=>(a.globalNumber||0)-(b.globalNumber||0));
const nums=card=>(card?.grid||[]).flat().filter(Number.isFinite);
const ownerOf=n=>assignments[String(Number(n))]?.name||'';
const assignmentKey=()=>`evento_lab_assignments:${event?.lotCode||lot?.code||'sin_lote'}`;
function saveAssignments(){try{localStorage.setItem(assignmentKey(),JSON.stringify(assignments))}catch{}}
function loadAssignments(){try{assignments=JSON.parse(localStorage.getItem(assignmentKey())||'{}')||{}}catch{assignments={}}}
function showAuth(on){$('auth')?.classList.toggle('hidden',!on);$('app')?.classList.toggle('hidden',on)}
async function login(){try{$('authError').textContent='';const d=await req('/api/admin/login',{method:'POST',body:JSON.stringify({password:$('password').value})});token=d.token;sessionStorage.setItem('bingoOnlineAdminToken:owner',token);sessionStorage.setItem('bingoOnlineAdminRole','owner');showAuth(false);await loadAll();startPolling()}catch(e){$('authError').textContent=e.message}}
async function init(){bind();renderSponsorEditors();renderPreviewBoard(90,[]);if(!token){showAuth(true);return}try{await loadAll();showAuth(false);startPolling()}catch{token='';sessionStorage.removeItem('bingoOnlineAdminToken:owner');showAuth(true)}}
function startPolling(){clearInterval(pollTimer);pollTimer=setInterval(()=>loadState(true),1800)}
async function loadAll(){community=await req('/api/admin/community');event=community?.event||null;await loadState(true);if(event?.lotCode){try{await loadLot(event.lotCode)}catch{}}renderAll()}
async function loadState(silent=false){try{adminState=await req('/api/admin/state');renderRealState();renderPreview();detectWinners()}catch(e){if(!silent)toast(e.message)}}
async function loadLot(code){lot=await fetch(`/api/community/cards/lot?lot=${encodeURIComponent(code)}`).then(async r=>{const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'No se pudo cargar el lote.');return d});cards=flattenLot(lot);loadAssignments();if(!selectedCard&&cards.length)selectedCard=cards[0];renderAssignments();renderCard();renderEventStatus()}
function renderAll(){renderEventForm();renderEventStatus();renderSponsors();renderAssignments();renderCard();renderRealState();renderPreview()}
function renderEventForm(){if(!event)return;$('eventTitle').value=event.title||'';$('eventMode').value=String(Number(event.mode)===75?75:90);$('eventCount').value=String(event.cardCount||120);if(event.design?.sponsorPosition)$('sponsorPosition').value=event.design.sponsorPosition}
function renderEventStatus(){const h=$('eventStatus');if(!h)return;if(!event){h.innerHTML='Sin evento. Guardá el nombre para empezar.';return}const lotText=event.lotReady?`${event.lotTotalCards||cards.length} cartones · ${esc(event.lotCode||'')}`:'sin lote';const room=event.roomCode?`Sala ${esc(event.roomCode)} · ${esc(event.roomStatus||'preparada')}`:'sala no preparada';h.innerHTML=`<b>${esc(event.title)}</b><br>Bingo ${Number(event.mode)===75?75:90} · ${lotText}<br>${room}`}
async function saveEvent(){const title=$('eventTitle').value.trim();if(!title)return toast('Escribí el nombre del evento.');const count=Math.max(6,Math.min(240,Math.ceil((Number($('eventCount').value)||120)/6)*6));$('eventCount').value=String(count);try{community=await req('/api/admin/community/event',{method:'POST',body:JSON.stringify({action:'save',title,startsAt:new Date(Date.now()+3600000).toISOString(),mode:Number($('eventMode').value),maxPeople:100,cardCount:count,autoSeconds:Number($('interval').value)||8})});event=community.event;if($('logoFile').files?.[0])await uploadLogo($('logoFile').files[0]);await saveSponsorPosition(true);renderAll();toast('Evento guardado. Ya podés prepararlo.')}catch(e){toast(e.message)}}
async function uploadLogo(file){const data=await imageData(file,1000,1000,'contain');community=await req('/api/admin/community/event/asset',{method:'POST',body:JSON.stringify({action:'upload',key:'logo',data})});event=community.event;$('logoFile').value=''}
async function generateLot(){if(!event)return toast('Primero guardá el evento.');if(event.roomCode)return toast('La sala ya fue preparada.');if(!confirm('¿Generar el lote numerado del evento?'))return;try{community=await req('/api/admin/community/event',{method:'POST',body:JSON.stringify({action:'generate-lot'})});event=community.event;await loadLot(event.lotCode);renderAll();toast(`${cards.length} cartones generados.`)}catch(e){toast(e.message)}}
function cardByNo(n){n=Number(n);return cards.find(c=>Number(c.globalNumber)===n)||null}
function parseCardNumbers(raw){return [...new Set(String(raw||'').split(/[\s,;]+/).map(Number).filter(Number.isFinite))]}
function assign(){if(!cards.length)return toast('Primero generá o cargá cartones.');const name=$('personName').value.trim().replace(/\s+/g,' ');if(name.length<2)return toast('Escribí el nombre.');const list=parseCardNumbers($('personCards').value);if(!list.length)return toast('Indicá al menos un número de cartón.');for(const n of list){if(!cardByNo(n))return toast(`El cartón ${pad(n)} no existe.`);const existing=ownerOf(n);if(existing&&existing.toLowerCase()!==name.toLowerCase())return toast(`El cartón ${pad(n)} ya está asignado a ${existing}.`)}for(const n of list)assignments[String(n)]={name};saveAssignments();$('personCards').value='';renderAssignments();renderCard();detectWinners();toast(`${name}: ${list.map(pad).join(', ')}`)}
function nextFree(){const c=cards.find(c=>!ownerOf(c.globalNumber));if(!c)return toast('No quedan cartones libres.');$('personCards').value=String(c.globalNumber)}
function renderAssignments(){const h=$('assignments');if(!h)return;if(!cards.length){h.innerHTML='<div class="status">Todavía no hay lote.</div>';return}const q=($('searchCard')?.value||'').trim().toLowerCase();const rows=cards.filter(c=>{const n=pad(c.globalNumber),name=ownerOf(c.globalNumber);return !q||n.includes(q)||name.toLowerCase().includes(q)}).map(c=>{const n=Number(c.globalNumber),name=ownerOf(n);return `<div class="personRow"><b>${pad(n)}</b><span>${name?esc(name):'<span style="color:var(--muted)">DISPONIBLE</span>'}</span><div class="row"><button data-view="${n}">VER</button>${name?`<button data-free="${n}">LIBERAR</button>`:''}</div></div>`}).join('');h.innerHTML=rows||'<div class="status">Sin resultados.</div>';h.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>selectCard(Number(b.dataset.view)));h.querySelectorAll('[data-free]').forEach(b=>b.onclick=()=>{const n=Number(b.dataset.free);if(confirm(`¿Liberar cartón ${pad(n)}?`)){delete assignments[String(n)];saveAssignments();renderAssignments();renderCard()}})}
function selectCard(n){const c=cardByNo(n);if(!c)return;selectedCard=c;$('cardNumber').value=String(n);renderCard();document.getElementById('cardHost')?.scrollIntoView({behavior:'smooth',block:'center'})}
function gridCols(card){return Number(card.mode)===75?5:9}
function renderCardMarkup(card,owner='',drawn=[]){if(!card)return '';const hits=new Set(drawn||[]),cols=gridCols(card),cells=(card.grid||[]).flat().map(v=>Number.isFinite(v)?`<div class="cardCell ${hits.has(v)?'hit':''}">${v}</div>`:'<div class="cardCell blank">·</div>').join('');return `<div class="bingoCard"><div class="cardHead"><div><div class="cardOwner">${esc(event?.title||lot?.title||'EVENTO')}</div>${owner?`<div style="font-size:12px;font-weight:800">${esc(owner)}</div>`:''}</div><div><div style="font-size:10px;font-weight:800">CARTÓN Nº</div><div class="cardNo">${pad(card.globalNumber)}</div></div></div><div class="cardGrid" style="grid-template-columns:repeat(${cols},1fr)">${cells}</div></div>`}
function renderCard(){const h=$('cardHost');if(!h)return;if(!selectedCard){h.innerHTML='Generá o cargá un lote para ver cartones.';$('downloadCard').disabled=true;$('printSix').disabled=true;$('playerLink').disabled=true;return}const drawn=adminState?.roomSettings?.eventMode?adminState?.game?.drawn||[]:test.drawn;h.innerHTML=renderCardMarkup(selectedCard,ownerOf(selectedCard.globalNumber),drawn);$('downloadCard').disabled=false;$('printSix').disabled=false;$('playerLink').disabled=!ownerOf(selectedCard.globalNumber)}
async function downloadCardPng(){if(!selectedCard)return;const mode=Number(selectedCard.mode)===75?75:90,cols=gridCols(selectedCard),rows=(selectedCard.grid||[]).length,title=event?.title||'EVENTO',owner=ownerOf(selectedCard.globalNumber);const canvas=document.createElement('canvas');canvas.width=mode===90?1400:1000;canvas.height=mode===90?680:1050;const x=canvas.getContext('2d');x.fillStyle='#f7f1df';x.fillRect(0,0,canvas.width,canvas.height);x.fillStyle='#241529';x.font='900 52px system-ui';x.fillText(title.slice(0,36).toUpperCase(),50,72);x.font='900 30px system-ui';if(owner)x.fillText(owner,50,118);x.textAlign='right';x.font='900 30px system-ui';x.fillText('CARTÓN Nº',canvas.width-50,62);x.font='1000 76px system-ui';x.fillText(pad(selectedCard.globalNumber),canvas.width-50,125);x.textAlign='center';const left=50,top=mode===90?165:185,w=canvas.width-100,h=canvas.height-top-50,cw=w/cols,ch=h/rows;(selectedCard.grid||[]).forEach((row,r)=>row.forEach((v,c)=>{x.strokeStyle='#6b5d43';x.lineWidth=3;x.strokeRect(left+c*cw,top+r*ch,cw,ch);x.fillStyle=Number.isFinite(v)?'#fff':'#d9d4c9';x.fillRect(left+c*cw+2,top+r*ch+2,cw-4,ch-4);if(Number.isFinite(v)){x.fillStyle='#111';x.font=`900 ${Math.floor(Math.min(cw,ch)*.52)}px system-ui`;x.fillText(String(v),left+c*cw+cw/2,top+r*ch+ch*.68)}}));const a=document.createElement('a');a.download=`${safeFile(title)}_CARTON_${pad(selectedCard.globalNumber)}.png`;a.href=canvas.toDataURL('image/png');a.click()}
function printSix(){if(!cards.length)return;const current=Number(selectedCard?.globalNumber)||1,start=Math.floor((current-1)/6)*6+1,group=cards.filter(c=>Number(c.globalNumber)>=start&&Number(c.globalNumber)<start+6);const win=window.open('','_blank');if(!win)return toast('Permití ventanas emergentes para imprimir.');win.document.write(`<!doctype html><html><head><title>Cartones ${pad(start)}-${pad(start+5)}</title><style>@page{size:A4 landscape;margin:7mm}body{font-family:Arial;margin:0}.page{display:grid;grid-template-columns:1fr 1fr;grid-template-rows:repeat(3,1fr);gap:5mm;height:190mm}.c{border:1.5px solid #333;border-radius:5px;padding:4mm;break-inside:avoid}.h{display:flex;justify-content:space-between;font-weight:bold;margin-bottom:2mm}.n{font-size:24px}.g{display:grid;gap:1px}.cell{border:1px solid #777;text-align:center;padding:4px;font-weight:bold;font-size:16px}.blank{background:#ddd;color:transparent}.owner{font-size:10px}</style></head><body><div class="page">${group.map(c=>{const cols=gridCols(c),name=ownerOf(c.globalNumber);return `<section class="c"><div class="h"><span>${esc(event?.title||'EVENTO')}<small class="owner"><br>${esc(name)}</small></span><span>CARTÓN <b class="n">${pad(c.globalNumber)}</b></span></div><div class="g" style="grid-template-columns:repeat(${cols},1fr)">${(c.grid||[]).flat().map(v=>Number.isFinite(v)?`<div class="cell">${v}</div>`:'<div class="cell blank">.</div>').join('')}</div></section>`}).join('')}</div><script>setTimeout(()=>print(),250)<\/script></body></html>`);win.document.close()}
function safeFile(v){return String(v||'EVENTO').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/gi,'_').replace(/^_|_$/g,'').slice(0,40)||'EVENTO'}
function backup(){if(!lot)return toast('No hay lote para respaldar.');const data={version:1,createdAt:new Date().toISOString(),event:{title:event?.title||'',mode:event?.mode||lot.mode,lotCode:event?.lotCode||lot.code},assignments,lot};const a=document.createElement('a');a.download=`RESPALDO_${safeFile(event?.title)}_${event?.lotCode||lot.code||'LOTE'}.json`;a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000)}
function decodeEmbeddedLot(t){const b=t.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-t.length%4)%4),bin=atob(b),bytes=Uint8Array.from(bin,ch=>ch.charCodeAt(0));return JSON.parse(new TextDecoder().decode(bytes))}
async function loadPdf(file){try{const raw=new TextDecoder('latin1').decode(await file.arrayBuffer()),m=raw.match(/LA_GORDA_CARD_LOT_V1\n([A-Za-z0-9_-]+)\nLA_GORDA_CARD_LOT_END/);if(m){lot=decodeEmbeddedLot(m[1]);cards=flattenLot(lot);if(!cards.length)throw new Error('El PDF no contiene cartones.');loadAssignments();selectedCard=cards[0];renderAll();toast(`${cards.length} cartones recuperados del PDF en este navegador.`);return}const legacy=raw.match(/Lote\s+(LG-[A-Z0-9]{6})/i)?.[1];if(legacy){await loadLot(legacy);renderAll();toast('Lote recuperado.');return}throw new Error('El PDF no es compatible con los cartones de La Gorda.')}catch(e){toast(e.message)}finally{$('pdfFile').value=''}}
function renderSponsorEditors(){const h=$('sponsorGrid');if(!h)return;h.innerHTML=[1,2,3].map(i=>`<div class="sponsor"><label><input id="sp${i}Enabled" type="checkbox"> SPONSOR ${i}</label><div id="sp${i}Thumb" class="thumb" style="margin:7px 0">SIN IMAGEN</div><input id="sp${i}Label" placeholder="Nombre" style="width:100%;background:#0c0910;color:#fff;border:1px solid var(--line);border-radius:8px;padding:7px"><input id="sp${i}File" type="file" accept="image/jpeg,image/png,image/webp" style="width:100%;margin-top:6px"><button id="sp${i}Remove" type="button" style="width:100%;margin-top:6px">QUITAR</button></div>`).join('');[1,2,3].forEach(i=>{$(`sp${i}File`).onchange=async()=>{const f=$(`sp${i}File`).files?.[0];if(!f)return;sponsorPending[i]=await imageData(f,1200,500,'contain');$(`sp${i}Thumb`).innerHTML=`<img src="${sponsorPending[i]}" alt="">`;renderPreview()};$(`sp${i}Remove`).onclick=()=>removeSponsor(i)})}
function renderSponsors(){const list=event?.sponsors||[];[1,2,3].forEach(i=>{const s=list.find(x=>Number(x.slot)===i)||{};$(`sp${i}Enabled`).checked=Boolean(s.enabled);$(`sp${i}Label`).value=s.label||'';if(!sponsorPending[i])$(`sp${i}Thumb`).innerHTML=s.imageUrl?`<img src="${esc(s.imageUrl)}" alt="">`:'SIN IMAGEN'});startSponsorRotation();renderPreview()}
async function saveSponsors(){if(!event)return toast('Primero guardá el evento.');try{for(const i of [1,2,3])if(sponsorPending[i]){community=await req('/api/admin/community/event/banner',{method:'POST',body:JSON.stringify({action:'upload',slot:i,imageData:sponsorPending[i]})});delete sponsorPending[i]}community=await req('/api/admin/community/event',{method:'POST',body:JSON.stringify({action:'save-sponsors',sponsors:[1,2,3].map(i=>({slot:i,enabled:$(`sp${i}Enabled`).checked,label:$(`sp${i}Label`).value.trim()}))})});event=community.event;await saveSponsorPosition(true);renderSponsors();toast('Sponsors guardados.')}catch(e){toast(e.message)}}
async function removeSponsor(i){if(sponsorPending[i]){delete sponsorPending[i];renderSponsors();return}if(!event)return;try{community=await req('/api/admin/community/event/banner',{method:'POST',body:JSON.stringify({action:'remove',slot:i})});event=community.event;renderSponsors();toast('Imagen quitada.')}catch(e){toast(e.message)}}
async function saveSponsorPosition(silent=false){if(!event)return;const requested=$('sponsorPosition').value,position=requested==='side'?'bottom':requested;const d=event.design||{};community=await req('/api/admin/community/event',{method:'POST',body:JSON.stringify({action:'save-design',design:{primaryColor:d.primaryColor||'#9b159f',secondaryColor:d.secondaryColor||'#180b24',accentColor:d.accentColor||'#f2c95d',textColor:d.textColor||'#fff4d2',backgroundMode:d.backgroundMode||'premium',ballStyle:d.ballStyle||'premium',marqueeStyle:d.marqueeStyle||'premium',showLogo:true,showTitle:true,sponsorPosition:position}})});event=community.event;if(!silent&&requested==='side')toast('En esta V1 la transmisión real usa sponsor abajo; lateral queda solo como vista previa.')}
function activeSponsors(){return [1,2,3].map(i=>{const saved=(event?.sponsors||[]).find(x=>Number(x.slot)===i)||{};return {slot:i,enabled:$(`sp${i}Enabled`)?.checked??saved.enabled,image:sponsorPending[i]||saved.imageUrl||'',label:$(`sp${i}Label`)?.value||saved.label||''}}).filter(x=>x.enabled&&x.image)}
function startSponsorRotation(){clearInterval(sponsorTimer);sponsorIndex=0;sponsorTimer=setInterval(()=>{sponsorIndex++;renderPreviewSponsor()},7000)}
function renderPreviewSponsor(){const list=activeSponsors(),h=$('pvSponsor');if(!h)return;if(!list.length){h.innerHTML='<span style="color:var(--muted)">SPONSOR</span>';return}const s=list[sponsorIndex%list.length];h.innerHTML=`<img src="${s.image}" alt="${esc(s.label||'Sponsor')}">`}
function renderPreviewBoard(mode,drawn){const h=$('pvBoard');if(!h)return;const max=Number(mode)===75?75:90,set=new Set(drawn||[]);h.innerHTML=Array.from({length:max},(_,i)=>`<div class="pvNum ${set.has(i+1)?'hit':''}">${i+1}</div>`).join('')}
function renderPreview(){const real=Boolean(adminState?.active&&adminState?.roomSettings?.eventMode),drawn=real?(adminState.game?.drawn||[]):test.drawn,mode=real?(adminState.game?.mode||event?.mode||90):(event?.mode||Number($('eventMode')?.value)||90),last=drawn.at(-1);$('pvTitle').textContent=$('eventTitle')?.value.trim()||event?.title||'EVENTO ESPECIAL';$('pvBall').textContent=last||'--';const logo=event?.design?.assets?.logo;if(logo?.hasAsset&&logo.url){$('pvLogo').src=logo.url;$('pvLogo').classList.remove('hidden')}else $('pvLogo').classList.add('hidden');const pos=$('sponsorPosition')?.value||event?.design?.sponsorPosition||'bottom';$('preview').className=`preview pos-${pos}`;renderPreviewBoard(mode,drawn);renderPreviewSponsor();renderCard()}
function resetTest(){stopTest();test={mode:$('drawMode').value,order:shuffle(Number($('eventMode').value)===75?75:90),drawn:[],paused:false,timer:null};renderTest();toast('Prueba reiniciada. No afecta el sorteo real.')}
function shuffle(max){const a=Array.from({length:max},(_,i)=>i+1);for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function testStart(){if(!test.order.length)resetTest();test.mode=$('drawMode').value;test.paused=false;if(test.mode==='automatic'){stopTest();test.timer=setInterval(testNext,Math.max(3,Number($('interval').value)||8)*1000)}renderTest()}
function stopTest(){if(test.timer)clearInterval(test.timer);test.timer=null}
function testNext(){if(test.paused)return;if(!test.order.length)resetTest();const n=test.order.find(x=>!test.drawn.includes(x));if(!n){stopTest();return}test.drawn.push(n);renderTest()}
function testPause(){test.paused=!test.paused;if(test.paused)stopTest();else if(test.mode==='automatic')testStart();renderTest()}
function renderTest(){$('recent').innerHTML=test.drawn.slice(-8).reverse().map(n=>`<i>${n}</i>`).join('');$('testPause').textContent=test.paused?'SEGUIR':'PAUSAR';renderPreview()}
async function prepareRoom(){if(!event?.lotReady)return toast('Primero generá el lote del evento.');try{community=await req('/api/admin/community/event',{method:'POST',body:JSON.stringify({action:'create-room'})});event=community.event;if(event.workspaceId)await req('/api/admin/workspace/select',{method:'POST',body:JSON.stringify({workspaceId:event.workspaceId})});await loadState();renderEventStatus();toast('Sala preparada. Todavía no empezó el sorteo.')}catch(e){toast(e.message)}}
async function startReal(){if(!adminState?.active)return toast('Primero prepará la sala.');try{await req('/api/admin/draw-settings',{method:'POST',body:JSON.stringify({drawMode:$('drawMode').value,autoSeconds:Number($('interval').value)||8})});adminState=await req('/api/admin/start',{method:'POST',body:JSON.stringify({force:true})});seenWins.clear();renderRealState();renderPreview();toast('Evento iniciado.')}catch(e){toast(e.message)}}
async function drawReal(){try{adminState=await req('/api/admin/draw',{method:'POST',body:JSON.stringify({source:'manual'})});renderRealState();renderPreview();detectWinners()}catch(e){toast(e.message)}}
async function pauseReal(){try{if(adminState?.status==='paused')adminState=await req('/api/admin/resume',{method:'POST',body:JSON.stringify({mode:adminState.game?.drawMode||'manual'})});else adminState=await req('/api/admin/pause',{method:'POST',body:'{}'});renderRealState()}catch(e){toast(e.message)}}
function renderRealState(){const h=$('realState');if(!h)return;const isEvent=Boolean(adminState?.active&&adminState?.roomSettings?.eventMode);if(!isEvent){h.innerHTML='Sala real todavía no preparada.';$('startReal').disabled=true;$('drawReal').disabled=true;$('pauseReal').disabled=true;$('openTx').disabled=true;return}const d=adminState.game?.drawn||[];h.innerHTML=`<b>${esc(adminState.roomSettings?.eventTitle||event?.title||'EVENTO')}</b><br>${String(adminState.status||'').toUpperCase()} · ${d.length}/${adminState.game?.mode||90} bolillas · ${adminState.game?.drawMode==='automatic'?'AUTOMÁTICO':'MANUAL'}`;$('startReal').disabled=adminState.status!=='waiting';$('drawReal').disabled=adminState.status!=='playing';$('pauseReal').disabled=!['playing','paused'].includes(adminState.status);$('openTx').disabled=!adminState.broadcastUrl}
function lineWins(card,drawn){const set=new Set(drawn);return (card.grid||[]).some(row=>{const rowNums=row.filter(Number.isFinite);return rowNums.length&&rowNums.every(n=>set.has(n))})}
function bingoWins(card,drawn){const set=new Set(drawn),n=nums(card);return n.length&&n.every(x=>set.has(x))}
function detectWinners(){const h=$('winnerAlerts');if(!h||!cards.length||!adminState?.roomSettings?.eventMode){if(h)h.innerHTML='';return}const drawn=adminState.game?.drawn||[],alerts=[];for(const c of cards){const name=ownerOf(c.globalNumber);if(!name)continue;for(const type of ['line','bingo']){const ok=type==='line'?lineWins(c,drawn):bingoWins(c,drawn);if(!ok)continue;const key=`${type}:${c.globalNumber}`;if(!seenWins.has(key)){seenWins.add(key);alerts.push({type,c,name})}}}if(!alerts.length)return;for(const a of alerts){const box=document.createElement('div');box.className='alert';box.innerHTML=`<b>${a.type==='line'?'LÍNEA':'BINGO'} DETECTADO</b> · Cartón ${pad(a.c.globalNumber)} · ${esc(a.name)} <div class="row" style="margin-top:6px"><button data-v>VER CARTÓN</button><button data-s class="gold">MOSTRAR EN TRANSMISIÓN</button><button data-g>VOLVER AL BOLILLERO</button></div>`;box.querySelector('[data-v]').onclick=()=>selectCard(a.c.globalNumber);box.querySelector('[data-s]').onclick=()=>setScene(a.type);box.querySelector('[data-g]').onclick=()=>setScene('game');h.prepend(box)}}
async function setScene(scene){try{community=await req('/api/admin/community/event',{method:'POST',body:JSON.stringify({action:'set-scene',scene})});event=community.event;toast(scene==='game'?'Bolillero en transmisión.':`${scene.toUpperCase()} en transmisión.`)}catch(e){toast(e.message)}}
function encodePayload(obj){const bytes=new TextEncoder().encode(JSON.stringify(obj));let bin='';bytes.forEach(b=>bin+=String.fromCharCode(b));return btoa(bin).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function playerLink(){if(!selectedCard)return;const name=ownerOf(selectedCard.globalNumber);if(!name)return toast('Asigná el cartón primero.');const list=cards.filter(c=>ownerOf(c.globalNumber).toLowerCase()===name.toLowerCase());const payload={v:1,title:event?.title||'EVENTO',name,mode:event?.mode||lot?.mode||90,cards:list.map(c=>({globalNumber:c.globalNumber,grid:c.grid,mode:c.mode})),broadcastUrl:adminState?.broadcastUrl||''};const url=`${location.origin}/assets/evento-jugar.html#${encodePayload(payload)}`;copyText(url);toast('Link del jugador copiado.')}
async function copyText(text){try{await navigator.clipboard.writeText(text)}catch{prompt('Copiá este enlace:',text)}}
async function imageData(file,maxW,maxH,fit='contain'){if(!file.type.startsWith('image/'))throw new Error('Elegí una imagen.');const url=URL.createObjectURL(file);try{const img=await new Promise((ok,no)=>{const i=new Image;i.onload=()=>ok(i);i.onerror=no;i.src=url});const scale=Math.min(maxW/img.naturalWidth,maxH/img.naturalHeight,1),w=Math.max(1,Math.round(img.naturalWidth*scale)),h=Math.max(1,Math.round(img.naturalHeight*scale)),canvas=document.createElement('canvas');canvas.width=fit==='contain'?maxW:w;canvas.height=fit==='contain'?maxH:h;const c=canvas.getContext('2d');if(fit==='contain'){c.fillStyle='#08050e';c.fillRect(0,0,canvas.width,canvas.height);c.drawImage(img,(canvas.width-w)/2,(canvas.height-h)/2,w,h)}else c.drawImage(img,0,0,w,h);return canvas.toDataURL('image/webp',.86)}finally{URL.revokeObjectURL(url)}}
function bind(){if($('loginBtn'))$('loginBtn').onclick=login;if($('password'))$('password').onkeydown=e=>e.key==='Enter'&&login();$('saveEvent').onclick=saveEvent;$('generateLot').onclick=generateLot;$('assignBtn').onclick=assign;$('nextCardBtn').onclick=nextFree;$('searchCard').oninput=renderAssignments;$('backupBtn').onclick=backup;$('saveSponsors').onclick=saveSponsors;$('sponsorPosition').onchange=()=>{renderPreview();saveSponsorPosition().catch(e=>toast(e.message))};$('eventTitle').oninput=renderPreview;$('eventMode').onchange=()=>{resetTest();renderPreview()};$('logoFile').onchange=()=>{if(event&&$('logoFile').files?.[0])uploadLogo($('logoFile').files[0]).then(()=>{renderAll();toast('Logo cargado.')}).catch(e=>toast(e.message))};$('previewReset').onclick=resetTest;$('testStart').onclick=testStart;$('testNext').onclick=testNext;$('testPause').onclick=testPause;$('drawMode').onchange=()=>{test.mode=$('drawMode').value};$('prepareRoom').onclick=prepareRoom;$('startReal').onclick=startReal;$('drawReal').onclick=drawReal;$('pauseReal').onclick=pauseReal;$('openTx').onclick=()=>adminState?.broadcastUrl&&window.open(adminState.broadcastUrl,'_blank','noopener');$('showCard').onclick=()=>selectCard(Number($('cardNumber').value));$('downloadCard').onclick=downloadCardPng;$('printSix').onclick=printSix;$('pdfFile').onchange=()=>loadPdf($('pdfFile').files?.[0]);$('playerLink').onclick=playerLink}
window.addEventListener('beforeunload',()=>{stopTest();clearInterval(pollTimer);clearInterval(sponsorTimer)});
init();
})();