(()=>{'use strict';
const $=id=>document.getElementById(id);let accessPayload=null,live=null,currentIndex=0,accessCode='',heartbeatTimer=null,es=null,pollTimer=null,working=false;
const cleanCode=value=>{const raw=String(value||'').toUpperCase().replace(/[^23456789ABCDEFGHJKLMNPQRSTUVWXYZ]/g,'').slice(0,8);return raw.length>4?raw.slice(0,4)+'-'+raw.slice(4):raw};const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const statusLabel=s=>({waiting:'ESPERANDO COMIENZO',starting:'COMENZANDO',playing:'JUGANDO',paused:'PAUSA',verifying:'VERIFICANDO RECLAMO',resuming:'REANUDANDO',finalizing:'CIERRE',finished:'EVENTO FINALIZADO'})[s]||String(s||'ESPERANDO').toUpperCase();
const ballLabel=(n,mode)=>!n?'—':Number(mode)===75?`${'BINGO'[Math.min(4,Math.floor((n-1)/15))]} ${n}`:String(n);
function applyBrand(event){document.documentElement.style.setProperty('--p',event?.colors?.primary||'#6D238C');document.documentElement.style.setProperty('--s',event?.colors?.secondary||'#D83A84');document.documentElement.style.setProperty('--a',event?.colors?.accent||'#E0A71A');$('eventLogo').src=event?.logoUrl||'/assets/logo.webp';$('eventName').textContent=event?.name||'El Bingo de la Gorda';$('eventDetails').textContent=[event?.tagline,event?.date,event?.location,event?.sponsor?`Presentado por ${event.sponsor}`:''].filter(Boolean).join(' · ')}
function baseCards(){return live?.cards?.length?live.cards:(accessPayload?.cards||[])}
function cardKey(card){return `${card.lotCode}:${Number(card.cardNumber)}`}
function gridCells(card){const cells=[];if(Number(card.mode)===75){'BINGO'.split('').forEach(v=>cells.push({v,c:'head',n:null}));for(const row of card.grid||[])for(const value of row)cells.push({v:value==='LIBRE'?'★':value,c:value==='LIBRE'?'free':'',n:Number.isFinite(Number(value))?Number(value):null})}else for(const row of card.grid||[])for(const value of row)cells.push({v:value,c:value==null?'empty':'',n:Number.isFinite(Number(value))?Number(value):null});return cells}
function renderGrid(card,target,interactive=false){const drawn=new Set(live?.room?.game?.drawn||[]),marks=new Set(card.marks||[]),manual=live?.live&&live?.player?.markingMode==='manual';target.style.gridTemplateColumns=Number(card.mode)===75?'repeat(5,1fr)':'repeat(9,1fr)';target.innerHTML=gridCells(card).map(cell=>{if(cell.n==null)return `<span class="${cell.c||''}">${cell.v==null?'':esc(cell.v)}</span>`;const classes=[cell.c||'',drawn.has(cell.n)?'drawn':'',marks.has(cell.n)?'marked':''].filter(Boolean).join(' ');if(interactive&&manual)return `<button type="button" class="${classes}" data-mark="${cell.n}" ${live?.room?.status!=='playing'||!drawn.has(cell.n)?'disabled':''}>${esc(cell.v)}</button>`;return `<span class="${classes}">${esc(cell.v)}</span>`}).join('');if(interactive&&manual)target.querySelectorAll('[data-mark]').forEach(btn=>btn.onclick=()=>toggleMark(card,Number(btn.dataset.mark),!marks.has(Number(btn.dataset.mark))))}
function renderMosaic(){const cards=baseCards();$('mosaic').innerHTML=cards.map((card,index)=>{const total=Number(card.totalNumbers)||((card.grid||[]).flat().filter(Number.isFinite).length),marked=Number(card.markedCount)||0,pct=total?Math.round(marked*100/total):0;return `<article class="mini" data-card="${index}"><div class="miniTop"><b>Cartón ${String(card.cardNumber).padStart(4,'0')}</b><span>${esc(card.lotCode)}</span></div><div class="progress"><i style="width:${pct}%"></i></div><div class="grid" id="miniGrid${index}"></div><div class="modeTag" style="margin-top:5px">${marked} de ${total||'—'} números salidos</div></article>`}).join('');cards.forEach((card,index)=>renderGrid(card,$(`miniGrid${index}`),false));$('mosaic').querySelectorAll('[data-card]').forEach(el=>el.onclick=()=>openViewer(Number(el.dataset.card)))}
function claimTypes(card){const r=card?.readiness||{},mode=Number(card?.mode),rules=live?.room?.game?.rules||{};const list=[];if(mode===90&&rules.ambocabeza)list.push(['ambo','AMBO CABEZA','amboEligible']);if(rules.line!==false)list.push(['line','LÍNEA','lineEligible']);if(mode===75&&rules.doubleLine)list.push(['doubleLine','DOBLE LÍNEA','doubleLineEligible']);if(mode===75&&rules.tripleLine)list.push(['tripleLine','TRIPLE LÍNEA','tripleLineEligible']);if(mode===75&&rules.corners)list.push(['corners','CUATRO ESQUINAS','cornersEligible']);if(rules.bingo!==false)list.push(['bingo','BINGO','bingoEligible']);return list}
function renderClaims(card){const auto=live?.room?.claimMode==='automatic_ties';$('claimHelp').textContent=auto?'Esta partida usa reclamo automático. El servidor detecta las jugadas válidas.':live?.room?.status==='playing'?'Los botones se habilitan cuando el cartón cumple la jugada.':'Los reclamos se habilitan durante la partida.';$('claimButtons').innerHTML=auto?'':claimTypes(card).map(([type,label,key])=>`<button class="btn primary" data-claim="${type}" ${!card.readiness?.[key]||working?'disabled':''}>RECLAMAR ${label}</button>`).join('');$('claimButtons').querySelectorAll('[data-claim]').forEach(btn=>btn.onclick=()=>claim(card,btn.dataset.claim))}
function openViewer(index){const cards=baseCards();if(!cards.length)return;currentIndex=(index+cards.length)%cards.length;const card=cards[currentIndex];$('viewerTitle').textContent=`Cartón ${String(card.cardNumber).padStart(4,'0')}`;$('viewerSub').textContent=`${card.lotCode} · Bingo ${card.mode}`;$('viewerIndex').textContent=`${currentIndex+1} de ${cards.length}`;renderGrid(card,$('viewerGrid'),true);renderClaims(card);$('prevCard').disabled=cards.length<2;$('nextCard').disabled=cards.length<2;$('viewer').classList.add('show')}
function closeViewer(){$('viewer').classList.remove('show')}
function renderLive(){const cards=baseCards(),room=live?.room||null;applyBrand(live?.event||accessPayload?.event);$('playerName').textContent=live?.player?`Hola, ${live.player.name}`:accessPayload?.player?`Hola, ${accessPayload.player.name}`:'Cartón reconocido';$('playerMessage').textContent=live?.message||accessPayload?.message||'';$('cardsTitle').textContent=(live?.player||accessPayload?.player)?'MIS CARTONES':'MI CARTÓN';$('cardsCount').textContent=`${cards.length} cartón${cards.length===1?'':'es'} · Bingo ${live?.event?.mode||accessPayload?.event?.mode||''}`;$('currentBall').textContent=ballLabel(room?.game?.lastBall,room?.game?.mode||live?.event?.mode);$('gameStatus').textContent=live?.live?statusLabel(room?.status):(live?.event?.completedAt||accessPayload?.event?.completedAt?'EVENTO FINALIZADO':'ESPERANDO SALA');$('markMode').textContent=live?.live?(live?.player?.markingMode==='automatic'?'Marcado automático':'Marcado manual'):(live?.event?.completedAt||accessPayload?.event?.completedAt?'Partida cerrada · cartones en consulta':'Todavía sin juego en vivo');$('recentBalls').innerHTML=(room?.game?.drawn||[]).slice(-10).reverse().map(n=>`<span>${esc(ballLabel(n,room?.game?.mode))}</span>`).join('')||'<span>—</span>';const pending=room?.pendingClaim,confirmed=room?.latestConfirmed,notice=$('claimNotice');if(pending){notice.classList.add('show');notice.innerHTML=`<b>VERIFICANDO ${esc(String(pending.type||'reclamo').toUpperCase())}</b><br>${esc(pending.playerName||'')} · Cartón ${esc(String(pending.cardNumber||''))}`}else if(confirmed){notice.classList.add('show');notice.innerHTML=`<b>${esc(confirmed.prizeLabel||String(confirmed.type||'PREMIO').toUpperCase())} CONFIRMADO</b><br>${esc(confirmed.playerName||'')} · Cartón ${esc(String(confirmed.cardNumber||''))}`}else notice.classList.remove('show');const fin=$('finalNotice');if(room?.status==='finished'){fin.classList.remove('hide');const own=(live?.ownClaims||[]).filter(c=>c.status==='confirmed');fin.innerHTML=own.length?`<b>EVENTO FINALIZADO</b><br>Tenés ${own.length} jugada${own.length===1?'':'s'} confirmada${own.length===1?'':'s'}.`:'<b>EVENTO FINALIZADO</b><br>Gracias por participar.'}else fin.classList.add('hide');renderMosaic();if($('viewer').classList.contains('show'))openViewer(Math.min(currentIndex,cards.length-1))}
async function json(url,opt={}){const r=await fetch(url,{...opt,headers:{...(opt.body?{'Content-Type':'application/json'}:{}),...(opt.headers||{})},cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'No se pudo completar la acción.');return d}
async function refreshLive(){if(!accessCode)return;try{live=await json('/api/event/player-state?codigo='+encodeURIComponent(accessCode));renderLive()}catch(e){$('playerMessage').textContent=e.message}}
function connectEvents(){try{es?.close();es=new EventSource(`/api/events?role=event&codigo=${encodeURIComponent(accessCode)}`);es.addEventListener('state',ev=>{try{live=JSON.parse(ev.data);renderLive()}catch{}});es.addEventListener('logout',()=>{es?.close();refreshLive()});es.onerror=()=>{es?.close();clearTimeout(pollTimer);pollTimer=setTimeout(()=>{refreshLive();connectEvents()},1800)}}catch{clearTimeout(pollTimer);pollTimer=setTimeout(refreshLive,1800)}}
async function toggleMark(card,number,marked){if(working)return;working=true;try{live=await json('/api/event/mark',{method:'POST',body:JSON.stringify({codigo:accessCode,lotCode:card.lotCode,cardNumber:card.cardNumber,number,marked})});renderLive()}catch(e){alert(e.message)}finally{working=false}}
async function claim(card,type){if(working)return;working=true;renderClaims(card);try{const d=await json('/api/event/claim',{method:'POST',body:JSON.stringify({codigo:accessCode,lotCode:card.lotCode,cardNumber:card.cardNumber,type})});live=d.state;renderLive()}catch(e){alert(e.message);await refreshLive()}finally{working=false;if($('viewer').classList.contains('show'))openViewer(currentIndex)}}
async function access(){const code=cleanCode($('code').value);$('code').value=code;if(code.length!==9){$('msg').className='msg err';$('msg').textContent='El código debe tener 8 caracteres.';return}$('go').disabled=true;$('msg').className='msg';$('msg').textContent='Buscando tus cartones…';try{accessPayload=await json('/api/event/access-info?codigo='+encodeURIComponent(code));accessCode=code;sessionStorage.setItem('bingoEventoAccessCode',code);$('accessScreen').classList.add('hide');$('app').classList.add('show');applyBrand(accessPayload.event);await refreshLive();const cards=baseCards(),idx=cards.findIndex(card=>card.lotCode===accessPayload.accessedCard?.lotCode&&Number(card.cardNumber)===Number(accessPayload.accessedCard?.cardNumber));currentIndex=Math.max(0,idx);startHeartbeat();connectEvents()}catch(e){$('msg').className='msg err';$('msg').textContent=e.message}finally{$('go').disabled=false}}
async function heartbeat(){if(!accessCode)return;try{await fetch('/api/event/heartbeat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({codigo:accessCode})})}catch{}}
function startHeartbeat(){clearInterval(heartbeatTimer);heartbeat();heartbeatTimer=setInterval(heartbeat,30000)}function reset(){clearInterval(heartbeatTimer);es?.close();accessPayload=null;live=null;accessCode='';sessionStorage.removeItem('bingoEventoAccessCode');$('app').classList.remove('show');$('accessScreen').classList.remove('hide');$('msg').className='msg';$('msg').textContent='Ingresá el código privado de cualquiera de tus cartones.';$('code').focus()}
const q=new URLSearchParams(location.search),saved=q.get('codigo')||sessionStorage.getItem('bingoEventoAccessCode')||'';$('code').value=cleanCode(saved);$('code').oninput=()=>{$('code').value=cleanCode($('code').value)};$('code').onkeydown=e=>{if(e.key==='Enter')access()};$('go').onclick=access;$('changeCode').onclick=reset;$('viewerClose').onclick=closeViewer;$('viewerAll').onclick=closeViewer;$('prevCard').onclick=()=>openViewer(currentIndex-1);$('nextCard').onclick=()=>openViewer(currentIndex+1);$('viewer').onclick=e=>{if(e.target===$('viewer'))closeViewer()};if($('code').value.length===9)access();
})();