(()=>{'use strict';
const $=id=>document.getElementById(id),q=new URLSearchParams(location.search),eventCode=q.get('evento')||'',token=q.get('token')||'',voice=window.BingoVoice?.create({enabled:true,volume:1,gapMs:130});let lastBall=null,lastClaim='',finalPlayed=false,lastOk=0;
function label(n,mode){if(!n)return '—';if(Number(mode)!==75)return String(n);return `${'BINGO'[Math.min(4,Math.floor((n-1)/15))]} ${n}`}
function status(s){return ({waiting:'ESPERANDO COMIENZO',starting:'COMENZANDO',playing:'JUGANDO',paused:'PAUSA',verifying:'VERIFICANDO',resuming:'REANUDANDO',finalizing:'CIERRE',finished:'EVENTO FINALIZADO'})[s]||String(s||'SIN SEÑAL').toUpperCase()}
function overlay(kind,who='',card=''){const o=$('overlay');if(!kind){o.classList.remove('show');return}o.classList.add('show');$('overlayBig').textContent=kind;$('overlayWho').textContent=who;$('overlayCard').textContent=card?`Cartón ${card}`:''}
function apply(d){const e=d.event||{},r=d.room||{};document.documentElement.style.setProperty('--p',e.colors?.primary||'#6d238c');document.documentElement.style.setProperty('--s',e.colors?.secondary||'#d83a84');document.documentElement.style.setProperty('--a',e.colors?.accent||'#e0a71a');$('logo').src=e.logoUrl||'/assets/logo.webp';$('name').textContent=e.name||'EVENTO PREMIUM';$('tag').textContent=e.tagline||`Bingo ${e.mode||''}`;$('location').textContent=[e.date,e.location].filter(Boolean).join(' · ');$('sponsor').textContent=e.sponsor?`Presentado por ${e.sponsor}`:'';$('status').textContent=d.live?status(r.status):'EVENTO SIN VINCULAR';document.body.classList.toggle('offline',!d.live);const g=r.game||{},drawn=g.drawn||[],b=drawn.at(-1)||null;$('ball').textContent=label(b,g.mode||e.mode);$('ballSub').textContent=b?`Bolilla ${drawn.length} de ${g.mode||e.mode}`:'Esperando la primera bolilla';$('recent').innerHTML=drawn.slice(-12).reverse().map(n=>`<span>${label(n,g.mode)}</span>`).join('')||'<span>—</span>';$('players').textContent=d.eventStats?.players??r.playersTotal??0;$('connected').textContent=d.eventStats?.connectedPlayers??r.playersConnected??0;$('cards').textContent=d.eventStats?.linkedCards??0;$('drawn').textContent=drawn.length;
if(b&&b!==lastBall){lastBall=b;voice?.playBall(b,g.mode||e.mode)}const pending=r.pendingClaim,confirmed=r.latestConfirmed;if(pending){const key=`p:${pending.type}:${pending.playerName}:${pending.cardNumber}`;overlay('VERIFICANDO RECLAMO',pending.playerName,pending.cardNumber);if(key!==lastClaim){lastClaim=key;voice?.playClaim(pending.type,{mode:g.mode,prizeNumber:pending.prizeNumber||1})}}else if(confirmed){const key=`c:${confirmed.type}:${confirmed.playerName}:${confirmed.cardNumber}:${confirmed.resolvedAt}`;overlay((confirmed.prizeLabel||confirmed.type||'PREMIO').toUpperCase()+' CONFIRMADO',confirmed.playerName,confirmed.cardNumber);if(key!==lastClaim){lastClaim=key;voice?.playConfirmed(confirmed.type,{mode:g.mode,prizeNumber:confirmed.prizeNumber||1})}}else if(r.status==='paused'){overlay('PAUSA')}else if(r.status==='starting'){overlay('COMENZAMOS')}else if(r.status==='finished'){overlay('EVENTO FINALIZADO');if(!finalPlayed){finalPlayed=true;voice?.playFinal({priority:true})}}else{overlay('');lastClaim=''}lastOk=Date.now()}
async function poll(){try{const r=await fetch(`/api/event/live-state?evento=${encodeURIComponent(eventCode)}&token=${encodeURIComponent(token)}`,{cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Sin señal');apply(d)}catch(e){$('status').textContent='SIN SEÑAL';document.body.classList.add('offline');if(Date.now()-lastOk>5000)overlay('ESPERANDO SEÑAL')}}
$('unlock').onclick=async()=>{const ok=await voice?.unlock();$('unlock').textContent=ok?'🔊 VOZ ACTIVA':'🔇 TOCÁ PARA ACTIVAR';if(ok)setTimeout(()=>$('unlock').style.opacity='.35',1200)};poll();setInterval(poll,900);
})();