(()=>{'use strict';
const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const labels={ambo:'AMBO CABEZA',line:'LÍNEA',doubleLine:'DOBLE LÍNEA',tripleLine:'TRIPLE LÍNEA',corners:'4 ESQUINAS',bingo:'BINGO'};
class PlayerAlpha{
 constructor(){this.state=null;this.es=null;this.cardIndex=0;this.lastChatId='';this.chatOpen=false;this.toastTimer=null;this.loading=true;this.retryTimer=null;this.working=new Set();}
 async init(){this.bind();this.renderLoading();await this.refresh(true);this.connectEvents();document.addEventListener('visibilitychange',()=>{if(!document.hidden)this.refresh(false)});window.addEventListener('online',()=>this.refresh(false));}
 bind(){
  $('chatFab').onclick=()=>this.openChat();$('minChat').onclick=()=>this.closeChat();
  $('chatForm').onsubmit=e=>{e.preventDefault();this.sendChat()};
  const emojis=['😀','😂','👏','👍','❤️','🔥','🎉','🍀','🎱','💰'],helper=window.BingoEmojiStickers;const stickers=(helper?.stickers||[]).slice(0,6);$('emojiRow').innerHTML=emojis.map(x=>`<button type="button" data-emoji="${x}">${x}</button>`).join('')+stickers.map(x=>`<button type="button" data-sticker="${esc(x.id)}" title="${esc(x.label)}">${esc(helper?.get?.(x.id)?.fallback||'✦')}</button>`).join('');document.querySelectorAll('[data-emoji]').forEach(b=>b.onclick=()=>{$('chatInput').value+=b.dataset.emoji;$('chatInput').focus()});document.querySelectorAll('[data-sticker]').forEach(b=>b.onclick=()=>this.sendSticker(b.dataset.sticker));
 }
 setNet(ok,text='EN LÍNEA'){const p=$('networkPill');p.textContent=text;p.classList.toggle('off',!ok)}
 toast(text){const el=$('toast');el.textContent=String(text||'');el.classList.add('show');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>el.classList.remove('show'),4200)}
 async req(url,opt={}){const r=await fetch(url,{cache:'no-store',headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});const d=await r.json().catch(()=>({}));if(r.status===401){location.replace('/jugador/salir');throw Error('Tu sesión terminó. Volvé a ingresar.')}if(!r.ok)throw Error(d.error||'No se pudo completar la acción.');return d}
 async refresh(first=false){try{const d=await this.req('/api/player/state',{method:'GET',headers:{}});this.loading=false;this.apply(d);this.setNet(true)}catch(e){this.setNet(false,'SIN CONEXIÓN');if(first)this.renderFatal(e.message);else this.toast(e.message);clearTimeout(this.retryTimer);this.retryTimer=setTimeout(()=>this.refresh(false),2500)}}
 connectEvents(){try{this.es?.close();this.es=new EventSource('/api/events?role=player');this.es.addEventListener('state',e=>{try{this.apply(JSON.parse(e.data));this.setNet(true)}catch{}});this.es.addEventListener('logout',()=>location.replace('/jugador/salir'));this.es.onopen=()=>this.setNet(true);this.es.onerror=()=>{this.setNet(false,'RECONECTANDO');clearTimeout(this.retryTimer);this.retryTimer=setTimeout(()=>this.refresh(false),1800)}}catch{this.setNet(false,'RECONECTANDO')}}
 apply(d){if(!d?.active){this.state=d;return this.renderClosed()}const old=this.state;this.state=d;const cards=d.player?.cards||[];if(this.cardIndex>=cards.length)this.cardIndex=0;$('playerMeta').textContent=`${d.player?.name||'Jugador'} · Sala ${d.roomCode||'—'}`;const hasPrize=(d.readiness||[]).some(r=>['amboEligible','lineEligible','doubleLineEligible','tripleLineEligible','cornersEligible','bingoEligible'].some(k=>r?.[k]));if(hasPrize&&this.chatOpen){this.closeChat();this.toast('¡TENÉS UN PREMIO PARA RECLAMAR!')}this.render();this.renderChat();if(old?.game?.lastBall!==d.game?.lastBall&&d.game?.lastBall!=null)this.toast(`Bolilla ${this.ballLabel(d.game.lastBall,d.game.mode)}`)}
 renderLoading(){this.loading=true;$('root').innerHTML=`<div class="stateHero"><img src="/assets/logo.png" alt=""><div class="spinner"></div><h1>Cargando sala…</h1><p>Estamos recuperando tu sesión privada. No cierres la página.</p></div>`}
 renderFatal(message){$('root').innerHTML=`<div class="stateHero"><img src="/assets/logo.png" alt=""><h1>No se pudo abrir la sala</h1><p>${esc(message||'No pudimos recuperar tu partida.')}</p><div class="actions"><button id="retryBtn" class="btn primary">REINTENTAR</button><a class="btn secondary" href="/jugador/salir" style="text-decoration:none">VOLVER A INGRESAR</a></div></div>`;$('retryBtn').onclick=()=>{this.renderLoading();this.refresh(true)}}
 renderClosed(){$('root').innerHTML=`<div class="stateHero"><img src="/assets/logo.png" alt=""><h1>Sala finalizada</h1><p>Esta partida ya no está activa.</p><div class="actions"><a class="btn primary" href="/jugador/salir" style="text-decoration:none">VOLVER AL INICIO</a></div></div>`;$('chatFab').classList.add('hidden');$('chatPanel').classList.add('hidden')}
 render(){const s=this.state,p=s.player;if(!s?.active)return this.renderClosed();$('chatFab').classList.toggle('hidden',s.chat?.enabled===false||this.chatOpen);if(['waiting','starting'].includes(s.status))return this.renderWaiting();if(['playing','paused','verifying','finalizing'].includes(s.status))return this.renderGame();if(s.status==='finished')return this.renderFinished();this.renderWaiting()}
 renderWaiting(){const s=this.state,p=s.player,paid=s.roomSettings?.paymentMode==='paid';if(p.excludedFromRound){$('root').innerHTML=`<div class="stateHero"><h1>Esta ronda ya inició</h1><p>Tu participación no estaba confirmada cuando comenzó el sorteo. No recibiste cartones en esta ronda.</p></div>`;return}
  if(paid&&p.paymentStatus!=='confirmed')return this.renderPayment();
  if(!p.selectionConfirmed)return this.renderSelection();
  const cards=p.cards||[];const manualOnly=s.roomSettings?.markingMode==='manual_only';$('root').innerHTML=`<div class="stateHero"><h1>Ya estás listo</h1><p>Tus ${cards.length} cartón${cards.length===1?'':'es'} ${cards.length===1?'está':'están'} confirmado${cards.length===1?'':'s'} y son exclusivamente tuyos.</p><div class="chosenList">${cards.map(c=>`<span class="chosen">Cartón ${esc(c.number)}</span>`).join('')}</div>${manualOnly?'<div class="notice" style="margin-top:12px"><b>MODO SOLO MANUAL</b><br>Esta partida se juega únicamente marcando a mano.</div>':`<div class="modeRow"><button id="manualBtn" class="modeBtn ${!p.autoMark?'active':''}">MANUAL</button><button id="autoBtn" class="modeBtn ${p.autoMark?'active':''}">AUTOMARCADO</button></div>`}<div class="actions"><button id="changeCards" class="btn secondary">CAMBIAR CARTONES</button></div><p style="margin-top:12px">Esperando que el administrador inicie el sorteo…</p></div>`;
  if(!manualOnly){$('manualBtn').onclick=()=>this.setAuto(false);$('autoBtn').onclick=()=>this.setAuto(true)}$('changeCards').onclick=()=>this.releaseSelection();}
 renderPayment(){const s=this.state,p=s.player,qty=Number(p.requestedCardCount||p.allowedCardCount||1),authorized=Number(p.allowedCardCount||qty),wa=String(s.roomSettings?.whatsapp||'').replace(/\D/g,'');const price=Number(s.roomSettings?.cardPrice||0);const text=`Hola, soy ${p.name}. Estoy en la sala ${s.roomCode}. Solicité ${qty} cartón${qty===1?'':'es'}.`;const href=wa?`https://wa.me/${wa}?text=${encodeURIComponent(text)}`:'';$('root').innerHTML=`<div class="stateHero"><h1>Esperando confirmación</h1><p>Solicitaste <b>${qty}</b> cartón${qty===1?'':'es'}. El administrador puede ajustar la cantidad según lo acordado por WhatsApp.</p><div class="statusCards"><div class="stat"><b>${qty}</b><small>SOLICITADOS</small></div><div class="stat"><b>${authorized}</b><small>CANTIDAD ACTUAL</small></div><div class="stat"><b>${price?`$${price.toLocaleString('es-AR')}`:'—'}</b><small>POR CARTÓN</small></div></div>${href?`<div class="actions"><a class="btn primary" href="${href}" target="_blank" rel="noopener" style="text-decoration:none">HABLAR / PAGAR POR WHATSAPP</a></div>`:''}<div class="notice" style="margin-top:13px">Podés ir a WhatsApp y volver. <b>Tu sesión privada queda guardada</b> y no perdés tu lugar.</div><p style="margin-top:12px">Cuando el administrador dé el OK, esta pantalla cambiará automáticamente para que elijas tus cartones.</p></div>`}
 renderSelection(){const s=this.state,p=s.player,offers=p.offeredCards||[],selected=new Set(p.reservedCardIds||[]),need=Number(p.allowedCardCount||1);$('root').innerHTML=`<div class="offerTop"><div><h2>Elegí tus cartones</h2><div style="color:var(--muted);font-size:11px;margin-top:3px">Elegí exactamente ${need}. Nadie más puede tomar un cartón que ya reservaste.</div></div><span class="counter">${selected.size} / ${need}</span></div><div class="offers">${offers.map(c=>this.offerMarkup(c,selected.has(c.id))).join('')||'<div class="notice warning">Actualizando cartones disponibles…</div>'}</div><div class="actions"><button id="renewOffers" class="btn secondary">RECARGAR CARTONES</button><button id="confirmCards" class="btn primary" ${selected.size===need?'':'disabled'}>CONFIRMAR ${need} CARTÓN${need===1?'':'ES'}</button></div>`;document.querySelectorAll('[data-offer]').forEach(b=>b.onclick=()=>this.toggleReserve(b.dataset.offer,!selected.has(b.dataset.offer)));$('renewOffers').onclick=()=>this.renewOffers();$('confirmCards').onclick=()=>this.confirmCards([...selected]);}
 offerMarkup(c,selected){return `<button type="button" class="offer ${selected?'selected':''}" data-offer="${esc(c.id)}"><header><b>Cartón ${esc(c.number)}</b><span>${selected?'✓ ELEGIDO':'TOCAR PARA ELEGIR'}</span></header>${this.gridMarkup(c,'miniGrid','miniCell')}</button>`}
 gridMarkup(card,gridClass='ticket',cellClass='cell',marks=new Set(),drawn=new Set(),interactive=false){const mode=Number(card?.mode)===75?75:90;return `<div class="${gridClass} m${mode}">${(card?.grid||[]).flat().map(v=>{if(v===null||v===undefined||v==='')return `<span class="${cellClass} blank">·</span>`;if(String(v).toUpperCase()==='LIBRE')return `<span class="${cellClass} free">LIBRE</span>`;const n=Number(v),classes=[cellClass];if(drawn.has(n))classes.push('drawn');if(marks.has(n))classes.push('marked');return interactive?`<button type="button" class="${classes.join(' ')}" data-mark-number="${n}" ${this.state?.player?.autoMark?'disabled':''}>${esc(v)}</button>`:`<span class="${classes.join(' ')}">${esc(v)}</span>`}).join('')}</div>`}
 async toggleReserve(cardId,reserve){if(this.working.has('reserve'))return;this.working.add('reserve');try{this.apply(await this.req('/api/player/reserve',{method:'POST',body:JSON.stringify({cardId,reserve})}))}catch(e){this.toast(e.message);await this.refresh(false)}finally{this.working.delete('reserve')}}
 async renewOffers(){try{this.apply(await this.req('/api/player/renew-offers',{method:'POST',body:'{}'}))}catch(e){this.toast(e.message)}}
 async confirmCards(ids){try{this.apply(await this.req('/api/player/choose',{method:'POST',body:JSON.stringify({cardIds:ids})}));this.toast('Cartones confirmados')}catch(e){this.toast(e.message);await this.refresh(false)}}
 async releaseSelection(){if(!confirm('¿Querés cambiar tus cartones? Los actuales volverán a quedar disponibles.'))return;try{this.apply(await this.req('/api/player/release',{method:'POST',body:'{}'}))}catch(e){this.toast(e.message)}}
 async setAuto(enabled){try{this.apply(await this.req('/api/player/automark',{method:'POST',body:JSON.stringify({enabled})}))}catch(e){this.toast(e.message)}}
 renderGame(){const s=this.state,p=s.player,cards=p.cards||[];if(!cards.length){$('root').innerHTML=`<div class="stateHero"><h1>Preparando tus cartones…</h1><p>El servidor está recuperando tu participación.</p></div>`;return}if(this.cardIndex>=cards.length)this.cardIndex=0;const card=cards[this.cardIndex],drawn=new Set((s.game?.drawn||[]).map(Number)),marks=new Set((p.marks?.[card.id]||[]).map(Number));const status=s.status==='playing'?'JUGANDO':s.status==='paused'?'PAUSADO':s.status==='verifying'?'VERIFICANDO PREMIO':s.status==='finalizing'?'CERRANDO PARTIDA':'PREPARANDO';$('root').innerHTML=`<div class="gameLayout"><section><div class="ballPanel"><div id="ball" class="ball">${this.ballLabel(s.game?.lastBall,s.game?.mode)}</div><div class="gameStatus">${status}</div><div class="gameStatusSub">${(s.game?.drawn||[]).length} de ${s.game?.mode||0} bolillas</div><div class="recent">${(s.game?.drawn||[]).slice(-6).reverse().map(n=>`<span>${esc(this.ballLabel(n,s.game.mode))}</span>`).join('')}</div></div><div class="ticketPanel"><div class="tabs">${cards.map((c,i)=>`<button type="button" data-tab="${i}" class="${i===this.cardIndex?'active':''}">Cartón ${esc(c.number)}</button>`).join('')}</div><div class="ticketHead"><b>Cartón ${esc(card.number)}</b><small>${p.autoMark?'AUTOMARCADO':'MARCADO MANUAL'}</small></div>${this.gridMarkup(card,'ticket','cell',marks,drawn,true)}${s.roomSettings?.markingMode==='manual_only'?'<div class="notice" style="margin-top:8px"><b>SOLO MANUAL</b> · máximo 2 cartones</div>':`<div class="modeRow"><button id="manualGame" class="modeBtn ${!p.autoMark?'active':''}">MANUAL</button><button id="autoGame" class="modeBtn ${p.autoMark?'active':''}">AUTOMARCADO</button></div>`}<div class="claims">${this.claimButtons(card)}</div></div></section><aside class="sideInfo"><div class="panel" style="margin:0"><h3>NÚMEROS SALIDOS</h3><div class="numbersGrid">${[...(s.game?.drawn||[])].sort((a,b)=>a-b).map(n=>`<span>${n}</span>`).join('')}</div></div><div class="panel" style="margin:0"><h3>PREMIOS CONFIRMADOS</h3><div class="claimHistory">${(s.publicClaims||[]).filter(x=>x.status==='confirmed').slice(-8).reverse().map(x=>`<div><b>${esc(x.prizeLabel||labels[x.type]||x.type)}</b><br>${esc(x.playerName)} · Cartón ${esc(x.cardNumber)}</div>`).join('')||'<div>Todavía no hay ganadores.</div>'}</div></div></aside></div>`;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{this.cardIndex=Number(b.dataset.tab)||0;this.renderGame()});document.querySelectorAll('[data-mark-number]').forEach(b=>b.onclick=()=>this.mark(card.id,Number(b.dataset.markNumber),!marks.has(Number(b.dataset.markNumber))));if($('manualGame'))$('manualGame').onclick=()=>this.setAuto(false);if($('autoGame'))$('autoGame').onclick=()=>this.setAuto(true);document.querySelectorAll('[data-claim]').forEach(b=>b.onclick=()=>this.claim(b.dataset.claim,card.id,b.dataset.label));}
 ballLabel(n,mode){if(n===null||n===undefined)return'—';const num=Number(n);return Number(mode)===75?`${'BINGO'[Math.min(4,Math.floor((num-1)/15))]} ${num}`:String(num)}
 claimButtons(card){const s=this.state,ps=s.prizeStatus||{},order=['ambo','corners','line','doubleLine','tripleLine','bingo'],ready=(s.readiness||[]).find(r=>r.cardId===card.id)||{};const key={ambo:'amboEligible',corners:'cornersEligible',line:'lineEligible',doubleLine:'doubleLineEligible',tripleLine:'tripleLineEligible',bingo:'bingoEligible'};return order.filter(type=>Number(ps[type]?.total||0)>0).map(type=>{const label=ps[type]?.nextLabel||labels[type]||type,closed=Boolean(ps[type]?.closed),can=['playing','verifying'].includes(s.status)&&!closed,isReady=Boolean(ready[key[type]]);return `<button type="button" class="claimBtn ${isReady?'ready':''}" data-claim="${type}" data-label="${esc(label)}" ${can?'':'disabled'}>${isReady?'¡RECLAMAR! ':''}${esc(label)}${closed?' · ENTREGADO':''}</button>`}).join('')}
 async mark(cardId,number,marked){if(this.state?.player?.autoMark)return;try{this.apply(await this.req('/api/player/mark',{method:'POST',body:JSON.stringify({cardId,number,marked})}))}catch(e){this.toast(e.message)}}
 async claim(type,cardId,label){if(!confirm(`¿Reclamar ${label||labels[type]||type} con este cartón?`))return;try{await this.req('/api/player/claim',{method:'POST',body:JSON.stringify({type,cardId})});this.toast('Reclamo enviado. El servidor lo está verificando.');await this.refresh(false)}catch(e){this.toast(e.message)}}
 renderFinished(){const s=this.state,p=s.player;$('root').innerHTML=`<div class="stateHero"><img src="/assets/logo.png" alt=""><h1>Partida finalizada</h1><p>Gracias por jugar, ${esc(p.name)}.</p><div class="chosenList">${(p.cards||[]).map(c=>`<span class="chosen">Cartón ${esc(c.number)}</span>`).join('')}</div><div class="actions"><a class="btn primary" href="/jugador/salir" style="text-decoration:none">SALIR</a></div></div>`}
 renderChat(){const s=this.state;if(!s?.active)return;const messages=s.chat?.messages||[];const host=$('chatMessages'),helper=window.BingoEmojiStickers;host.innerHTML=messages.length?messages.slice(-60).map(m=>`<div class="msg ${m.role==='admin'?'admin':''}"><b>${esc(m.name||'Jugador')}:</b> ${helper?helper.renderMessage(m):esc(m.text||'')}</div>`).join(''):'<div class="msg">Todavía no hay mensajes.</div>';const input=$('chatInput'),send=$('chatForm').querySelector('button');const blocked=s.chat?.locked||s.chat?.muted;input.disabled=send.disabled=Boolean(blocked);input.placeholder=s.chat?.muted?'Tu chat fue bloqueado por el administrador':s.chat?.locked?'El chat está pausado':'Escribí un mensaje…';const newest=messages.at(-1)?.id||'';if(!this.chatOpen&&newest&&newest!==this.lastChatId){const count=Math.min(99,messages.slice(-10).filter(m=>m.id!==this.lastChatId).length||1);$('chatCount').textContent=count;$('chatCount').classList.remove('hidden')}if(this.chatOpen){this.lastChatId=newest;$('chatCount').classList.add('hidden');queueMicrotask(()=>host.scrollTop=host.scrollHeight)}}
 openChat(){this.chatOpen=true;$('chatPanel').classList.remove('hidden');$('chatFab').classList.add('hidden');const messages=this.state?.chat?.messages||[];this.lastChatId=messages.at(-1)?.id||this.lastChatId;$('chatCount').classList.add('hidden');this.renderChat()}
 closeChat(){this.chatOpen=false;$('chatPanel').classList.add('hidden');if(this.state?.chat?.enabled!==false)$('chatFab').classList.remove('hidden')}
 async sendSticker(stickerId){try{await this.req('/api/player/chat',{method:'POST',body:JSON.stringify({stickerId})});await this.refresh(false)}catch(e){this.toast(e.message)}}
 async sendChat(){const input=$('chatInput'),text=input.value.trim();if(!text)return;try{await this.req('/api/player/chat',{method:'POST',body:JSON.stringify({text})});input.value='';await this.refresh(false)}catch(e){this.toast(e.message)}}
}
window.addEventListener('DOMContentLoaded',()=>new PlayerAlpha().init());
})();
