(()=>{'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const token=decodeURIComponent(location.pathname.split('/').filter(Boolean).at(-1)||'');
const Scripts=window.BingoPresenterScripts||{},VERO=Scripts.profiles?.vero||{name:'Vero',rate:1.02,pitch:1.16},phrases=Scripts.PhraseEngine?new Scripts.PhraseEngine():{ball:(_id,n)=>`Número ${n}`,event:()=>''};
let state=null,lastBall=null,hasInitialState=false,rotationIndex=0,rotationTimer=null,rotationSignature='',claimToastKey='',confirmedKey='',claimToastTimer=null,prizeTimer=null,bingoTimer=null,leaderToastTimer=null,hintTimer=null,lastStatus='';
let showcaseIndex=0,showcaseTimer=null,showcaseSignature='',closingVoiceTimer=null;
let wakeLock=null;
let previousCards=new Map(),cardMotion=new Map(),lastLeaderKey='';
let audioContext=null,audioUnlocked=false,speechUnlocked=false,soundEnabled=localStorage.getItem('lgBroadcastSound')!=='off',voiceEnabled=localStorage.getItem('lgBroadcastVoice')!=='off',theme=localStorage.getItem('bingo_theme')==='day'?'day':'night',voices=[];
const seenChatIds=new Set();
function label(type,number=1,mode=75){if(type==='bingo')return'BINGO';if(type==='ambo'||type==='ambocabeza')return'AMBO CABEZA';if(type==='corners')return'4 ESQUINAS';if(type==='doubleLine')return'DOBLE LÍNEA';if(type==='tripleLine')return'TRIPLE LÍNEA';if(type==='line'&&Number(mode)===90)return Number(number)===2?'SEGUNDA LÍNEA':'PRIMERA LÍNEA';return'LÍNEA'}
function ballLabel(n,mode){if(n==null)return'—';return Number(mode)===75?`${'BINGO'[Math.min(4,Math.floor((Number(n)-1)/15))]} ${n}`:String(n)}
function cardKey(item){return String(item.cardId||`${item.playerId||item.playerName}:${item.cardNumber}`)}
function publicName(name){return state?.roomSettings?.transmission?.showNames===false?'Jugador':String(name||'Jugador')}
function raceLabel(item){return String(item.racePrizeLabel||label(item.racePrizeType,item.racePrizeNumber,item.mode)).toUpperCase()}
function missingBadge(item){const missing=Number(item.raceMissing);const prize=raceLabel(item);if(missing===0)return[`${prize} LISTO`,'win'];if(missing===1)return[`A 1 PARA ${prize}`,'hot'];if(missing===2)return[`A 2 PARA ${prize}`,'hot'];if(Number.isFinite(missing)&&missing<10)return[`A ${missing} PARA ${prize}`,''];return['EN CARRERA','']}
function isConfirmedCard(item){const c=state?.latestConfirmed;return Boolean(c&&String(c.cardNumber)===String(item.cardNumber)&&String(c.playerName)===String(item.playerName))}
function showHint(text,ms=3800){clearTimeout(hintTimer);$('soundHint').textContent=text;$('soundHint').classList.add('show');if(ms>0)hintTimer=setTimeout(()=>$('soundHint').classList.remove('show'),ms)}
function updateSoundButton(){const btn=$('soundBtn');if(!btn)return;btn.textContent=soundEnabled?'🔊':'🔇';btn.classList.toggle('muted',!soundEnabled);btn.title=!soundEnabled?'Activar sonido':audioUnlocked?'Silenciar sonido':'Activar sonido de la transmisión';btn.setAttribute('aria-label',btn.title)}
function refreshVoices(){voices=window.speechSynthesis?window.speechSynthesis.getVoices():[]}
function preferredVoice(){const spanish=voices.filter(v=>/^es([-_]|$)/i.test(v.lang)||/spanish|español|espanol/i.test(v.name));return spanish.find(v=>/female|femen|mujer|sofia|paulina|paloma|ximena|laura|lucia|mar[ií]a|camila|valentina|monica|m[oó]nica|sabina/i.test(v.name))||spanish[0]||voices[0]}
function updateVoiceButton(){const btn=$('voiceBtn');if(!btn)return;btn.textContent=voiceEnabled?'🗣':'🤐';btn.classList.toggle('muted',!voiceEnabled);btn.title=!voiceEnabled?'Activar voz de Vero':speechUnlocked?'Silenciar voz de Vero':'Activar voz de Vero';btn.setAttribute('aria-label',btn.title)}
function applyTheme(){document.documentElement.dataset.theme=theme;const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.content=theme==='day'?'#edf2f8':'#090511';const btn=$('themeBtn');if(btn){btn.textContent=theme==='day'?'☀':'☾';btn.title=theme==='day'?'Cambiar a modo noche':'Cambiar a modo día';btn.setAttribute('aria-label',btn.title)}}
function toggleTheme(){theme=theme==='day'?'night':'day';localStorage.setItem('bingo_theme',theme);applyTheme()}
function unlockSpeech(){speechUnlocked=true;refreshVoices();return Boolean(window.speechSynthesis)}
function speak(text,priority=false){if(!voiceEnabled||!speechUnlocked||!window.speechSynthesis||!text)return;refreshVoices();const u=new SpeechSynthesisUtterance(text),voice=preferredVoice();if(voice){u.voice=voice;u.lang=voice.lang}else u.lang='es-AR';u.rate=VERO.rate||1.02;u.pitch=VERO.pitch||1.16;u.volume=.95;if(priority)window.speechSynthesis.cancel();window.speechSynthesis.speak(u)}
function speakBall(number){if(state?.bingoConfirmed||['finalizing','finished'].includes(state?.status))return;speak(phrases.ball('vero',number,state?.game?.drawn?.length||0,state?.game?.mode||90),false)}
function speakEvent(name,replacements={},priority=true){speak(phrases.event('vero',name,replacements),priority)}
function toggleVoice(){if(!voiceEnabled){voiceEnabled=true;localStorage.setItem('lgBroadcastVoice','on');unlockSpeech();speak(VERO.preview||'Hola, soy Vero. Voz activada.',true);showHint('Voz de Vero activada',1800)}else if(!speechUnlocked){unlockSpeech();speak(VERO.preview||'Hola, soy Vero. Voz activada.',true);showHint('Voz de Vero activada',1800)}else{voiceEnabled=false;localStorage.setItem('lgBroadcastVoice','off');if(window.speechSynthesis)window.speechSynthesis.cancel();showHint('Voz de Vero silenciada',1800)}updateVoiceButton()}
function ensureAudio(){if(!soundEnabled)return false;try{const Ctx=window.AudioContext||window.webkitAudioContext;if(!Ctx)return false;if(!audioContext)audioContext=new Ctx();if(audioContext.state==='suspended')audioContext.resume();audioUnlocked=true;$('soundHint').classList.remove('show');updateSoundButton();return true}catch{return false}}
function tone(freq,offset=0,duration=.09,gain=.035,type='sine'){if(!soundEnabled||!audioUnlocked||!audioContext)return;const start=audioContext.currentTime+offset,osc=audioContext.createOscillator(),amp=audioContext.createGain();osc.type=type;osc.frequency.setValueAtTime(freq,start);amp.gain.setValueAtTime(0.0001,start);amp.gain.exponentialRampToValueAtTime(Math.max(.001,gain),start+.012);amp.gain.exponentialRampToValueAtTime(.0001,start+duration);osc.connect(amp);amp.connect(audioContext.destination);osc.start(start);osc.stop(start+duration+.02)}
function playSound(kind){if(!soundEnabled||!audioUnlocked)return;if(kind==='ball'){tone(520,0,.07,.022,'triangle');tone(720,.055,.09,.025,'sine')}else if(kind==='leader'){tone(620,0,.08,.025,'sine');tone(830,.07,.13,.028,'sine')}else if(kind==='claim'){tone(380,0,.12,.035,'square');tone(520,.14,.14,.032,'square')}else if(kind==='prize'){tone(523,0,.16,.035);tone(659,.09,.18,.038);tone(784,.18,.24,.042)}else if(kind==='bingo'){[392,523,659,784,1047].forEach((f,i)=>tone(f,i*.115,.3,.045,i<2?'triangle':'sine'));tone(523,.64,.45,.03);tone(659,.64,.45,.03);tone(784,.64,.45,.035)}}
function toggleSound(){if(!soundEnabled){soundEnabled=true;localStorage.setItem('lgBroadcastSound','on');ensureAudio();playSound('leader');showHint('Sonido activado',1700)}else if(!audioUnlocked){ensureAudio();playSound('leader');showHint('Sonido activado',1700)}else{soundEnabled=false;localStorage.setItem('lgBroadcastSound','off');showHint('Sonido silenciado',1700)}updateSoundButton()}
function fullscreenElement(){return document.fullscreenElement||document.webkitFullscreenElement||null}

function setWakeStatus(kind,text){const el=$('wakeStatus');if(!el)return;el.dataset.state=kind||'';el.textContent=text||''}
async function requestWakeLock(){
  if(!state?.active){setWakeStatus('','');return}
  if(!('wakeLock'in navigator)){setWakeStatus('warn','⚠ Mantener pantalla: no disponible');return}
  if(document.visibilityState!=='visible'){setWakeStatus('wait','Pantalla en espera');return}
  if(wakeLock&&!wakeLock.released){setWakeStatus('ok','● Pantalla activa');return}
  try{
    wakeLock=await navigator.wakeLock.request('screen');setWakeStatus('ok','● Pantalla activa');
    wakeLock.addEventListener('release',()=>{wakeLock=null;if(state?.active){setWakeStatus('wait','Recuperando pantalla…');setTimeout(()=>requestWakeLock(),600)}});
  }catch{wakeLock=null;setWakeStatus('warn','⚠ Revisá ahorro de energía de la TV')}
}
async function releaseWakeLock(){try{if(wakeLock&&!wakeLock.released)await wakeLock.release()}catch{}wakeLock=null;if(!state?.active)setWakeStatus('','')}
function updateWakeLock(){if(state?.active&&document.visibilityState==='visible')requestWakeLock();else if(!state?.active)releaseWakeLock()}
function renderContingency(s){const host=$('contingencyBanner'),admin=s?.adminPresence;if(!host)return;if(!admin||admin.connected||['waiting','finished'].includes(s.status)){host.classList.remove('show');return}if(admin.autoVerificationActive)host.textContent='⚙ VERIFICACIÓN AUTOMÁTICA ACTIVA · El servidor valida los reclamos';else{const seconds=Math.max(0,Math.ceil((new Date(admin.activatesAt||0).getTime()-Date.now())/1000));host.textContent=`⚠ ADMINISTRADOR SIN CONEXIÓN · contingencia automática en ${seconds} s`}host.classList.add('show')}

async function castTransmission(){
  if(!state?.broadcastUrl){showHint('El enlace de esta transmisión todavía no está disponible',3000);return}
  if(soundEnabled&&!audioUnlocked)ensureAudio();
  try{
    if(!window.LaGordaCast?.castUrl)throw new Error('Chromecast no está disponible en este navegador.');
    await window.LaGordaCast.castUrl(state.broadcastUrl,state.castAppId);
    showHint('Elegí tu Chromecast o TV compatible',2600);
  }catch(error){showHint(error?.message||'No se pudo iniciar Chromecast',4200)}
}

async function toggleFullscreen(){try{if(fullscreenElement()){const exit=document.exitFullscreen||document.webkitExitFullscreen;if(exit)await exit.call(document)}else{const root=document.documentElement,request=root.requestFullscreen||root.webkitRequestFullscreen;if(!request){showHint('Pantalla completa no disponible en este navegador',3000);return}await request.call(root)}}catch{showHint('No se pudo activar pantalla completa',2500)}updateFullscreenButton()}
function updateFullscreenButton(){const btn=$('fullBtn');if(!btn)return;const active=Boolean(fullscreenElement());btn.textContent='⛶';btn.title=active?'Salir de pantalla completa':'Pantalla completa';btn.setAttribute('aria-label',btn.title)}
function fitBoards(){document.querySelectorAll('.boardWrap').forEach(wrap=>{const grid=wrap.querySelector('.grid');if(!grid)return;const ratio=grid.classList.contains('mode90')?3:1,w=wrap.clientWidth,h=wrap.clientHeight;if(!w||!h)return;const width=Math.max(1,Math.min(w,h*ratio)),height=Math.max(1,Math.min(h,width/ratio));grid.style.width=`${Math.floor(width)}px`;grid.style.height=`${Math.floor(height)}px`})}
function prepareRaceMotion(s){const cards=s.highlightedCards||[],next=new Map();cardMotion=new Map();cards.forEach((item,index)=>{const key=cardKey(item),old=previousCards.get(key),marked=new Set((item.marked||[]).map(Number)),newMarks=new Set();if(old)for(const number of marked)if(!old.marked.has(number))newMarks.add(number);cardMotion.set(key,{rankUp:Boolean(old&&index+1<old.rank),newMarks});next.set(key,{rank:index+1,marked})});const leader=cards[0],leaderKey=leader?cardKey(leader):'';if(hasInitialState&&!s.pendingClaim&&leaderKey&&lastLeaderKey&&leaderKey!==lastLeaderKey)showLeaderToast(leader);lastLeaderKey=leaderKey;previousCards=next}
function renderCard(item,tx){const mode=Number(item.mode),key=cardKey(item),motion=cardMotion.get(key)||{},marked=new Set((item.marked||[]).map(Number)),newMarks=motion.newMarks||new Set(),[badgeText,badgeClass]=missingBadge(item),confirmed=isConfirmedCard(item),playerName=tx.showNames===false?'Jugador destacado':esc(item.playerName);const cells=(item.grid||[]).flat().map(v=>{const num=Number(v),fresh=Number.isFinite(num)&&newMarks.has(num);return `<span class="cell ${v===null?'blank':v==='LIBRE'?'free':marked.has(num)?'marked':''} ${fresh?'newMark':''}">${v==='LIBRE'?'LIBRE':v??''}</span>`}).join('');const progress=tx.showProgress===false?'':`<div class="badges">${confirmed?'<span class="badge win">PREMIO CONFIRMADO</span>':`<span class="badge ${badgeClass}">${esc(badgeText)}</span>`}<span class="badge">Línea ${Number(item.lineMissing)||0} · Bingo ${Number(item.bingoMissing)||0}</span></div>`;return `<article class="featured ${Number(item.rank)===1?'leader':''} ${tx.showProgress!==false&&badgeClass==='hot'?'hot':''} ${motion.rankUp?'rankUp':''} ${confirmed?'confirmed':''}"><header class="cardHead"><div class="identity"><span class="rankPill">${Number(item.rank)||'·'}º</span><div class="identityText"><h3 class="player">${playerName}</h3><span class="cardNumber">Cartón ${esc(item.cardNumber)}</span></div></div>${progress}</header><div class="boardWrap"><div class="grid mode${mode}">${cells}</div></div></article>`}
function cardsPerPage(){const w=window.innerWidth,h=window.innerHeight,portrait=h>=w;if(w<=900&&portrait)return 1;if(w<=1050)return 2;if($('layout').classList.contains('noChat')&&w>=1280)return 4;return 3}
function visibleCards(cards,count){if(cards.length<=count)return cards;if(count<=1)return cards.slice(0,1);const fixed=cards.slice(0,count-1),pool=cards.slice(count-1);return [...fixed,pool[rotationIndex%pool.length]]}
function renderDots(total,count){const pool=Math.max(0,total-Math.max(0,count-1));if(total<=count||count<=1||pool<=1){$('rotationDots').innerHTML='';return}$('rotationDots').innerHTML=Array.from({length:pool},(_,i)=>`<i class="${i===rotationIndex%pool?'active':''}"></i>`).join('')}
function leaderSummary(item,tx){if(!item)return'Los más cerca de ganar';const who=tx.showNames===false?`Cartón ${item.cardNumber}`:`${item.playerName} · Cartón ${item.cardNumber}`,missing=Number(item.raceMissing);return `${who} · ${missing===0?`${raceLabel(item)} listo`:missing===1?`falta 1 para ${raceLabel(item)}`:`faltan ${missing} para ${raceLabel(item)}`}`}
function renderFeatured(){if(!state)return;const tx=state.roomSettings?.transmission||{},cards=state.highlightedCards||[];if(tx.showCards===false)return;const per=Math.max(1,Math.min(cardsPerPage(),Math.max(1,cards.length)));document.documentElement.style.setProperty('--cards-per-page',String(per));$('featuredCards').innerHTML=cards.length?visibleCards(cards,per).map(item=>renderCard(item,tx)).join(''):'<div class="empty emptyCard">La carrera aparecerá cuando haya jugadores con cartones activos.</div>';$('cardsSubtitle').textContent=cards.length?leaderSummary(cards[0],tx):'Los más cerca de ganar';renderDots(cards.length,per);fitBoards();requestAnimationFrame(fitBoards)}
function setupRotation(){if(!state)return;const tx=state.roomSettings?.transmission||{},cards=state.highlightedCards||[],per=cardsPerPage(),seconds=[15,20,30,60].includes(Number(tx.rotationSeconds))?Number(tx.rotationSeconds):30;const sig=`${tx.showCards!==false}:${seconds}:${cards.map(c=>`${c.cardId||c.cardNumber}:${c.rank}:${c.raceMissing}`).join(',')}:${per}`;if(sig===rotationSignature)return;rotationSignature=sig;clearInterval(rotationTimer);rotationTimer=null;rotationIndex=0;if(tx.showCards!==false&&per>1&&cards.length>per){const pool=cards.length-(per-1);rotationTimer=setInterval(()=>{rotationIndex=(rotationIndex+1)%pool;cardMotion=new Map();renderFeatured()},seconds*1000)}}
function showLeaderToast(item){clearTimeout(leaderToastTimer);const missing=Number(item.raceMissing),prize=raceLabel(item),name=publicName(item.playerName),progress=missing===0?`${prize} listo`:missing===1?`a 1 de ${prize}`:`a ${missing} de ${prize}`;$('leaderToastText').textContent=`${name} · Cartón ${item.cardNumber} · ${progress}`;$('leaderToast').classList.add('show');playSound('leader');if(!state?.roomSettings?.adminSimulation){if(state?.demo&&missing>0&&missing<=2)speakEvent('demoNear',{name,card:item.cardNumber,prize,missing},true);else if(missing===0)speakEvent('leaderReady',{name,card:item.cardNumber,prize},true);else if(missing===1)speakEvent('leaderOneAway',{name,card:item.cardNumber,prize},true);else speakEvent('leaderChange',{name,card:item.cardNumber,prize,missing},false)}leaderToastTimer=setTimeout(()=>$('leaderToast').classList.remove('show'),2600)}
function showClaimToast(claim){$('leaderToast').classList.remove('show');clearTimeout(leaderToastTimer);const key=`${claim.type}:${claim.playerName}:${claim.cardNumber}:${claim.createdAt||''}`;if(key===claimToastKey)return;claimToastKey=key;clearTimeout(claimToastTimer);const prize=label(claim.type,1,state?.game?.mode);$('claimToastTitle').textContent=`${prize} RECLAMADO`;$('claimToastText').textContent=`${publicName(claim.playerName)} · Cartón ${claim.cardNumber} · Verificando…`;$('claimToast').classList.add('show');playSound('claim');if(hasInitialState){if(state?.demo)speakEvent('demoClaim',{name:publicName(claim.playerName),prize},true);else{const event=({ambo:'claimAmbo',doubleLine:'claimDoubleLine',tripleLine:'claimTripleLine',corners:'claimCorners',bingo:'claimBingo'})[claim.type]||'claimLine';speakEvent(event,{},true)}}claimToastTimer=setTimeout(()=>$('claimToast').classList.remove('show'),3800)}
function hideClaimToast(){clearTimeout(claimToastTimer);$('claimToast').classList.remove('show')}
function showConfirmed(claim){const key=`${claim.type}:${claim.resolvedAt||''}`;if(key===confirmedKey)return;confirmedKey=key;hideClaimToast();clearTimeout(prizeTimer);clearTimeout(bingoTimer);clearTimeout(closingVoiceTimer);$('prizeBanner').classList.remove('show');$('bingoOverlay').classList.remove('show');const name=publicName(claim.playerName),genericPrize=label(claim.type,claim.prizeNumber,state?.game?.mode),replacements={name,card:claim.cardNumber||'',prize:genericPrize},event=({ambo:'amboConfirmed',doubleLine:'doubleLineConfirmed',tripleLine:'tripleLineConfirmed',corners:'cornersConfirmed',bingo:'bingoConfirmed'})[claim.type]||'lineConfirmed';if(claim.type==='bingo'){$('bingoWinner').textContent=name;$('bingoCardNo').textContent=`Cartón ${claim.cardNumber}`;$('bingoOverlay').classList.add('show');$('bingoOverlay').setAttribute('aria-hidden','false');playSound('bingo');if(window.speechSynthesis)window.speechSynthesis.cancel();if(hasInitialState){if(state?.roomSettings?.adminSimulation)speakEvent('bingoConfirmedGeneric',{prize:genericPrize},true);else if(state?.demo)speakEvent('demoWinner',{name,prize:genericPrize,card:claim.cardNumber||''},true);else speakEvent(event,replacements,true)}bingoTimer=setTimeout(()=>{$('bingoOverlay').classList.remove('show');$('bingoOverlay').setAttribute('aria-hidden','true')},5200);closingVoiceTimer=setTimeout(()=>{if(state?.status==='finalizing'&&state?.bingoConfirmed&&!state?.roomSettings?.adminSimulation)speakEvent('finalExtractionStart',{},false)},5300)}else{$('prizeBannerText').textContent=`${name} · Cartón ${claim.cardNumber}`;$('prizeBannerType').textContent=label(claim.type,claim.prizeNumber,state?.game?.mode);$('prizeBanner').classList.add('show');playSound('prize');if(hasInitialState){if(state?.roomSettings?.adminSimulation)speakEvent('prizeConfirmedGeneric',{prize:genericPrize},true);else if(state?.demo)speakEvent('demoWinner',{name,prize:genericPrize,card:claim.cardNumber||''},true);else speakEvent(event,replacements,true)}prizeTimer=setTimeout(()=>$('prizeBanner').classList.remove('show'),4200)}}
function renderFinalExtraction(s){const info=s.finalExtraction,active=s.status==='finalizing'&&info?.active,overlay=$('closingOverlay');overlay.classList.toggle('show',Boolean(active));overlay.setAttribute('aria-hidden',active?'false':'true');if(!active)return;const total=Number(info.total)||Number(s.game?.total)||90,drawn=Number(info.drawnCount)||s.game.drawn.length,remaining=Math.max(0,Number(info.remaining)||total-drawn),last=s.game?.lastBall;$('closingBall').textContent=ballLabel(last,s.game.mode);$('closingCount').textContent=`${drawn} de ${total} bolillas`;$('closingRemaining').textContent=remaining?`Faltan ${remaining}`:'Extracción completa';$('closingProgressBar').style.width=`${Math.max(0,Math.min(100,total?drawn/total*100:0))}%`;const waiting=info.leadInEndsAt&&Date.now()<new Date(info.leadInEndsAt).getTime();$('closingText').textContent=waiting?'Bingo confirmado. En instantes comienza la extracción de las bolillas faltantes para habilitar el acta oficial.':remaining?'Extrayendo las bolillas restantes. Este cierre completa el registro oficial de la partida.':'Extracción completa. Preparando el acta y los cartones ganadores…'}
function winnerBoard(item){const winning=new Set((item.winningNumbers||[]).map(Number)),cells=(item.grid||[]).flat().map(v=>{const n=Number(v),win=Number.isFinite(n)&&winning.has(n);return `<span class="winnerCell ${v===null?'blank':v==='LIBRE'?'free':''} ${win?'winning':''}">${v==='LIBRE'?'LIBRE':v??''}</span>`}).join('');return `<div class="winnerGrid mode${Number(item.mode)===75?75:90}">${cells}</div>`}
function renderWinnerSlide(){const winners=state?.finalShowcase||[],stage=$('winnerStage');if(!winners.length){stage.innerHTML='<div class="empty">Partida finalizada.</div>';$('showcaseDots').innerHTML='';return}showcaseIndex=((showcaseIndex%winners.length)+winners.length)%winners.length;const item=winners[showcaseIndex],name=state?.roomSettings?.transmission?.showNames===false?'Ganador/a':esc(item.playerName),plays=(item.prizes||[]).map(prize=>`<div class="winnerPlay"><b>${esc(prize.prizeLabel)}</b><span>${esc(prize.winningLineLabel||'Jugada confirmada')}</span></div>`).join('');stage.innerHTML=`<article class="winnerSlide animate"><section class="winnerInfo"><span class="winnerPrize">${esc(item.prizeSummary||'PREMIO CONFIRMADO')}</span><h3 class="winnerName">${name}</h3><div class="winnerCardNo">Cartón ${esc(item.cardNumber)}</div><div class="winnerPlays">${plays}</div></section><section class="winnerBoardBox">${winnerBoard(item)}</section></article>`;$('showcaseDots').innerHTML=winners.map((_,i)=>`<i class="${i===showcaseIndex?'active':''}"></i>`).join('');$('showcaseMeta').textContent=(winners.length>1?`Cartón ${showcaseIndex+1} de ${winners.length} · cada ganador permanece 10 segundos en pantalla · loop hasta cerrar la sala`:'Este cartón ganador permanecerá en pantalla hasta que se cierre la sala.')+(state?.integrity?.verified?' · ✓ Sorteo verificado':'')}
function setupFinalShowcase(s){const winners=s.finalShowcase||[],active=s.status==='finished'&&winners.length>0,overlay=$('winnersOverlay');overlay.classList.toggle('show',active);overlay.setAttribute('aria-hidden',active?'false':'true');if(!active){clearInterval(showcaseTimer);showcaseTimer=null;showcaseSignature='';showcaseIndex=0;return}const sig=winners.map(w=>`${w.cardId||w.cardNumber}:${(w.prizes||[]).map(p=>`${p.type}:${p.prizeNumber}`).join(',')}`).join('|');if(sig===showcaseSignature)return;showcaseSignature=sig;showcaseIndex=0;clearInterval(showcaseTimer);renderWinnerSlide();if(winners.length>1)showcaseTimer=setInterval(()=>{showcaseIndex=(showcaseIndex+1)%winners.length;renderWinnerSlide()},10000)}
function fitTransmissionChat(){const list=$('chatList');if(!list||list.clientHeight<=0)return;while(list.scrollHeight>list.clientHeight+1&&list.children.length>1)list.firstElementChild?.remove()}
function renderChat(s){const tx=s.roomSettings?.transmission||{},chatMessages=(s.chat?.messages||[]).slice(-40),stickers=window.BingoEmojiStickers,fresh=new Set(chatMessages.filter(m=>!seenChatIds.has(m.id)).map(m=>m.id));$('chatList').innerHTML=chatMessages.map(m=>{const isSticker=Boolean(stickers?.isStickerMessage(m)),body=stickers?stickers.renderMessage(m,{animate:fresh.has(m.id)}):esc(m.text||'');return `<article class="msg ${m.role==='admin'?'admin':''} ${isSticker?'stickerMessage':''}"><b>${esc(m.name)}</b><p>${body}</p></article>`}).join('')||'<div class="empty">Todavía no hay mensajes.</div>';chatMessages.forEach(m=>seenChatIds.add(m.id));$('layout').classList.toggle('noChat',tx.showChat===false);$('chatPanel').hidden=tx.showChat===false;if(tx.showChat!==false)requestAnimationFrame(fitTransmissionChat)}
function render(s){state=s;renderContingency(s);updateWakeLock();const castBtn=$('castBtn');if(castBtn){castBtn.title=s.castAppId?'Transmitir con Chromecast':'Chromecast: falta configurar CAST_APP_ID';castBtn.setAttribute('aria-label',castBtn.title)}if(!s.active){clearTimeout(closingVoiceTimer);clearInterval(showcaseTimer);$('closingOverlay').classList.remove('show');$('winnersOverlay').classList.remove('show');$('bingoOverlay').classList.remove('show');$('status').textContent='SALA CERRADA';$('liveDot').style.background='var(--danger)';return}prepareRaceMotion(s);const tx=s.roomSettings?.transmission||{},leader=(s.highlightedCards||[])[0];$('presenterPhoto').src='/assets/vero.png';$('presenterPhoto').alt='Vero';$('presenterName').textContent='Vero';$('roomInfo').textContent=`Sala ${s.roomCode} · ${s.game.mode} bolas · Vero en vivo`;const statusText=s.status==='playing'?'PARTIDA ACTIVA':s.status==='waiting'?'SALA DE ESPERA':s.status==='verifying'?'VERIFICANDO PREMIO':s.status==='paused'?'PARTIDA PAUSADA':s.status==='finalizing'?'CIERRE FINAL':s.status==='finished'?'PARTIDA FINALIZADA':'PREPARANDO';$('status').textContent=statusText;$('liveDot').style.background=['playing','verifying'].includes(s.status)?'var(--green)':'var(--gold)';if(hasInitialState&&lastStatus&&s.status!==lastStatus){if(s.status==='paused')speakEvent('pause',{},true);else if(s.status==='resuming')speakEvent('resume',{},true);else if(s.status==='finished'){clearTimeout(closingVoiceTimer);if(s.bingoConfirmed&&!s.roomSettings?.adminSimulation)speakEvent('finalExtractionDone',{},true);else speakEvent('gameFinished',{},true)}}lastStatus=s.status;const current=s.game.lastBall,isNewBall=hasInitialState&&current!==lastBall&&current!=null;$('ball').textContent=ballLabel(current,s.game.mode);if(current!==lastBall&&current!=null){lastBall=current;$('ball').classList.remove('pop');void $('ball').offsetWidth;$('ball').classList.add('pop');if(isNewBall&&!s.bingoConfirmed&&s.status!=='finalizing'&&s.status!=='finished'){playSound('ball');speakBall(current)}}$('count').textContent=`${s.game.drawn.length} de ${s.game.total} bolillas sorteadas`;$('recent').innerHTML=s.game.drawn.slice(-7).reverse().map((n,index)=>`<span class="${isNewBall&&index===0?'newBall':''}">${ballLabel(n,s.game.mode)}</span>`).join('');$('prizeNow').textContent=s.status==='finalizing'?'EXTRACCIÓN FINAL':s.pendingClaim?'RECLAMO EN VERIFICACIÓN':leader?`EN JUEGO · ${raceLabel(leader)}`:'PARTIDA EN VIVO';$('cardsShell').hidden=tx.showCards===false;$('mainPanel').classList.toggle('noCards',tx.showCards===false);renderChat(s);setupRotation();renderFeatured();if(s.pendingClaim)showClaimToast(s.pendingClaim);else hideClaimToast();if(s.latestConfirmed)showConfirmed(s.latestConfirmed);renderFinalExtraction(s);setupFinalShowcase(s);hasInitialState=true;setTimeout(()=>{cardMotion=new Map()},1000)}
async function refresh(){const r=await fetch(`/api/broadcast/state?token=${encodeURIComponent(token)}`,{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||'Transmisión no válida');render(d)}
function connect(){const es=new EventSource(`/api/events?role=broadcast&broadcastToken=${encodeURIComponent(token)}`);es.addEventListener('state',e=>render(JSON.parse(e.data)));es.addEventListener('chat',e=>{if(!state)return;const m=JSON.parse(e.data);state.chat||={messages:[]};state.chat.messages||=[];if(!state.chat.messages.some(x=>x.id===m.id))state.chat.messages.push(m);state.chat.messages=state.chat.messages.slice(-100);renderChat(state)});es.addEventListener('chat-control',e=>{if(!state)return;state.chat={...(state.chat||{}),...JSON.parse(e.data)};renderChat(state)});es.onerror=()=>setTimeout(()=>refresh().catch(()=>{}),1500)}
let resizeTimer=null;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{rotationSignature='';setupRotation();cardMotion=new Map();renderFeatured();fitTransmissionChat()},120)});document.addEventListener('fullscreenchange',updateFullscreenButton);document.addEventListener('webkitfullscreenchange',updateFullscreenButton);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')requestWakeLock();else setWakeStatus('wait','Pantalla en espera')});window.addEventListener('focus',requestWakeLock);window.addEventListener('pageshow',requestWakeLock);window.addEventListener('pagehide',releaseWakeLock);document.addEventListener('pointerdown',event=>{requestWakeLock();if(event.target!==$('soundBtn')&&event.target!==$('voiceBtn')){if(soundEnabled&&!audioUnlocked)ensureAudio();if(voiceEnabled&&!speechUnlocked)unlockSpeech()}},{passive:true});$('soundBtn').addEventListener('click',()=>{unlockSpeech();toggleSound()});$('voiceBtn').addEventListener('click',()=>{if(soundEnabled&&!audioUnlocked)ensureAudio();toggleVoice()});$('castBtn').addEventListener('click',castTransmission);$('themeBtn')?.addEventListener('click',toggleTheme);$('fullBtn').addEventListener('click',()=>{if(soundEnabled&&!audioUnlocked)ensureAudio();if(voiceEnabled&&!speechUnlocked)unlockSpeech();toggleFullscreen()});$('chatList').addEventListener('click',event=>window.BingoEmojiStickers?.replay(event.target));if(window.speechSynthesis){refreshVoices();window.speechSynthesis.onvoiceschanged=refreshVoices}applyTheme();updateSoundButton();updateVoiceButton();updateFullscreenButton();setTimeout(()=>{if((soundEnabled&&!audioUnlocked)||(voiceEnabled&&!speechUnlocked))showHint('Tocá 🔊, 🗣 o ⛶ para activar el audio',5200)},1100);
setInterval(()=>{if(state)renderContingency(state)},1000);setInterval(()=>{if(state?.active&&document.visibilityState==='visible')requestWakeLock()},15000);
refresh().then(connect).catch(e=>{$('status').textContent=e.message;$('liveDot').style.background='var(--danger)'});
})();
