(()=>{'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const parts=location.pathname.split('/').filter(Boolean),token=parts[0]==='tv'&&parts.length>1?decodeURIComponent(parts.at(-1)):'';
let state=null,lastBall=null,pendingRaw='',renderQueued=false,es=null,retryTimer=null,lastStateAt=0,voiceEnabled=localStorage.getItem('lgTvVoice')!=='off',voiceUnlocked=false,voices=[],tickerIndex=0,tickerTimer=null,tickerSig='',winnerIndex=0,winnerTimer=null,winnerSig='';
function label(type,n=1,mode=90){if(type==='bingo')return'BINGO';if(type==='ambo'||type==='ambocabeza')return'AMBO CABEZA';if(type==='corners')return'4 ESQUINAS';if(type==='doubleLine')return'DOBLE LÍNEA';if(type==='tripleLine')return'TRIPLE LÍNEA';if(type==='line'&&Number(mode)===90)return Number(n)===2?'SEGUNDA LÍNEA':'PRIMERA LÍNEA';return'LÍNEA'}
function letter(n){return'BINGO'[Math.min(4,Math.floor((Number(n)-1)/15))]}
function toneClass(n,mode){return Number(mode)===75&&n!=null?`bingo-${letter(n).toLowerCase()}`:''}
function ballText(n,mode){if(n==null)return'—';return Number(mode)===75?`${letter(n)} ${Number(n)}`:String(Number(n))}
function setBall(el,n,mode){if(!el)return;el.className=el.className.replace(/\sbingo-[bingo]/g,'').trim();const cls=toneClass(n,mode);if(cls)el.classList.add(cls);if(n==null){el.textContent='—';return}el.innerHTML=Number(mode)===75?`<small>${letter(n)}</small>${Number(n)}`:String(Number(n))}
function refreshVoices(){voices=window.speechSynthesis?window.speechSynthesis.getVoices():[]}
function preferredVoice(){const esv=voices.filter(v=>/^es([-_]|$)/i.test(v.lang)||/spanish|español|espanol/i.test(v.name));return esv[0]||voices[0]}
function updateVoice(){const b=$('voiceBtn');if(!b)return;if(!window.speechSynthesis){b.hidden=true;return}b.textContent=voiceEnabled?'🗣':'🤐';b.classList.toggle('muted',!voiceEnabled)}
function unlockVoice(){if(!window.speechSynthesis)return;voiceUnlocked=true;refreshVoices();updateVoice()}
function speakBall(n,mode){if(!voiceEnabled||!voiceUnlocked||!window.speechSynthesis||n==null)return;refreshVoices();const u=new SpeechSynthesisUtterance(Number(mode)===75?`${letter(n)}, ${Number(n)}`:String(Number(n))),v=preferredVoice();if(v){u.voice=v;u.lang=v.lang}else u.lang='es-AR';u.rate=1;u.pitch=1;window.speechSynthesis.cancel();window.speechSynthesis.speak(u)}
function setSync(kind,text){$('syncDot').className=`syncDot ${kind||''}`.trim();$('statusText').textContent=text}
function showEntry(error=''){$('entry').classList.remove('hidden');$('app').classList.add('hidden');$('entryError').textContent=error;setTimeout(()=>$('tvCode')?.focus(),50)}
function startApp(){$('entry').classList.add('hidden');$('app').classList.remove('hidden')}
function cardMarkup(item,compact=false){const marked=new Set((item.marked||[]).map(Number)),flat=(item.grid||[]).flat(),cells=flat.map(v=>{if(v===null||v===undefined||v==='')return'<span class="miniCell blank">·</span>';if(String(v).toUpperCase()==='LIBRE')return'<span class="miniCell free">★</span>';const n=Number(v);return`<span class="miniCell ${marked.has(n)?'marked':''}">${esc(v)}</span>`}).join('');return`<article class="raceCard ${compact?'compact':''} r${item.rank||''} rank${item.rank||''}"><div class="cardTop"><b>#${item.rank||''} ${esc(item.playerName||'Jugador')}</b><span>Cartón ${esc(item.cardNumber)}</span></div><div class="miniGrid m${Number(item.mode)===75?75:90}">${cells}</div><div class="cardFoot"><span>${esc(item.racePrizeLabel||'JUGADA')}</span><span class="missing">${Number(item.raceMissing)===1?'FALTA 1':`FALTAN ${Math.max(0,Number(item.raceMissing)||0)}`}</span></div></article>`}
function renderRace(s){const host=$('raceGrid'),mode=Number(s.game?.mode)===75?75:90,cards=(s.highlightedCards||[]).slice(0,6),sig=JSON.stringify(cards.map(c=>[c.cardId,c.rank,c.raceMissing,c.racePrizeType,c.cardNumber,c.playerName,c.marked]));if(host.dataset.sig===sig&&host.dataset.mode===String(mode))return;host.dataset.sig=sig;host.dataset.mode=String(mode);host.className=`raceGrid mode${mode}`;const slots=[];for(let i=0;i<6;i++){const c=cards[i];if(c)slots.push(cardMarkup(c,mode===75&&i>=3));else slots.push(`<div class="raceCard emptySlot ${mode===75&&i>=3?`compact r${i+1}`:''}">—</div>`)}host.innerHTML=slots.join('');$('raceHint').textContent=mode===75?'3 principales + puestos 4, 5 y 6':'Hasta 6 cartones más cerca de completar una jugada'}
function cleanText(text){return esc(String(text||'')).replace(/\n/g,' ')}
function renderChat(s){const host=$('chatList'),msgs=(s.chat?.messages||[]).slice(-7),sig=msgs.map(m=>`${m.id}:${m.text}`).join('|')+`:${s.chat?.enabled!==false}`;if(host.dataset.sig===sig)return;host.dataset.sig=sig;if(s.chat?.enabled===false){host.innerHTML='<div class="chatOff">Chat pausado.</div>';return}host.innerHTML=msgs.length?msgs.map(m=>`<article class="msg"><b>${esc(m.name)}</b><p>${cleanText(m.text)}</p></article>`).join(''):'<div class="chatOff">Todavía no hay mensajes.</div>'}
function tickerClaims(s){return(s.publicClaims||[]).filter(c=>c.status==='confirmed'&&c.type!=='bingo')}
function drawTicker(s){const claims=tickerClaims(s);if(!claims.length){$('prizeName').textContent='Aún no hay ganadores';$('prizeWinner').textContent='Esperando validaciones…';$('prizeMeta').textContent='';$('prizeCounter').textContent='';return}tickerIndex=((tickerIndex%claims.length)+claims.length)%claims.length;const c=claims[tickerIndex];$('prizeName').textContent=label(c.type,c.prizeNumber,s.game?.mode);$('prizeWinner').textContent=s.roomSettings?.transmission?.showNames===false?'Ganador/a':String(c.playerName||'Jugador');$('prizeMeta').textContent=`Cartón ${c.cardNumber||''}`;$('prizeCounter').textContent=claims.length>1?`${tickerIndex+1} de ${claims.length}`:''}
function renderTicker(s){const claims=tickerClaims(s),sig=claims.map(c=>`${c.id}:${c.type}:${c.prizeNumber}:${c.playerName}:${c.cardNumber}`).join('|');if(sig!==tickerSig){tickerSig=sig;tickerIndex=0;clearInterval(tickerTimer);tickerTimer=null;if(claims.length>1)tickerTimer=setInterval(()=>{tickerIndex=(tickerIndex+1)%Math.max(1,tickerClaims(state).length);drawTicker(state)},6000)}drawTicker(s)}
function winnerGrid(item){const wins=new Set((item.winningNumbers||[]).map(Number));return`<div class="winnerGrid m${Number(item.mode)===75?75:90}">${(item.grid||[]).flat().map(v=>{if(v===null)return'<span class="winnerCell blank">·</span>';if(String(v).toUpperCase()==='LIBRE')return'<span class="winnerCell free">★</span>';const n=Number(v);return`<span class="winnerCell ${wins.has(n)?'win':''}">${esc(v)}</span>`}).join('')}</div>`}
function drawWinner(s){const arr=s.finalShowcase||[];if(!arr.length)return;winnerIndex=((winnerIndex%arr.length)+arr.length)%arr.length;const w=arr[winnerIndex],name=s.roomSettings?.transmission?.showNames===false?'Ganador/a':esc(w.playerName),prizes=(w.prizes||[]).map(p=>`<span>${esc(p.prizeLabel||label(p.type,p.prizeNumber,w.mode))}</span>`).join('');$('winnerBox').innerHTML=`<div class="winnerInfo"><small>PARTIDA FINALIZADA · CARTÓN GANADOR</small><h2>${name}</h2><p>Cartón ${esc(w.cardNumber)}</p><div class="winnerPrizes">${prizes}</div></div><div class="winnerBoard">${winnerGrid(w)}</div>`}
function renderFinal(s){const final=s.status==='finished'&&(s.finalShowcase||[]).length>0;$('finalOverlay').classList.toggle('show',final);if(!final){clearInterval(winnerTimer);winnerTimer=null;winnerSig='';winnerIndex=0;return}const sig=(s.finalShowcase||[]).map(w=>`${w.cardId||w.cardNumber}:${(w.prizes||[]).map(p=>`${p.type}:${p.prizeNumber}`).join(',')}`).join('|');if(sig!==winnerSig){winnerSig=sig;winnerIndex=0;clearInterval(winnerTimer);winnerTimer=null;drawWinner(s);if((s.finalShowcase||[]).length>1)winnerTimer=setInterval(()=>{winnerIndex=(winnerIndex+1)%state.finalShowcase.length;drawWinner(state)},9000)}else drawWinner(s)}
function renderClosing(s){const info=s.finalExtraction,active=s.status==='finalizing'&&info?.active;$('closingOverlay').classList.toggle('show',Boolean(active));if(!active)return;const total=Number(info.total)||Number(s.game?.total)||90,drawn=Number(info.drawnCount)||s.game.drawn.length,remain=Math.max(0,Number(info.remaining)||total-drawn),last=s.game?.lastBall;$('closingBall').textContent=ballText(last,s.game.mode);$('closingStats').textContent=`${drawn} de ${total} · ${remain?`faltan ${remain}`:'completa'}`;$('closingText').textContent=remain?'Extrayendo las bolillas restantes para completar el acta oficial.':'Extracción completa. Preparando los resultados…';$('closingProgressBar').style.width=`${Math.max(0,Math.min(100,total?drawn/total*100:0))}%`}
function render(s){state=s;lastStateAt=Date.now();if(!s?.active){setSync('off','SALA CERRADA');return}startApp();$('roomInfo').textContent=`Sala ${s.roomCode} · ${s.game.mode} bolas · Modo TV`;$('eyebrow').textContent=s.status==='finalizing'?'EXTRACCIÓN FINAL':s.pendingClaim?'RECLAMO EN VERIFICACIÓN':'PARTIDA EN VIVO';const current=s.game.lastBall,newBall=current!=null&&current!==lastBall;setBall($('ball'),current,s.game.mode);$('count').textContent=`${s.game.drawn.length} de ${s.game.total} bolillas sorteadas`;$('recent').innerHTML=s.game.drawn.slice(-7).reverse().map(n=>`<span class="${toneClass(n,s.game.mode)}">${ballText(n,s.game.mode)}</span>`).join('');renderTicker(s);renderRace(s);renderChat(s);renderClosing(s);renderFinal(s);const status=s.status==='playing'?'EN VIVO':s.status==='paused'?'PAUSADO':s.status==='verifying'?'VERIFICANDO':s.status==='finalizing'?'CIERRE FINAL':s.status==='finished'?'FINALIZADA':'PREPARANDO';setSync(['playing','verifying'].includes(s.status)?'':'warn',status);if(newBall&&!s.bingoConfirmed&&!['finalizing','finished'].includes(s.status)){speakBall(current,s.game.mode)}lastBall=current}
function flushPending(){renderQueued=false;const raw=pendingRaw;pendingRaw='';if(!raw)return;try{render(JSON.parse(raw))}catch{}}
function queueRaw(raw){pendingRaw=raw;if(renderQueued)return;renderQueued=true;setTimeout(flushPending,45)}
async function refresh(){const r=await fetch(`/api/broadcast/state?token=${encodeURIComponent(token)}`,{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||'Código de TV no válido.');render(d)}
function connect(){if(es)try{es.close()}catch{};es=new EventSource(`/api/events?role=broadcast&broadcastToken=${encodeURIComponent(token)}`);es.addEventListener('state',e=>queueRaw(e.data));es.addEventListener('chat',()=>{});es.onerror=()=>{setSync('warn','RECONECTANDO…');clearTimeout(retryTimer);retryTimer=setTimeout(()=>refresh().catch(()=>{}),1200)}}
function fullscreen(){const el=document.fullscreenElement||document.webkitFullscreenElement;if(el){const fn=document.exitFullscreen||document.webkitExitFullscreen;if(fn)fn.call(document);return}const fn=document.documentElement.requestFullscreen||document.documentElement.webkitRequestFullscreen;if(fn)fn.call(document.documentElement).catch?.(()=>{})}
$('tvForm')?.addEventListener('submit',e=>{e.preventDefault();const code=$('tvCode').value.trim().replace(/\s+/g,'');if(!code){$('entryError').textContent='Ingresá el código de la sala.';return}location.href=`/tv/${encodeURIComponent(code)}`});
$('voiceBtn')?.addEventListener('click',()=>{if(!voiceUnlocked){unlockVoice();voiceEnabled=true}else voiceEnabled=!voiceEnabled;localStorage.setItem('lgTvVoice',voiceEnabled?'on':'off');updateVoice()});$('fullBtn')?.addEventListener('click',()=>{unlockVoice();fullscreen()});
if(window.speechSynthesis){refreshVoices();window.speechSynthesis.onvoiceschanged=refreshVoices}updateVoice();
if(!token){showEntry()}else{startApp();refresh().then(connect).catch(e=>showEntry(e.message))}
setInterval(()=>{if(token&&Date.now()-lastStateAt>8000)refresh().catch(()=>setSync('warn','RECONECTANDO…'))},5000);
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&token)refresh().catch(()=>{})});
})();
