(()=>{'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const parts=location.pathname.split('/').filter(Boolean),token=parts[0]==='tv'&&parts.length>1?decodeURIComponent(parts.at(-1)):'';
let state=null,lastBall=null,pendingRaw='',renderQueued=false,es=null,retryTimer=null,lastStateAt=0,voiceEnabled=localStorage.getItem('lgTvVoice')!=='off',voiceUnlocked=false,voice=window.BingoVoice?.create({enabled:voiceEnabled})||null,lastStatus='',lastPendingKey='',lastConfirmedKey='',lastAutoPrizeAnnouncementKey='',tickerIndex=0,tickerTimer=null,tickerSig='',winnerIndex=0,winnerTimer=null,winnerSig='';
function label(type,n=1,mode=90){if(type==='bingo')return'BINGO';if(type==='ambo'||type==='ambocabeza')return'AMBO CABEZA';if(type==='corners')return'4 ESQUINAS';if(type==='doubleLine')return'DOBLE LÍNEA';if(type==='tripleLine')return'TRIPLE LÍNEA';if(type==='line'&&Number(mode)===90)return Number(n)===2?'SEGUNDA LÍNEA':'PRIMERA LÍNEA';return'LÍNEA'}
function letter(n){return'BINGO'[Math.min(4,Math.floor((Number(n)-1)/15))]}
function toneClass(n,mode){return Number(mode)===75&&n!=null?`bingo-${letter(n).toLowerCase()}`:''}
function ballText(n,mode){if(n==null)return'—';return Number(mode)===75?`${letter(n)} ${Number(n)}`:String(Number(n))}
function setBall(el,n,mode){if(!el)return;el.className=el.className.replace(/\sbingo-[bingo]/g,'').trim();const cls=toneClass(n,mode);if(cls)el.classList.add(cls);if(n==null){el.textContent='—';return}el.innerHTML=Number(mode)===75?`<small>${letter(n)}</small>${Number(n)}`:String(Number(n))}
function updateVoice(){const b=$('voiceBtn');if(!b)return;b.textContent=voiceEnabled?'🗣':'🤐';b.classList.toggle('muted',!voiceEnabled);b.classList.toggle('active',voiceEnabled&&voiceUnlocked);b.title=!voiceEnabled?'Activar voz de La Gorda':voiceUnlocked?'Silenciar voz de La Gorda':'Tocá para activar la voz de La Gorda'}
async function unlockVoice(){if(!voiceEnabled||!voice)return false;voice.setEnabled(true);voiceUnlocked=await voice.unlock();updateVoice();return voiceUnlocked}
function speakBall(n,mode){if(!voiceEnabled||!voiceUnlocked||n==null)return;voice?.playBall?.(Number(n),Number(mode),{priority:true})}
function speakStatus(s){if(!voiceEnabled||!voiceUnlocked)return;const autoPrize=Boolean(s.prizeAnnouncement),pending=s.pendingClaim,pendingKey=pending?`${pending.type}:${pending.playerName}:${pending.cardNumber}:${pending.createdAt||''}`:'',confirmed=s.latestConfirmed,confirmedKey=confirmed?`${confirmed.type}:${confirmed.playerName}:${confirmed.cardNumber}:${confirmed.resolvedAt||''}`:'',newConfirmed=Boolean(confirmedKey&&confirmedKey!==lastConfirmedKey&&!confirmed.automatic&&!autoPrize);if(pendingKey&&pendingKey!==lastPendingKey){lastPendingKey=pendingKey;voice?.playClaim?.(pending.type,{mode:s.game?.mode,prizeNumber:pending.prizeNumber||1,playerName:pending.playerName,priority:true})}if(newConfirmed){lastConfirmedKey=confirmedKey;voice?.playConfirmed?.(confirmed.type,{mode:s.game?.mode,prizeNumber:confirmed.prizeNumber||1,playerName:confirmed.playerName,priority:true})}if(lastStatus&&s.status!==lastStatus){if(s.status==='paused'&&s.pauseReason!=='claim'&&s.pauseReason!=='automatic_prize')voice?.playEvent?.('partida_pausa',{priority:true});else if(s.status==='playing'&&['paused','resuming'].includes(lastStatus)&&!autoPrize)voice?.playEvent?.('partida_continuamos',{priority:true});else if(s.status==='finalizing'&&!autoPrize)voice?.playEvent?.('partida_ultima_etapa',{priority:!newConfirmed});else if(s.status==='finished')voice?.playFinal?.({priority:!newConfirmed})}lastStatus=s.status}
function setSync(kind,text){$('syncDot').className=`syncDot ${kind||''}`.trim();$('statusText').textContent=text}
function showEntry(error=''){$('entry').classList.remove('hidden');$('app').classList.add('hidden');$('entryError').textContent=error;setTimeout(()=>$('tvCode')?.focus(),50)}
function startApp(){$('entry').classList.add('hidden');$('app').classList.remove('hidden')}
function cardMarkup(item){const marked=new Set((item.marked||[]).map(Number)),missing=Math.max(0,Number(item.raceMissing)||0),hot=missing>=1&&missing<=5?new Set((item.raceHotNumbers||[]).map(Number)):new Set(),heat=missing>=1&&missing<=5?`heat${missing}`:'',flat=(item.grid||[]).flat(),cells=flat.map(v=>{if(v===null||v===undefined||v==='')return'<span class="miniCell blank">·</span>';if(String(v).toUpperCase()==='LIBRE')return'<span class="miniCell free">★</span>';const n=Number(v),cls=marked.has(n)?'marked':hot.has(n)?`hotTarget ${heat}`:'';return`<span class="miniCell ${cls}">${esc(v)}</span>`}).join(''),foot=item.antibingo?`<span>☠ ${esc(item.positionLabel||'CARTÓN')} · SOBREVIVE</span><span class="missing antibingoMissing">${missing===1?'⚠ 1 SIN MARCAR':`${missing} SIN MARCAR`}</span>`:item.flash?`<span>${item.flashWinner?'GANADOR FLASH':item.flashContender&&state?.flash?.suddenDeath?'FINALISTA':'PUNTOS FLASH'}</span><span class="missing">${Number(item.flashScore)||0} PTS</span>`:`<span>${esc(item.racePrizeLabel||'JUGADA')}</span><span class="missing">${missing===1?'🔥 FALTA 1':`FALTAN ${missing}`}</span>`;return`<article class="raceCard rank${item.rank||''} ${heat} ${item.antibingo?'antibingoRaceCard':''}"><div class="cardTop"><b>#${item.rank||''} ${esc(item.playerName||'Jugador')}</b><span>${item.antibingo?esc(item.positionLabel||''):''} · Cartón ${esc(item.cardNumber)}</span></div><div class="miniGrid m${Number(item.mode)===75?75:90}">${cells}</div><div class="cardFoot">${foot}</div></article>`}
function renderRace(s){const host=$('raceGrid'),mode=Number(s.game?.mode)===75?75:90,cards=(s.highlightedCards||[]).slice(0,6),sig=JSON.stringify(cards.map(c=>[c.cardId,c.rank,c.raceMissing,c.racePrizeType,c.cardNumber,c.playerName,c.marked,c.raceHotNumbers]));if(host.dataset.sig===sig&&host.dataset.mode===String(mode))return;host.dataset.sig=sig;host.dataset.mode=String(mode);host.className=`raceGrid mode${mode}`;const title=document.querySelector('.raceHead strong');if(title)title.textContent=s.antibingo?.enabled?'☠ SOBREVIVIENTES MÁS COMPROMETIDOS':'🔥 CARTONES MÁS CERCA';const slots=[];for(let i=0;i<6;i++){const c=cards[i];slots.push(c?cardMarkup(c):'<div class="raceCard emptySlot">—</div>')}host.innerHTML=slots.join('');$('raceHint').textContent=s.antibingo?.enabled?`${Math.max(0,Number(s.antibingo.aliveCount)||0)} CARTONES VIVOS · el último sobrevive`:s.flash?.enabled?(s.flash.suddenDeath?'Finalistas del desempate Flash':'Clasificación por aciertos en las primeras 10 bolas'):missingRaceHint(cards)}
function missingRaceHint(cards){const leader=cards?.[0];if(!leader)return'Hasta 6 cartones más cerca de completar una jugada';const m=Math.max(0,Number(leader.raceMissing)||0);return m>=1&&m<=5?`🔥 ${leader.playerName||'Líder'} está a ${m} de ${leader.racePrizeLabel||'la jugada'}`:'Hasta 6 cartones más cerca de completar una jugada'}
function cleanText(text){return esc(String(text||'')).replace(/\n/g,' ')}
function renderChat(s){const host=$('chatList'),msgs=(s.chat?.messages||[]).slice(-3),sig=msgs.map(m=>`${m.id}:${m.text}`).join('|')+`:${s.chat?.enabled!==false}`;if(host.dataset.sig===sig)return;host.dataset.sig=sig;if(s.chat?.enabled===false){host.innerHTML='<div class="chatOff">Chat pausado.</div>';return}host.innerHTML=msgs.length?msgs.map(m=>`<article class="msg"><b>${esc(m.name)}</b><p>${cleanText(m.text)}</p></article>`).join(''):'<div class="chatOff">Todavía no hay mensajes.</div>'}
function renderChampionshipHistory(s){const panel=$('racePanel'),host=$('championshipHistory'),champ=s?.championship;if(!panel||!host)return false;const active=Boolean(champ?.enabled);panel.classList.toggle('champHistoryActive',active);if(!active){host.innerHTML='';return false}const round=Number(champ.currentRound)||1,all=(champ.announcements||[]).filter(a=>(Number(a.round)||round)===round),seen=new Set(),rows=all.map((a,index)=>{const type=String(a.type||''),first=!seen.has(type);seen.add(type);return{...a,order:index+1,first}}),visible=rows.slice(-5),latestId=String(rows.at(-1)?.id||'');host.innerHTML=`<div class="champHistoryHead"><b>LOGROS · RONDA ${round}</b><span>${rows.length} registrado${rows.length===1?'':'s'}</span></div><div class="champHistoryList">${visible.length?visible.map(a=>{const type=a.type==='secondLine'?'line':a.type,num=a.type==='secondLine'?2:1;return`<div class="champHistoryRow ${a.first?'first':''} ${String(a.id||'')===latestId?'latest':''}"><span class="champHistoryOrder">${a.order}</span><div class="champHistoryText"><b>${esc(label(type,num,s.game?.mode))}${a.first?' · 1º':''}</b><small>${esc(a.playerName||'Jugador')} · ${esc(a.positionLabel||`C${Number(a.slot)||1}`)}</small></div><span class="champHistoryPts">+${Math.max(0,Number(a.points)||0)}</span></div>`}).join(''):'<div class="chatOff">Esperando el primer logro de la ronda…</div>'}</div>`;return true}
function renderTicker(s){renderChampionshipHistory(s);clearInterval(tickerTimer);tickerTimer=null;tickerSig=''}
function renderAutomaticPrizeAnnouncement(s){const a=s?.prizeAnnouncement,overlay=$('autoPrizeOverlay');if(!overlay)return false;if(s?.antibingo?.enabled){overlay.classList.remove('show');return false}if(!a||a.stage!=='showing'||!a.current){overlay.classList.remove('show');return false}const item=a.current,winners=Array.isArray(item.winners)?item.winners:[],key=`${a.id}:${a.currentIndex}:${a.stage}`,prize=String(item.prizeLabel||item.label||label(item.type,item.prizeNumber,s.game?.mode)).toUpperCase(),tie=winners.length>1,names=winners.map(w=>String(w.playerName||'Jugador')).join(' · '),cards=winners.map(w=>`Cartón ${w.cardNumber}`).join(' · ');$('autoPrizeType').textContent=`¡${prize}!`;$('autoPrizeWinner').textContent=tie?`EMPATE · ${winners.length} GANADORES`:item.type==='bingo'&&names?`GANÓ ${names}`:names||'GANADOR CONFIRMADO';$('autoPrizeNames').textContent=tie?names:cards;$('autoPrizeMeta').textContent=tie?cards:'';overlay.classList.toggle('show',!s?.championship?.enabled);if(key!==lastAutoPrizeAnnouncementKey){lastAutoPrizeAnnouncementKey=key;voice?.stop?.(true);voice?.playConfirmed?.(item.type,{mode:s.game?.mode,prizeNumber:item.prizeNumber||1,winnerNames:winners.map(w=>w.playerName).filter(Boolean),priority:true})}return true}
function renderPlayingFor(s){const el=$('playingFor');if(!el)return;if(s?.antibingo?.enabled)el.textContent=s.antibingo?.tieResolution?.stage==='resolving'?`🤝 EMPATE · RESOLVIENDO POR RESISTENCIA`:`☠ ANTIBINGO · ${Math.max(0,Number(s.antibingo.aliveCount)||0)} CARTONES VIVOS · ÚLTIMO SOBREVIVIENTE GANA`;else if(s?.flash?.enabled)el.textContent='SE JUEGA: FLASH · 10 BOLILLAS';else if(s?.championship?.enabled)el.textContent=`SE JUEGA: CAMPEONATO · RONDA ${Number(s.championship.currentRound)||1}/${Number(s.championship.totalRounds)||5}`;else{const prizes=(s.prizeLabels||[]).filter(Boolean);el.textContent=`SE JUEGA POR: ${prizes.length?prizes.join(' + '):'BINGO'}`}}
function renderClaimNotice(s){const host=$('claimNotice');if(!host)return;if(s?.antibingo?.enabled||s?.championship?.enabled||s?.prizeAnnouncement){host.classList.remove('show','confirmed');return}const p=s.pendingClaim,c=s.latestConfirmed;if(p){$('claimNoticeTitle').textContent=`VERIFICANDO ${label(p.type,p.prizeNumber||1,s.game?.mode)}`;$('claimNoticeText').textContent=`${p.playerName||'Jugador'} · Cartón ${p.cardNumber||'—'}`;host.classList.remove('confirmed');host.classList.add('show');return}if(c&&!c.automatic){const prize=label(c.type,c.prizeNumber||1,s.game?.mode);$('claimNoticeTitle').textContent=c.type==='bingo'?`¡${prize}!`:`${prize} CONFIRMADO`;$('claimNoticeText').textContent=c.type==='bingo'?`GANÓ ${c.playerName||'Jugador'} · Cartón ${c.cardNumber||'—'}`:`${c.playerName||'Jugador'} · Cartón ${c.cardNumber||'—'}`;host.classList.add('show','confirmed');return}host.classList.remove('show','confirmed')}

function winnerGrid(item){const wins=new Set((item.winningNumbers||[]).map(Number));return`<div class="winnerGrid m${Number(item.mode)===75?75:90}">${(item.grid||[]).flat().map(v=>{if(v===null)return'<span class="winnerCell blank">·</span>';if(String(v).toUpperCase()==='LIBRE')return'<span class="winnerCell free">★</span>';const n=Number(v);return`<span class="winnerCell ${wins.has(n)?'win':''}">${esc(v)}</span>`}).join('')}</div>`}
function drawWinner(s){const arr=s.finalShowcase||[];if(!arr.length)return;winnerIndex=((winnerIndex%arr.length)+arr.length)%arr.length;const w=arr[winnerIndex],name=s.roomSettings?.transmission?.showNames===false?'Ganador/a':esc(w.playerName),prizes=(w.prizes||[]).map(p=>`<span>${esc(p.prizeLabel||label(p.type,p.prizeNumber,w.mode))}</span>`).join('');$('winnerBox').innerHTML=`<div class="winnerInfo"><small>PARTIDA FINALIZADA · CARTÓN GANADOR</small><h2>${name}</h2><p>Cartón ${esc(w.cardNumber)}</p><div class="winnerPrizes">${prizes}</div><div class="winnerThanks">GRACIAS POR JUGAR AL BINGO DE LA GORDA</div></div><div class="winnerBoard">${winnerGrid(w)}</div>`}
function renderFinal(s){if(s?.antibingo?.enabled){const final=s.status==='finished'&&s.antibingo.finished,winners=s.antibingo.winners||[];$('finalOverlay').classList.toggle('show',Boolean(final));clearInterval(winnerTimer);winnerTimer=null;winnerSig='';winnerIndex=0;if(!final)return;const names=winners.map(w=>s.roomSettings?.transmission?.showNames===false?'Sobreviviente':esc(w.playerName||'Jugador')),rows=winners.map(w=>`<div class="antibingoTvWinner"><b>🏆 ${esc(w.positionLabel||'')}</b><span>${s.roomSettings?.transmission?.showNames===false?'Sobreviviente':esc(w.playerName||'Jugador')}</span><strong>Cartón ${esc(w.cardNumber)}</strong></div>`).join(''),resolution=s.antibingo.tieResolution?.occurred?s.antibingo.tieResolution:null;$('winnerBox').innerHTML=`<div class="winnerInfo antibingoTvFinal"><small>${resolution?'🤝 EMPATE RESUELTO · ANTIBINGO':'☠ ANTIBINGO FINALIZADO'}</small><h2>${resolution?'DESEMPATE POR RESISTENCIA':'ÚLTIMO SOBREVIVIENTE'}</h2><p>${names[0]||'Ganador definido'}${resolution?` · ${esc(resolution.criterionLabel||'Resistencia')}`:''}</p><div class="antibingoTvWinnerList">${rows}</div>${resolution?`<div class="winnerThanks">${esc(resolution.reason||'Empate resuelto por resistencia.')}</div>`:'<div class="winnerThanks">NO HAGAS BINGO · EL ÚLTIMO CARTÓN VIVO GANA</div>'}</div><div class="antibingoTvSkull">${resolution?'🤝':'☠'}<small>${Math.max(0,Number(s.antibingo.totalCards)||0)} CARTONES<br>${Math.max(0,Number(s.antibingo.eliminatedCount)||0)} ELIMINADOS</small></div>`;return}const final=s.status==='finished'&&(s.finalShowcase||[]).length>0;$('finalOverlay').classList.toggle('show',final);if(!final){clearInterval(winnerTimer);winnerTimer=null;winnerSig='';winnerIndex=0;return}const sig=(s.finalShowcase||[]).map(w=>`${w.cardId||w.cardNumber}:${(w.prizes||[]).map(p=>`${p.type}:${p.prizeNumber}`).join(',')}`).join('|');if(sig!==winnerSig){winnerSig=sig;winnerIndex=0;clearInterval(winnerTimer);winnerTimer=null;drawWinner(s);if((s.finalShowcase||[]).length>1)winnerTimer=setInterval(()=>{winnerIndex=(winnerIndex+1)%state.finalShowcase.length;drawWinner(state)},9000)}else drawWinner(s)}
function renderClosing(s){const info=s.finalExtraction,active=s.status==='finalizing'&&info?.active;$('closingOverlay').classList.toggle('show',Boolean(active));if(!active)return;const total=Number(info.total)||Number(s.game?.total)||90,drawn=Number(info.drawnCount)||s.game.drawn.length,remain=Math.max(0,Number(info.remaining)||total-drawn),last=s.game?.lastBall;$('closingBall').textContent=ballText(last,s.game.mode);$('closingStats').textContent=`${drawn} de ${total} · ${remain?`faltan ${remain}`:'completa'}`;$('closingText').textContent=remain?'Extrayendo las bolillas restantes para completar el acta oficial.':'Extracción completa. Preparando los resultados…';$('closingProgressBar').style.width=`${Math.max(0,Math.min(100,total?drawn/total*100:0))}%`}
function render(s){state=s;lastStateAt=Date.now();if(!s?.active){$('autoPrizeOverlay')?.classList.remove('show');$('claimNotice')?.classList.remove('show');setSync('off','SALA CERRADA');return}startApp();$('roomInfo').textContent=s?.antibingo?.enabled?`☠ Antibingo · Bingo ${s.game.mode} · ${Math.max(0,Number(s.antibingo.aliveCount)||0)} vivos`:s?.championship?.enabled?`${s.championship.inTiebreak?'⚔ Campeonato · DESEMPATE FINAL':`🏆 Campeonato · Ronda ${Number(s.championship.currentRound)||1}/${Number(s.championship.totalRounds)||5}`} · Bingo ${s.game.mode}`:s?.flash?.enabled?`⚡ Flash · Bingo ${s.game.mode} · ${s.flash.suddenDeath?'MUERTE SÚBITA':`${Math.min(10,Number(s.flash.drawnCount)||0)}/10`}`:`Sala ${s.roomCode} · ${s.game.mode} bolas · Modo TV`;$('eyebrow').textContent=s.status==='finalizing'?'EXTRACCIÓN FINAL':s.pauseReason==='automatic_prize'?'PREMIO DETECTADO':s.pendingClaim?'RECLAMO EN VERIFICACIÓN':s.status==='waiting'?'ESPERANDO INICIO':'PARTIDA EN VIVO';const current=s.game.lastBall,newBall=current!=null&&current!==lastBall,autoPrizeLead=Boolean(s.prizeAnnouncement&&s.prizeAnnouncement.stage==='lead_in');setBall($('ball'),current,s.game.mode);$('count').textContent=`${s.game.drawn.length} de ${s.game.total} bolillas sorteadas`;renderPlayingFor(s);$('recent').innerHTML=s.game.drawn.slice(-7).reverse().map(n=>`<span class="${toneClass(n,s.game.mode)}">${ballText(n,s.game.mode)}</span>`).join('');renderTicker(s);renderAutomaticPrizeAnnouncement(s);renderClaimNotice(s);renderRace(s);renderChat(s);renderClosing(s);renderFinal(s);const status=s.status==='playing'?'EN VIVO':s.pauseReason==='automatic_prize'?'PREMIO':s.status==='paused'?'PAUSADO':s.status==='verifying'?'VERIFICANDO':s.status==='finalizing'?'CIERRE FINAL':s.status==='finished'?'FINALIZADA':'PREPARANDO';setSync(['playing','verifying'].includes(s.status)?'':'warn',status);speakStatus(s);if(newBall&&(!s.bingoConfirmed||autoPrizeLead)&&!['finalizing','finished'].includes(s.status)){speakBall(current,s.game.mode)}lastBall=current}
function flushPending(){renderQueued=false;const raw=pendingRaw;pendingRaw='';if(!raw)return;try{render(JSON.parse(raw))}catch{}}
function queueRaw(raw){pendingRaw=raw;if(renderQueued)return;renderQueued=true;setTimeout(flushPending,45)}
async function refresh(){const r=await fetch(`/api/broadcast/state?token=${encodeURIComponent(token)}`,{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||'Código de TV no válido.');render(d)}
function connect(){if(es)try{es.close()}catch{};es=new EventSource(`/api/events?role=broadcast&broadcastToken=${encodeURIComponent(token)}`);es.addEventListener('state',e=>queueRaw(e.data));es.addEventListener('chat',()=>{});es.onerror=()=>{setSync('warn','RECONECTANDO…');clearTimeout(retryTimer);retryTimer=setTimeout(()=>refresh().catch(()=>{}),1200)}}
function fullscreen(){const el=document.fullscreenElement||document.webkitFullscreenElement;if(el){const fn=document.exitFullscreen||document.webkitExitFullscreen;if(fn)fn.call(document);return}const fn=document.documentElement.requestFullscreen||document.documentElement.webkitRequestFullscreen;if(fn)fn.call(document.documentElement).catch?.(()=>{})}
$('tvForm')?.addEventListener('submit',e=>{e.preventDefault();const code=$('tvCode').value.trim().replace(/\s+/g,'');if(!code){$('entryError').textContent='Ingresá el código de la sala.';return}location.href=`/tv/${encodeURIComponent(code)}`});
$('voiceBtn')?.addEventListener('click',async()=>{if(!voiceEnabled){voiceEnabled=true;voice?.setEnabled?.(true);localStorage.setItem('lgTvVoice','on');await unlockVoice();voice?.playEvent?.('inicio_bienvenida',{priority:true})}else if(!voiceUnlocked){await unlockVoice();if(voiceUnlocked)voice?.playEvent?.('inicio_bienvenida',{priority:true})}else{voiceEnabled=false;voiceUnlocked=false;voice?.setEnabled?.(false);localStorage.setItem('lgTvVoice','off')}updateVoice()});$('fullBtn')?.addEventListener('click',()=>{if(voiceEnabled)unlockVoice();fullscreen()});document.addEventListener('pointerdown',()=>{if(voiceEnabled&&!voiceUnlocked)unlockVoice()},{once:true,passive:true});
updateVoice();
if(!token){showEntry()}else{startApp();refresh().then(connect).catch(e=>showEntry(e.message))}
setInterval(()=>{if(token&&Date.now()-lastStateAt>8000)refresh().catch(()=>setSync('warn','RECONECTANDO…'))},5000);
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&token)refresh().catch(()=>{})});
})();
