'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'admin.html'), 'utf8');
const js = fs.readFileSync(path.join(root, 'js', 'admin-simplificado.js'), 'utf8');
const playerHtml = fs.readFileSync(path.join(root, 'jugador.html'), 'utf8');
const playerJs = fs.readFileSync(path.join(root, 'js', 'online-room-player.js'), 'utf8');
assert(html.includes('id="liveTransmissionBtn"'), 'Debe existir configuración de transmisión durante el sorteo.');
assert(html.includes('id="simulationChat"'), 'La simulación masiva debe permitir habilitar chat IA.');
assert(js.includes('document.documentElement.requestFullscreen()'), 'Fullscreen debe incluir overlays y reclamos.');
assert(js.includes('lastBallOf(data)'), 'El panel debe derivar la última bolilla desde el historial.');
assert(js.includes("d.roomSettings?.transmission?.enabled?'TRANSMISIÓN ✓':'TRANSMISIÓN'"), 'El panel debe reflejar el estado de transmisión en vivo.');

assert(playerHtml.includes('id="sequenceCard"'), 'La secuencia del jugador debe tener un panel identificable para el aviso especial.');
assert(playerJs.includes('transition.largeRoomNotice'), 'El jugador debe recibir el aviso especial antes del sorteo en salas grandes.');
assert(html.includes('id="startCriterionModal"'), 'Partidas de más de 20 jugadores deben mostrar el criterio antes de iniciar.');
assert(html.includes('VÁLIDA POSTERIOR'), 'El aviso debe explicar cómo se registran reclamos válidos posteriores.');
assert(js.includes('this.state.players.length>20'), 'El aviso especial debe activarse solo al superar 20 jugadores.');
assert(js.includes("claimAuditLabel(a)"), 'La vista del acta debe traducir el estado de auditoría a etiquetas legibles.');
console.log('PRUEBA UI ADMIN EN VIVO: OK');
