'use strict';
const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawn } = require('child_process');
const root = path.resolve(__dirname, '..');
const port = 49000 + Math.floor(Math.random()*400);
const base = `http://127.0.0.1:${port}`;
const dataDir = fs.mkdtempSync(path.join(os.tmpdir(), 'la-gorda-community-'));
const password = 'community-test-2026';
const child = spawn(process.execPath, ['server.js'], { cwd:root, env:{...process.env,PORT:String(port),ONLINE_MODE:'true',MASTER_ADMIN_PASSWORD:password,PUBLIC_URL:base,BINGO_DATA_DIR:dataDir}, stdio:['ignore','pipe','pipe'] });
let logs=''; child.stdout.on('data',c=>logs+=c); child.stderr.on('data',c=>logs+=c);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function wait(){for(let i=0;i<120;i++){try{if((await fetch(base+'/healthz')).ok)return}catch{}await sleep(40)}throw new Error(logs)}
async function json(url,opt={}){const r=await fetch(base+url,opt);const d=await r.json().catch(()=>({}));return {r,d}}
(async()=>{try{
  await wait();
  const html=await (await fetch(base+'/comunidad')).text();
  assert(html.includes('Jugá · Charlá · Enterate'));
  assert(html.includes('id="chatDrawer"'));
  assert(html.includes('data-open-game="red_black"'));
  assert(html.includes('id="nameForm"'));
  assert(html.includes('id="emojiBtn"'));
  assert(html.includes('id="stickerBtn"'));
  assert(html.includes('/js/emoji-stickers.js'));
  const communityJs=await (await fetch(base+'/js/community.js')).text();
  assert(communityJs.includes('focusNameInput'));
  assert(communityJs.includes('sendSticker'));
  let x=await json('/api/community/state?visitorId=v1'); assert.equal(x.r.status,200); assert(x.d.onlineCount>=1);
  x=await json('/api/community/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({visitorId:'v1',name:'ADMIN',text:'hola'})}); assert.equal(x.r.status,400);
  x=await json('/api/community/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({visitorId:'v1',name:'Marta',text:'Hola comunidad'})}); assert.equal(x.r.status,200); assert.equal(x.d.message.name,'Marta'); assert.equal(x.d.message.type,'text');
  x=await json('/api/community/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({visitorId:'v1',name:'Marta',stickerId:'gorda-risa'})}); assert.equal(x.r.status,200); assert.equal(x.d.message.type,'sticker'); assert.equal(x.d.message.stickerId,'gorda-risa'); assert.equal(x.d.message.text,'');
  x=await json('/api/community/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({visitorId:'v1',name:'Marta',stickerId:'no-existe'})}); assert.equal(x.r.status,400);
  x=await json('/api/community/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({visitorId:'v1',name:'Marta',stickerId:'corazon'})}); assert.equal(x.r.status,400); assert(/otro sticker/i.test(x.d.error));
  await sleep(1900);
  x=await json('/api/community/score',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({visitorId:'v1',name:'Marta',gameType:'red_black',score:7})}); assert.equal(x.r.status,200); assert.equal(x.d.leaderboards.red_black[0].bestScore,7);
  const login=await json('/api/master/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})}); assert.equal(login.r.status,200);
  const mh={'Content-Type':'application/json','X-Master-Token':login.d.token};
  x=await json('/api/master/community/settings',{method:'POST',headers:mh,body:JSON.stringify({whatsappGroup:'https://chat.whatsapp.com/AbCdEf123',whatsappNumber:'+54 9 376 1234567',chatEnabled:true,blockPhoneNumbers:true,blockWhatsappLinks:true})}); assert.equal(x.r.status,200); assert.equal(x.d.blockPhoneNumbers,true); assert.equal(x.d.blockWhatsappLinks,true);
  x=await json('/api/community/state?visitorId=v1'); assert.equal(x.d.whatsapp.groupUrl,'https://chat.whatsapp.com/AbCdEf123'); assert(x.d.whatsapp.contactUrl.includes('5493761234567'));
  x=await json('/api/master/community/moderate',{method:'POST',headers:mh,body:JSON.stringify({action:'block-term',term:'SPÁM'})}); assert.equal(x.r.status,200); assert(x.d.blockedTerms.includes('spam'));
  x=await json('/api/community/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({visitorId:'v1',name:'Marta',text:'Esto es spam'})}); assert.equal(x.r.status,400); assert(/contenido no permitido/i.test(x.d.error));
  x=await json('/api/community/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({visitorId:'v1',name:'Marta',text:'s.p.a.m otra vez'})}); assert.equal(x.r.status,400);
  x=await json('/api/community/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({visitorId:'v1',name:'Marta',text:'Mi numero es 351 612 3456'})}); assert.equal(x.r.status,400); assert(/datos de contacto/i.test(x.d.error));
  x=await json('/api/community/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({visitorId:'v1',name:'Marta',text:'3 5 1 6 1 2 3 4 5 6'})}); assert.equal(x.r.status,400);
  x=await json('/api/community/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({visitorId:'v1',name:'Marta',text:'Escribime en wa.me/5493516123456'})}); assert.equal(x.r.status,400);
  await sleep(1900);
  x=await json('/api/community/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({visitorId:'v1',name:'Marta',text:'Sala 4821, bolilla 48, carton 123, jugamos 21:30'})}); assert.equal(x.r.status,200);
  x=await json('/api/master/community/moderate',{method:'POST',headers:mh,body:JSON.stringify({action:'unblock-term',term:'spam'})}); assert.equal(x.r.status,200); assert(!x.d.blockedTerms.includes('spam'));
  x=await json('/api/master/community/moderate',{method:'POST',headers:mh,body:JSON.stringify({action:'clear'})}); assert.equal(x.r.status,200); assert.equal(x.d.messages.length,0);
  console.log('PRUEBA COMUNIDAD: OK');
}catch(e){console.error(e);console.error(logs);process.exitCode=1}finally{child.kill('SIGTERM')}})();
