'use strict';
const fs=require('fs'),path=require('path'),root=path.join(__dirname,'..');
const must=(ok,msg)=>{if(!ok){console.error('FUNCIONAL UI FAIL:',msg);process.exit(1)}};
const admin=fs.readFileSync(path.join(root,'admin.html'),'utf8');
const ajs=fs.readFileSync(path.join(root,'js/admin.js'),'utf8');
const player=fs.readFileSync(path.join(root,'player.html'),'utf8');
const pjs=fs.readFileSync(path.join(root,'js/player.js'),'utf8');
const css=fs.readFileSync(path.join(root,'css/platform.css'),'utf8');
const server=fs.readFileSync(path.join(root,'server.js'),'utf8');
const demo=fs.readFileSync(path.join(root,'demo.html'),'utf8');
must(admin.includes('AGREGAR Y GENERAR LINK'),'Admin debe generar links privados');
must(admin.includes('Hasta cartones')&&admin.includes('selected>4'),'El predeterminado debe ser 4');
must(!admin.includes('CLAVE DE LA SALA'),'La creación no debe pedir clave compartida');
must(admin.includes('ABRIR TRANSMISIÓN'),'Transmisión siempre disponible');
must(server.includes('joinOpen: false')&&server.includes('/invitacion/'),'Ingreso oficial por invitación privada');
must(server.includes("req.method === 'HEAD'")&&server.includes('consumeInvitationActivation')&&server.includes('NUNCA deben consumir la invitación'),'Preview GET/HEAD de WhatsApp no debe consumir invitaciones');
must(!pjs.includes('¿Reclamar')&&pjs.includes('RECLAMO ENVIADO…'),'Los premios deben reclamarse con un solo toque, sin confirmación previa');
must(server.includes('Tu acceso es personal')&&server.includes('NO NECESITÁS CLAVE'),'La pantalla /jugador no debe ofrecer clave pública');
must(pjs.includes('SALA DE ESPERA')&&pjs.includes('MINIJUEGOS')&&pjs.includes('waitingChat'),'Sala de espera social requerida');
must(player.includes('chatEmojiBtn')&&player.includes('chatStickerBtn')&&player.includes('Emojis · stickers · La Gorda'),'Chat de juego debe usar el patrón de Comunidad con emojis, stickers y La Gorda');
must(!player.toUpperCase().includes('GIF'),'No debe existir GIF');
must(!pjs.includes('<span>BOLILLA</span>')&&pjs.includes('ballProgress')&&pjs.includes('${drawnArr.length} / ${total}'),'Debe mostrar progreso X / total sin el rótulo BOLILLA en medio');
must(css.includes('radial-gradient')&&css.includes('.ballStage'),'Bolilla moderna requerida');
must(css.includes('communityStyleChat')&&css.includes('height:min(38dvh,320px)'),'Chat móvil compacto y basado en Comunidad');
must(!pjs.includes('class="quickStrip"')&&pjs.includes('class="primaryClaim')&&pjs.includes('class="prizeTrack"'),'El juego móvil debe eliminar herramientas duplicadas y usar reclamo principal compacto');
must(ajs.includes('https://wa.me/?text='),'Botón WhatsApp debe abrir WhatsApp');
must(demo.includes('Configurar DEMO')&&demo.includes('name="linePrizeCount"'),'DEMO debe usar configuración funcional de 90 con 1/2 líneas');
must(demo.includes('MINIJUEGOS')||demo.includes('Minijuego'),'DEMO debe explicar la sala de espera con minijuegos');
must(!demo.includes('demo-alfa.js')&&demo.includes('name="prizeAmbo"'),'DEMO no debe depender del cliente viejo y debe ofrecer AmboCabeza opcional en 90');
must(demo.includes('value="4" checked'),'DEMO Normal debe partir con 4 cartones por defecto');
must(player.includes('themeTool')&&pjs.includes('bingo_theme'),'Jugador debe recuperar Día/Noche y persistirlo');
must(demo.includes('demoThemeBtn')&&demo.includes('bingo_theme'),'DEMO debe recuperar Día/Noche');
const community=fs.readFileSync(path.join(root,'comunidad.html'),'utf8');
const tx=fs.readFileSync(path.join(root,'transmision.html'),'utf8');
const txjs=fs.readFileSync(path.join(root,'js/transmision.js'),'utf8');
const presenter=fs.readFileSync(path.join(root,'js/presenter-scripts.js'),'utf8');
must(!community.includes('communityThemeBtn')&&community.includes("document.documentElement.dataset.theme='night'"),'Comunidad debe permanecer siempre en modo nocturno');
must(tx.includes('data-theme="night"')&&!tx.includes('id="themeBtn"')&&txjs.includes("theme='night'"),'Transmisión debe permanecer solo en modo nocturno');
must(!presenter.includes("'Bolilla {n}'")&&presenter.includes("lineConfirmed: '¡{prize} para {name}! Reclamo válido.'"),'Cantador debe ser breve, natural y nombrar Primera/Segunda Línea correctamente');
console.log('PRUEBA UI CUASIFINAL FUNCIONAL: OK');
