'use strict';
const fs=require('fs'),path=require('path'),root=path.join(__dirname,'..');
const must=(ok,msg)=>{if(!ok){console.error('FUNCIONAL UI FAIL:',msg);process.exit(1)}};
const admin=fs.readFileSync(path.join(root,'admin.html'),'utf8');
const ajs=fs.readFileSync(path.join(root,'js/admin.js'),'utf8');
const player=fs.readFileSync(path.join(root,'player.html'),'utf8');
const pjs=fs.readFileSync(path.join(root,'js/player.js'),'utf8');
const css=fs.readFileSync(path.join(root,'css/platform.css'),'utf8');
const server=fs.readFileSync(path.join(root,'server.js'),'utf8');
const demo=fs.readFileSync(path.join(root,'demo.html'),'utf8');
must(admin.includes('AGREGAR Y GENERAR LINK'),'Admin debe generar links privados');
must(admin.includes('Hasta cartones')&&admin.includes('selected>4'),'El predeterminado debe ser 4');
must(!admin.includes('CLAVE DE LA SALA'),'La creación no debe pedir clave compartida');
must(admin.includes('ABRIR TRANSMISIÓN / TV'),'Transmisión siempre disponible');
must(server.includes('joinOpen: false')&&server.includes('/invitacion/'),'Ingreso oficial por invitación privada');
must(server.includes('Tu acceso es personal')&&server.includes('NO NECESITÁS CLAVE'),'La pantalla /jugador no debe ofrecer clave pública');
must(pjs.includes('SALA DE ESPERA')&&pjs.includes('MINIJUEGOS')&&pjs.includes('waitingChat'),'Sala de espera social requerida');
must(player.includes('EMOJIS')&&player.includes('STICKERS')&&player.includes('LA GORDA'),'Chat debe incluir las tres categorías');
must(!player.toUpperCase().includes('GIF'),'No debe existir GIF');
must(pjs.includes('BOLILLA')&&pjs.includes('ballProgress'),'Debe mostrar progreso de bolillas');
must(css.includes('radial-gradient')&&css.includes('.ballStage'),'Bolilla moderna requerida');
must(css.includes('height:min(38dvh,320px)'),'Chat móvil compacto');
must(pjs.indexOf('class="ticketPanel"') < pjs.indexOf('class="quickStrip"'),'En juego móvil el cartón debe quedar antes de herramientas secundarias');
must(ajs.includes('https://wa.me/?text='),'Botón WhatsApp debe abrir WhatsApp');
must(demo.includes('Configurar DEMO')&&demo.includes('name="linePrizeCount"'),'DEMO debe usar configuración funcional de 90 con 1/2 líneas');
must(demo.includes('MINIJUEGOS')||demo.includes('Minijuego'),'DEMO debe explicar la sala de espera con minijuegos');
must(!demo.includes('demo-alfa.js')&&!demo.includes('prizeAmbo'),'DEMO no debe depender del cliente viejo ni ofrecer Ambo en 90');
must(demo.includes('value="4" checked'),'DEMO Normal debe partir con 4 cartones por defecto');
console.log('PRUEBA UI CUASIFINAL FUNCIONAL: OK');
